### ISSUE TITLE
[Feature Request] Game Age Rating icons extension

### ISSUE THREAD

**Issue by Darthagnon** [darklinkpower/PlayniteExtensionsCollection#1]
Sorry to disturb you; I was wondering, since you're well-versed and know how to make Playnite plugins, whether you could make or help me make a plugin to display game Age Ratings in Playnite, via PEGI, ESRB, BBFC and CERO icons and content descriptors? 

I've collected the icons in this repo: https://github.com/Darthagnon/PEGI

**Comment by darklinkpower** [comment]
Hello, sorry didn't see this until now, I kind of missed it with all the notifications!

Sadly that's out of my knowledge but could be done after this is implemented in Playnite 9 easily https://github.com/JosefNemec/Playnite/issues/1702

The only current way is similar to how Lacro does it in his plugins but it might be worth waiting to add it after that is in Playnite

**Comment by Darthagnon** [comment]
That sounds like a good idea! Thank you!

**Comment by darklinkpower** [comment]
Closing since I don't have plans to develop an extension that does this.
