### ISSUE TITLE
[Extra Metata Video] Importing video for trailer from file deletes original file

### ISSUE THREAD

**Issue by Deytron** [darklinkpower/PlayniteExtensionsCollection#10]
I don't know if this has been reported, so I'm reporting it.

The options "Set trailer video for the selected game" and "Set microtrailer video for the selected game" don't work, and delete the original file in the process. This can be reproduced on any game :

- Right click on game and select one of the two options
- Set the video file, in my case an MP4 video
![image](https://user-images.githubusercontent.com/20344764/117843430-181bd500-b27f-11eb-8146-66b22568a963.png)
- Process is finished, but there is no trailer to be found, and the original file disappeared
![image](https://user-images.githubusercontent.com/20344764/117843580-3a155780-b27f-11eb-8ef5-633db68dac61.png)

The issue seems to be present on any game, and so far has only been tested with .mp4 files.

**Comment by darklinkpower** [comment]
Fixed a while ago but forgot to close
