### ISSUE TITLE
[Splash Screen] Global custom splashscreen image

### ISSUE THREAD

**Issue by Gildum** [darklinkpower/PlayniteExtensionsCollection#104]
**Extension**
Splash Screen

**Describe the solution you'd like**
Ability to choose a custom image to be used as the global splashscreen image. Once selected, it will be used for all games, even those that already have a metadata background image. 

Currently via the options you can only select a black image as the global splashscreen.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/54a5a732482ba9eff00cee23ce7d60e25ed3d269
