### ISSUE TITLE
[Splash Screen] Hide mouse cursor

### ISSUE THREAD

**Issue by Gildum** [darklinkpower/PlayniteExtensionsCollection#105]
**Extension**
Splash Screen

**Describe the solution you'd like**
Hide mouse cursor during splashscreen image phase for a nicer presentation.

darklinkpower mentioned that they are uncertain if that's possible. I have the following suggestion that might be simple to implement:

- right before the splashscreen image is activated, an ahk script will start that moves the mouse cursor to the bottom left corner of the screen, example:

`SetMouseDelay,-1`
`CoordMode, Mouse, Screen`
`MouseMove, 0, A_ScreenHeight`
`return`

- this script could be either included as part of the Splash Screen extension, by default or with an option in the settings to turn it on/off
- or allow users to insert their own custom powershell script right before splashscreen activates (just like it's implemented in playnite for each game or globally). This way the mouse hide ahk script can be enabled manually.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/08f0cbbfa5dd75764a9d5b63be8f0b5743660a66

**Comment by Gildum** [comment]
That's great, thank you for adding it!
