### ISSUE TITLE
[Extra Metadata Loader] Missing micro video tag not working correctly

### ISSUE THREAD

**Issue by philipjholm** [darklinkpower/PlayniteExtensionsCollection#106]
**Extension**
Extra Metadata Loader

**Describe the bug**
The function to tag games with missing micro videos is not working as all games get the tag no matter what.

**To Reproduce**
Make sure you have a game that doesn't have micro video and no missing micro video tag.
Go to Add-ons and go to settings for the plugin. Make sure that checkbox "Update tag that indicates if a game is missing micro video on library update" is checked.

**Expected behavior**
A game that already has a micro video should not get a missing micro video tag, but right now all games get that tag no matter if it has a video or not.

**Screenshots**
<img width="202" alt="1" src="https://user-images.githubusercontent.com/37110163/140569406-4304727e-65a4-4324-a313-7549cdbc1bd2.png">
<img width="294" alt="2" src="https://user-images.githubusercontent.com/37110163/140569409-d01cad25-a00e-4415-9414-b0ceffa5440c.png">

**Extensions log**
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7488556/extensions.log)

**Comment by darklinkpower** [comment]
Fixed
