### ISSUE TITLE
[Extra Metadata Loader] Logos Not Being Displayed

### ISSUE THREAD

**Issue by Kyzoku** [darklinkpower/PlayniteExtensionsCollection#113]
**Extension**
Extra Metadata Loader

**Describe the bug**
I have used the tool to download logos for the games in my library, but they are not being displayed.  All that gets displayed is the games name in white text.  I opened the Extra Metadata folder and confirm that the logo image is there.  I checked to make sure my theme wasn't the issue and the problem persists on Classic.

**To Reproduce**
Download Logo, Logo Downloaded, Nothing Displays.

**Expected behavior**
Download Logo, Logo Downloaded, Logo Displayed.

**Screenshots**
![Extra_Metadata_Loader_-_Screenshot 1](https://user-images.githubusercontent.com/49911814/141226005-f9622b88-4cd4-4ac2-a8f6-957ee842f909.jpg)

![Extra_Metadata_Loader_-_Screenshot 2](https://user-images.githubusercontent.com/49911814/141226055-b646411f-f3b2-4814-ac3a-46a80817be66.jpg)

**Extensions log**
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7517188/extensions.log)

**Comment by darklinkpower** [comment]
The theme you use must implement support to display the extension controls, otherwise they won't show. You need to ask the theme developer or you must add support to the theme https://github.com/darklinkpower/PlayniteExtensionsCollection/wiki/Extra-Metadata-Loader

**Comment by Kyzoku** [comment]
I actually figured the issue out, which had nothing to do with the theme by the way.  The issue was my drive containing Playnite was assigned a different drive letter and it was trying to find the logos on the other drive letter.

**Comment by darklinkpower** [comment]
As I mentioned the theme needs to support the extension. It's loading logos in the deprecated way, on its own via code theme, which will cause these issues and more.
