### ISSUE TITLE
[News Viewer] Generate news for games from libraries other than Steam where the game is also available on Steam

### ISSUE THREAD

**Issue by SlipperyJim** [darklinkpower/PlayniteExtensionsCollection#114]
**Extension**
News Viewer

**Describe the solution you'd like**
Similar to your Video viewer, it would be great to get news for games that are on libraries other than steam (and where the game has a steam version). 

**Screenshots**
Not applicable

**Comment by SlipperyJim** [comment]
I know you weren't sure about this when it was discussed on Discord and I see it wasn't in the latest update to the News Viewer, so have you decided against adding it ? :(

**Comment by darklinkpower** [comment]
I'm not against this being an option hence why the issue is still open. Please be understanding that I'm not a programmer and I learn and develop themes and extensions as a hobby when I can, which unfortunately means I can't work on all requested features and there has to be priorities.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/4af1423aa62a7a61033c31874d06f9ab68bd9530

**Comment by SlipperyJim** [comment]
Now I feel really bad for having chased this up as it's not like I don't know how many plates you have spinning at the moment. 

In my (fairly rubbish) defence, I had thought that as it was something you had already implemented in the video viewer addon already that it was a fairly straightforward thing to do here too (but I am a long, long way from a programmer) and that it wasn't time or resources that was the issue but that you were not in favour of adding it, so I was hoping the comment was one last chance at persuading you.

Thank you for adding the option - it's much appreciated, as is your continuing work on all of your addons and themes. You many claim not to be a programmer (and I'm really not sure that's at all fair), but the things you have added to Playnite make a massive difference to the project.
