### ISSUE TITLE
[Extra Metadata Loader] Show game name on logo selection screen

### ISSUE THREAD

**Issue by erys** [darklinkpower/PlayniteExtensionsCollection#115]
**Extra Metadata Loader**

**Add Game title on logo select screen**
When you're downloading logos for a number of games at once, it's not always clear which game is being asked about on the select logo screen. See screenshot for example. In that example, I have 8 Higurashi Hou games, and I'm pretty sure that it's on episode 1, but I'm not completely sure, since only one of the possible logos includes an episode number. If it said "Select logo for `<game title>`" instead of just "Select logo", that would be really helpful.

**Screenshots**

![Select logo-2021-11-12 19_29_19](https://user-images.githubusercontent.com/12535744/141598424-e13d9cfc-234b-4866-8947-f9a4529acedd.png)

**Comment by darklinkpower** [comment]
Done
