### ISSUE TITLE
[Steam Tags Importer] Option not available with eMixedNite

### ISSUE THREAD

**Issue by DrHaTed** [darklinkpower/PlayniteExtensionsCollection#116]
**Extension**
Steam Tags Importer

**Describe the bug**
Instructions state "Select the function from the Playnite extensions submenu"
When I right click there is no option. Neither extension settings.
Platform is set to Steam. 

**To Reproduce**
Use Playnite 9.6, eMixedNite 2.44, Steam Tags Importer 2.6

**Expected behavior**
I assume there should be an option when I right click the game and download tags

**Screenshots**
Will add if it helps.

**Extensions log**
Attach Playnite's `Extensions.log` file. It is located in Playnite's installation directory in the portable version or in `%AppData%\Playnite` (Can be pasted in Explorer) in the installed version
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7532825/extensions.log)

**Comment by darklinkpower** [comment]
The menu functions are located in the main menu extensions submenu, not the game right click menu 
![image](https://user-images.githubusercontent.com/1389286/141661419-9336da33-cb96-450e-95e5-cf19c7e44038.png)
