### ISSUE TITLE
[Extra Metadata Loader] Video trailer automatically in full screen mode

### ISSUE THREAD

**Issue by LuKa8989** [darklinkpower/PlayniteExtensionsCollection#118]
Extra Metadata Loader

Re-add the function to start the video trailers automatically in full screen mode with both audio and without audio thank you very much

**Comment by darklinkpower** [comment]
Replied on discord

> I'm sorry if I wasn't clear but what I meant by that is that fullscreen themes are not using the video player from the Extra Metadata Loader extension, they are using their own player so any setting you configure in the extension will not apply, as it's something unrelated.
You need to contact the theme developer to provide their own way to do what you requested
