### ISSUE TITLE
[Extra Metadata Loader] Restore ability to add Logo from URL and/or Local File

### ISSUE THREAD

**Issue by sofmarch** [darklinkpower/PlayniteExtensionsCollection#119]
**Extension**
Extra Metadata Loader

**Describe the solution you'd like**
The previous versions of Extra Metadata Loader (now known as Extra Metadata Fullscreen Mode Helper) included the ability to add a logo from a local file or from a URL. This was especially useful for games that are neither on Steam or have listings on SteamGridDB, such as small projects from Itch.io or mods from ModDB, etc.

**Comment by darklinkpower** [comment]
Just to clarify, it's not restoring but to implement, as `Extra Metadata Tools`, the extension which had this function, was/is a complete separate extension so the functionality was never included in the `Extra Metadata Loader` extension.

**Comment by darklinkpower** [comment]
I just noticed that this is a duplicate https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/117
