### ISSUE TITLE
[Extra Metadata Loader] Adding logo from file does not load up the logo.

### ISSUE THREAD

**Issue by KiimaRo** [darklinkpower/PlayniteExtensionsCollection#121]
Extra Metadata Loader

**Describe the bug**
Adding logo from file does not actually add the logo. Nothing shows up

**To Reproduce**
Adding logo from file?

**Expected behavior**
Logo shows up

**Screenshots**

**Extensions log**
Attach Playnite's `Extensions.log` file. It is located in Playnite's installation directory in the portable version or in `%AppData%\Playnite` (Can be pasted in Explorer) in the installed version
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7581605/extensions.log)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/27d38f517eb34606add494bf8f5f80f922f34e31
