### ISSUE TITLE
[Importer for anilist] Bug description

### ISSUE THREAD

**Issue by Kdog88** [darklinkpower/PlayniteExtensionsCollection#124]
**Extension**
importer for anilist
**Describe the bug**
extension fails to import titles into the playnite library

**To Reproduce**
updating the anilist library

**Expected behavior**
succesfully importing new titles/updating existing titles within the playnite library.
**Screenshots**

**Extensions log**
Attach Playnite's `Extensions.log` file. It is located in Playnite's installation directory in the portable version or in `%AppData%\Playnite` (Can be pasted in Explorer) in the installed versio
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7599384/extensions.log)
![2021-11-24 14-30-41](https://user-images.githubusercontent.com/49170700/143330289-dec019e7-f537-42bf-9ed7-e96776f9b8ef.JPG)
n

**Comment by darklinkpower** [comment]
Fixed
