### ISSUE TITLE
[PlayState] Ability to switch from one suspended game to another among more games

### ISSUE THREAD

**Issue by LuKa8989** [darklinkpower/PlayniteExtensionsCollection#126]
PlayState

add the ability to switch from a game in suspension to others and be able to reactivate previously suspended games

**Comment by exoduscl** [comment]
This would be a great addition, is it possible?

**Comment by BanCrash** [comment]
When #194 is merged I will try to add processes for each app to the new PlayStateData class, and as a first approach make that at least when you close one game, if that game was the currentGame you can control again the previous currentGame, so you can pause / resume the currentGame always, even if another game was launched after.

For the future, the best approach for this IMO is, for one side add a GUI where easily control this, and for other side also add hotkeys for switching to the next or previous currentGame. Also one hotkey for opening the GUI would be useful I think.

In this GUI you would be able to change the actual currentGame, and pause or resume the games even if they are not the currentGame. 

This is just an idea and don't know if / when I'll work on it, nor if @darklinkpower likes this idea or want to work on it. For the moment I only have planned to do the first paragraph.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/ce0e48c83d42cfcaf9909ef47b1037843c6cf360 and https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/fb88bc2e46c95f0cd91785e0bf59d59c9e9d12b3

To change the active game go to the sidebar to open a manager for the extension. I will post a release of this after it's been more thoroughly tested.

![image](https://user-images.githubusercontent.com/1389286/161369533-4befce07-8c61-4c66-aa34-77670e6fc3ef.png)
