### ISSUE TITLE
[PlayState] Doesn't work on games ran as Administrator

### ISSUE THREAD

**Issue by mainmango** [darklinkpower/PlayniteExtensionsCollection#128]
**Extension**
PlayState

**Describe the bug**
PlayState doesn't work when games are ran as administrator.

**To Reproduce**
Launch game as Administrator

**Expected behavior**
PlayState should be able to suspend games even if they are ran as administrator

**Comment by darklinkpower** [comment]
Unfortunately there's nothing that can be done if the game has higher privileges. It would probably work if you launch Playnite as admin but that's a bad idea because you would give admin right to all extensions and apps/games launched from Playnite.
