### ISSUE TITLE
[Extra Metadata Loader] Fullscreen/Desktop mode switching issues

### ISSUE THREAD

**Issue by dotexe1337** [darklinkpower/PlayniteExtensionsCollection#129]
**Extension**
Extra Metadata Loader

**Describe the bug**
When switching between fullscreen/desktop mode for the first time, the program will bug out and open 2 copies of itself, with a "Playnite closed unexpectedly while starting" error on both.

**To Reproduce**
Enable Extra Metadata Loader, open the program, and hit F11 and the issue will occur.

**Expected behavior**
The program should not open two copies of itself.

**Screenshots**
[YouTube video](https://www.youtube.com/watch?v=HQH1myej92Y)

**Extensions log**
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7627809/extensions.log)

**Comment by darklinkpower** [comment]
Closing since it's a bug in Playnite itself

![image](https://user-images.githubusercontent.com/1389286/145163759-ec9ba7fe-3c49-4709-a006-59f3c70453b3.png)
