### ISSUE TITLE
[Steam Tags Importer] Allow to select which tags to import?

### ISSUE THREAD

**Issue by Jhanlon95** [darklinkpower/PlayniteExtensionsCollection#130]
**Extension**
Steam Tags Importer

**Describe the solution you'd like**
When selecting to import tags for a game it would be nice to if for instance we could ask for 5 tags and then select the ones that we do want to be added. Most of the time I just want to add the Horror tag to games (since Steam doesn't give it a genre) and end up with multiple newly created tags, which then I need to uncheck for the game and then remove from my library.

**Screenshots**
N/A

**Comment by darklinkpower** [comment]
I'm no longer developing and maintaining the extension. The extension is now developed by Jeshibu over at https://github.com/Jeshibu/PlayniteExtensions, if there are new feature requests or bug reports please open an issue in that repository
