### ISSUE TITLE
[Extra MetaData Loader] No Menu Entry

### ISSUE THREAD

**Issue by n-els** [darklinkpower/PlayniteExtensionsCollection#133]
**Extension**
Extra Meta Data Loader

**Describe the bug**
There is no entry in the menu for setting up this Addon.

**To Reproduce**
Install this Addon (and restart).

**Expected behavior**
There should be a menu entry anywhere.

**Screenshots**
![image](https://user-images.githubusercontent.com/78740982/145617635-8e97d29b-d07a-47a0-9c2d-dae3883b837b.png)
![image](https://user-images.githubusercontent.com/78740982/145617768-bc6de44a-6ea5-4333-a530-1befbcbc6c6e.png)

**Comment by darklinkpower** [comment]
Menu items are in the right click game menu

**Comment by n-els** [comment]
Okay, but where can i find these settings: 

![image](https://user-images.githubusercontent.com/78740982/145619942-dddce95b-68d0-4e72-ae13-733f4de9a1ab.png)
