### ISSUE TITLE
[Splash Screen] Per Game Toggle of Splash Screen Visibility

### ISSUE THREAD

**Issue by EmilyLove26** [darklinkpower/PlayniteExtensionsCollection#140]
**Extension**
Splash Screen

**Describe the solution you'd like**
I'd like a toggle of some kind, or maybe a tag, to have games NOT show a splash screen. On some games, the splash screen doesn't want to disappear for a while, meanwhile the game has been running in the background for a bit. Being able to disable the splash screen on a per game basis would be fantastic!

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/4e5f09c3ea746e77814c30baa75214cf07476257

**Comment by EmilyLove26** [comment]
Dude you’re awesome. Thank you!

[Emily Love - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1ca3sv)	[1ca3sv]
