### ISSUE TITLE
[Extrametadata Loader] Downloaded Youtube videos not working correctly

### ISSUE THREAD

**Issue by azuravian** [darklinkpower/PlayniteExtensionsCollection#141]
**Extension**
Extrametadata Loader

**Describe the bug**
Videos downloaded from youtube do not play in Playnite.  Videos play in external player (VLC), but with no audio.

**To Reproduce**
1. Select game
2. Extra Metadata | Videos | Videos | Download Video from Youtube
3. Select video from list
4. Click "Download Selected Video" and close extension when complete.
5. Select game in Playnite using theme with video support
6. Video does not play
7. Open Extra Metadata folder for game,
8. Launch video using VLC.
9. Video plays, but with no audio.
 

**Expected behavior**
The video would play in Playnite and would have audio in VLC.

I have also manually downloaded the same videos using YT-DLG (the gui for yt-dlp) and the resulting videos worked in Playnite when put in the Extra Metadata folder.

**Extensions log**
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7741873/extensions.log)

**Comment by darklinkpower** [comment]
Did you check if this was fixed by updating the dependencies? yt-dlp, ffmpeg and ffprobe

**Comment by azuravian** [comment]
Thanks, closing this now.  Not sure which one it was, but I just updated everything and it's working great now.
