### ISSUE TITLE
[Resolution Changer] Addition of Refresh Rate

### ISSUE THREAD

**Issue by TobiGrul** [darklinkpower/PlayniteExtensionsCollection#142]
**Extension**
Resolution Changer

**Describe the solution you'd like**
Add possibility so set individual monitor refresh rate per game.

**Comment by darklinkpower** [comment]
Hello. Please fill the information uaing the issue template in the future.

**Comment by dariusaurius** [comment]
wonderfull idea, please allow me to add that also the refresh rate for the resolution before the game started, possibly be changed back after quitting the game to the highest available or defined one. Currently Windows is always using the default refresh rate defined in the display control data for each resolution.

Example screenshot of default settings for my 120hz TV:

![Screenshot cru utility](https://user-images.githubusercontent.com/58703994/152705010-7a695681-9b6a-45a9-823d-ae689529c198.png)

**Comment by ReenigneCA** [comment]
The way the extension is currently written it would require extensive GUI rework or a gigantic menu list of resolution refresh rate combinations to make this change. Would everyone be happy with just defaulting to the highest refresh rate possible for a given resolution? Everything would remain the same but whenever the extension chose to change the refresh rate it would enumerate all possible refresh rates for the given resolution and choose the highest one. I just put this type of logic in as an optional ini option for moonlight_hdr_launcher though it hasn't been accepted yet. The C++ code is:

```
DWORD get_max_refresh_rate(uint16_t width, uint16_t height) {
    DWORD max_refresh_rate = 0;
    for (DWORD graphics_mode_index = 0;; ++graphics_mode_index) {
        DEVMODE devmode{};
        devmode.dmSize = sizeof(devmode);
        auto rval = EnumDisplaySettings(0, graphics_mode_index, &devmode);
        if (rval == 0)
            break;
        if (devmode.dmPelsWidth == width && devmode.dmPelsHeight == height)
            max_refresh_rate = std::max(max_refresh_rate, devmode.dmDisplayFrequency);
    }

    return max_refresh_rate;
}

template<typename log_function>
void set_resolution(uint16_t width, uint16_t height, uint16_t refresh_rate, bool wait_on_process, bool refresh_rate_use_max, log_function log_func) {
    DEVMODE devmode{};
    devmode.dmSize = sizeof(devmode);
    devmode.dmPelsWidth = width;
    devmode.dmPelsHeight = height;
    devmode.dmFields = DM_PELSHEIGHT | DM_PELSWIDTH;
    if (refresh_rate == 0 && refresh_rate_use_max) {
        log_func("setting max refresh_rate"s);
        refresh_rate = get_max_refresh_rate(width, height);
    }
    else {
        if (refresh_rate_use_max)
            log_func("refresh_rate and refresh_rate_use_max specified, defaulting to specified rate"s);
    }
    if (refresh_rate != 0) {
        devmode.dmDisplayFrequency = refresh_rate;
        devmode.dmFields |= DM_DISPLAYFREQUENCY;
    }
    DWORD result;
    if(wait_on_process) // if we are waiting on the process we can clean up at the end
        result = _ChangeDisplaySettings(&devmode, CDS_UPDATEREGISTRY);
    else //otherwise we do the best we can
        result = _ChangeDisplaySettings(&devmode, 0);
    if (result != DISP_CHANGE_SUCCESSFUL) {
        log_func("ChangeDisplaySettings failed error:" + std::to_string(result));
    }
}

```

For this case it would have to be converted to C# and the set_resolution code would be simplified a bit as you'd just use get_max_refresh_rate on every display mode change. I was going to just put this into a pull request but I figured out that for my specific use case it works perfectly to just put it into moonlight_hdr_launcher and for that niche case I don't think this extension actually handles all the issues I was trying to solve that were wrapped up in non-standard gamestream resolutions. Anyway I currently don't use this extension but if someone from the project signs off on the plan it would be easy enough for me to do the C# conversion and implement this change. Though if someone familiar with the plugin who has a dev environment setup likes this idea they can probably implement and test it in a few minutes. Let me know.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/f98a57dd589257809c30c9e8f28dc774fcee2c00
