### ISSUE TITLE
[Steam Description Cleaner] Ability to filter clutter in other languages like German

### ISSUE THREAD

**Issue by GogetaCross** [darklinkpower/PlayniteExtensionsCollection#146]
### Extension name

Steam Description Cleaner

### Feature Description

The extension only works in English so far.
It would be great if clutter from otgher languages could also be filtered out.

**Comment by darklinkpower** [comment]
Linking for reference https://github.com/Lacro59/playnite-descriptioneditor-plugin/blob/master/source/HtmlHelper.cs#L219-L247

**Comment by darklinkpower** [comment]
Closed as discussed on discord.
