### ISSUE TITLE
[PCGamingWiki Metadata Provider --or similar--] Ability to pull entire PCGW page for game, display alongside metadata.

### ISSUE THREAD

**Issue by ParasiteDelta** [darklinkpower/PlayniteExtensionsCollection#147]
### Extension name

PCGamingWiki Metadata Provider

### Feature Description

So, the title does a poor job describing what I mean. Allow to me clarify.

When you select a game in Playnite, you get the game page with its metadata, including some links. What I was wondering is if it would be possible to create or modify an addon that would pull the PCGW page for the selected game in its entirety, save it locally, and display it under its own section on the relevant Playnite game page, maybe with collapsible segments for game metadata, PCGW info, etc.

It would hold a similar purpose to pulling and storing the game's metadata, where you could <for example> open a collapsible segment on the game's page labeled "PCGamingWiki" and read the entire page, complete with fixes, workarounds, etc. without needing to visit the page itself. You could update the PCGW manually via addon settings or a new dropdown button for that particular game entry in your library.

As to why I don't tinker around with it, well, I don't hate my life enough to delve back into C#, Visual Studio, and the relevant ecosystem for any reason, especially something that I could probably script using Python or Lua.

### Screenshots

![image](https://user-images.githubusercontent.com/19669733/147840286-0b23dd87-f92e-4b92-8690-cbbbea2db374.png)

**Comment by darklinkpower** [comment]
Sorry but I don't plan to make a new extension that does this. You could probably ask in the Playnite discord and see if someone else is interested in making it.
