### ISSUE TITLE
[Extra Metadata Loader] Ability to download NSFW and Humor logos from SGDB

### ISSUE THREAD

**Issue by Nes370** [darklinkpower/PlayniteExtensionsCollection#150]
### Extension name

Extra Metadata Loader

### Feature Description

Logos tagged as Adult Content and Humor are excluded when using the "Download logos from SteamGridDB for selected games" action. It would be nice to have a setting to include those logos as download options.

### Screenshots

Logos available on SGDB for Dark Souls: Prepare to Die
![image](https://user-images.githubusercontent.com/25238987/148630514-e693828a-faf4-4a55-9abe-0bd0c84a9e42.png)

Download options using Extra Metadata Loader
![image](https://user-images.githubusercontent.com/25238987/148630457-30ca522d-df4e-4655-a707-235e4e6c20be.png)

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/bb9a5340aaefbd2ebbfcc902809f041d9e2d1749

**Comment by Nes370** [comment]
Thanks!
