### ISSUE TITLE
[Review Viewer] Display review timestamp

### ISSUE THREAD

**Issue by poetickatana** [darklinkpower/PlayniteExtensionsCollection#153]
### Extension name

Review viewer

### Feature Description

It would be helpful if a review's timestamp was displayed underneath the playtime, just like it is on Steam.

### Screenshots

![Review Timestamp](https://user-images.githubusercontent.com/95546621/148712281-ad0ec7d2-79c9-4844-878d-2cda12051e7d.JPG)

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/bf036dbfffeec71f051a9b48882a80b8c43d4cd0
