### ISSUE TITLE
[Extra Metadata Loader] Logos not overwriting/deleting properly

### ISSUE THREAD

**Issue by Nes370** [darklinkpower/PlayniteExtensionsCollection#155]
### Extension name

Extra Metadata Loader

### Bug Description

After the latest update (v1.28), newly downloaded logos fail to overwrite existing ones. And attempting to delete existing logos fails.

### To Reproduce

Right click > Extra Metadata > Logos > Download logos from SteamGridDB for selected games

![image](https://user-images.githubusercontent.com/25238987/148720920-60d48031-ef00-4da7-86a5-6906f944ec3e.png)

![image](https://user-images.githubusercontent.com/25238987/148720935-1a5fad40-d84a-4d19-8098-0925c02249c7.png)

![image](https://user-images.githubusercontent.com/25238987/148720957-af6cadb1-42f3-4cb5-a21e-211e2f72855e.png)

![image](https://user-images.githubusercontent.com/25238987/148721011-5e49ea14-85fe-45d7-9490-7c7414501e17.png)
Logo fails to overwrite old one.

----

Right click > Extra Metadata > Logos > Delete logos of selected games

![image](https://user-images.githubusercontent.com/25238987/148720502-264211ed-8842-4b93-a9ba-0130b1947235.png)

![image](https://user-images.githubusercontent.com/25238987/148720411-1872af24-8b79-4603-817b-ef20aa28af5c.png)
Logo deletion fails.

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7836899/extensions.log)

**Comment by darklinkpower** [comment]
That is caused by the theme you are using, which is loading logos in an unsupported way and not via the extension, which locks the logo files. It has already been reported before

https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/95

**Comment by Nes370** [comment]
Ah, thank you for the information.
