### ISSUE TITLE
[NVIDIA GFN ENABLER] Support for Origin Games

### ISSUE THREAD

**Issue by Knicey** [darklinkpower/PlayniteExtensionsCollection#156]
### Extension name

GeForceNOW Enabler

### Feature Description

Some Origin games are supported by GeForceNOW including: Battlefield 4, Battleifled 1, Battlfield 5, Dragon Age Inquisition, and more.
Please add support for these games through GeForceNOW Enabler.

### Screenshots

![image](https://user-images.githubusercontent.com/45131167/148821923-d9c8489f-e262-4c48-a7ca-409e485b8aa7.png)

**Comment by darklinkpower** [comment]
What are the names of the games in your Playnite library? Matching for everything but Steam is done using the name, so they must be very different. Please share them to see if something can be done.

This is what they use in GFN database 

![image](https://user-images.githubusercontent.com/1389286/148835021-91a055d6-4be7-4b1b-85a4-5af37119b0d1.png)

![image](https://user-images.githubusercontent.com/1389286/148835147-afebb6df-f174-48f5-8cee-4b0ce00c4a8f.png)

**Comment by Knicey** [comment]
I see, I thought this might have been the issue. I own the base versions of all of these games so that is probably why they aren't recognized in the extension.

**Comment by Knicey** [comment]
The obvious solution would be to register the base games as compatible on a case by case basis, but I'm not sure what a long term solution would be.

**Comment by darklinkpower** [comment]
I've added some measures to fix this, can you check if this still happens?

**Comment by Knicey** [comment]
> I've added some measures to fix this, can you check if this still happens?

It seems to have fixed the issue! Let's hope it doesn't happen again when they add more EA games to the service.

**Comment by darklinkpower** [comment]
Unfortunately I'm afraid that a lot of these fixes will have to be game specific. If you find more please open a new issue.
