### ISSUE TITLE
[Extra Metadata Loader ] Videos are not visible in supported themes

### ISSUE THREAD

**Issue by WoofWoofGrr** [darklinkpower/PlayniteExtensionsCollection#159]
### Extension name

Extra Metadata Loader

### Bug Description

Videos/audio do not play but player controls are visible. Video player controls respond to mouse hover/clicks and correctly disappear when selecting a game without downloaded videos if Steam trailer steaming is off.

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7862210/extensions.log)

### Screenshots

![image](https://user-images.githubusercontent.com/76901281/149319785-8e7576f1-0cc0-4b4d-bcf5-cdbe960547fe.png)

**Comment by darklinkpower** [comment]
First verify that Windows Media Player is installed in your system. If it's not installed you can install it from here. https://support.microsoft.com/en-us/windows/get-windows-media-player-81718e0d-cfce-25b1-aee3-94596b658287

**Comment by WoofWoofGrr** [comment]
Thanks, that was it.
