### ISSUE TITLE
Splash Screen - Image stuck on some games

### ISSUE THREAD

**Issue by batero2000** [darklinkpower/PlayniteExtensionsCollection#16]
Hi everyone, so I'm trying this new extension on my PC and it seems that the cover picture at Powershell get's stuck, preventing games from starting, anyways this happens to me only in some games, ex. Geometry Dash.
Otherwise, the extension it's pretty cool, I would like for example that you can select a custom picture besides video for game splash, or even the same splash for all the games (I like the Playnite default splash within the extension, although if you have cover for the game, it will show that picture instead).

**Comment by darklinkpower** [comment]
Sorry for the delay in the reply, I had not seen the issue.

Unfortunately some games can fail to take focus over the splashscreen for some reason. If you have any problematic games you can disable the splashscreen by selecting the game in the Playnite UI and using this function

![image](https://user-images.githubusercontent.com/1389286/122506944-f07a0400-cfc4-11eb-86ab-32f1fa0d9121.png)

I'll see if I can add a way to add a custom default splash screen.

**Comment by darklinkpower** [comment]
The extension has been reworked since this and doesn't use Powershell anymore so this issue should not happen. If the issue still happens please let me know to reopen the issue.

**Comment by Wolf-ON** [comment]
I'm using the latest (2.26) Splash Screen extension.

I observed probably similar issue as this old one.

It starts normally: plays a short video intro, splash screen appears, and I can see that the game is starting (window with a black screen). But as soon the game window tries to go full screen, the splash-screen image goes back to the foreground and I need to alt+tab to see the launched game

(and yes, I have "automatically close splashcreen in ___" options enabled)
