### ISSUE TITLE
[Steam Tags Importer] Automatically import tags for newly added games

### ISSUE THREAD

**Issue by nicksundermeyer** [darklinkpower/PlayniteExtensionsCollection#163]
### Extension name

Steam Tags Importer

### Feature Description

It would be really nice to not have to manually add tags to every new game in my library, but instead for it just to be a part of the process as they get added automatically! Have an option to have the Steam Tags Importer automatically import a certain number of tags for new games as they are added to the library. Either just a checkbox to add 5 tags automatically, or something where we could set a number of tags to add to every new game.

**Comment by darklinkpower** [comment]
This feature was added for v3.0

I'm no longer developing and maintaining the extension. The extension is now developed by Jeshibu over at https://github.com/Jeshibu/PlayniteExtensions, if there are new feature requests or bug reports please open an issue in that repository
