### ISSUE TITLE
[Steam Tags Importer] Extension fails to import tags with an error

### ISSUE THREAD

**Issue by nicksundermeyer** [darklinkpower/PlayniteExtensionsCollection#164]
### Extension name

Steam Tags Importer

### Bug Description

When trying to download five tags for certain games, the download will fail and give an error message, and won't download for any of the tags for the game. This happens specifically in Battlefield V in my library.

### To Reproduce

1. Select Battlefield V in library
2. Select "download 5 tags" in extension menu
3. Wait for failure to occur

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7892817/extensions.log)

### Screenshots

![image](https://user-images.githubusercontent.com/6006304/150029690-403f6319-c397-4200-a66d-a1441842b720.png)

**Comment by darklinkpower** [comment]
This issue should be fixed for v3.0

I'm no longer developing and maintaining the extension. The extension is now developed by Jeshibu over at https://github.com/Jeshibu/PlayniteExtensions, if there are new feature requests or bug reports please open an issue in that repository
