### ISSUE TITLE
[Extra Metadata Loader] Unrecoverable error when accessing details of a game

### ISSUE THREAD

**Issue by Spouwny** [darklinkpower/PlayniteExtensionsCollection#169]
### Extension name

Extra Metadata Loader

### Bug Description

If I use a theme other than the default one, one specific game cause an unrecoverable error when displaying its details.
The game is a f2p called StoryBook Brawl.
I tried to empty the Extra Metadata folder associated with the game to no avail.

### Extensions log

[playnite.extrametadata.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7904551/playnite.extrametadata.log)

**Comment by darklinkpower** [comment]
Hello, the file you uploaded is broken

![image](https://user-images.githubusercontent.com/1389286/150609049-4d0226c3-00e6-452b-ad80-bcf138867ee9.png)

Also, is there a error message saying that this is caused by the extension?

**Comment by darklinkpower** [comment]
Ok I figured out it was a `zip` file renamed to `log` extension. Can you tell me which which game this error happens?

**Comment by Spouwny** [comment]
Sorry about the renaming. Playnite just didn't put any extension when I saved them from the dialog box.

The game is the f2p "StoryBook Brawl" available on Steam

**Comment by darklinkpower** [comment]
Can you try with this version and see if it's fixed?

[ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_31.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7917412/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_31.zip)

**Comment by Spouwny** [comment]
It works fine whith this version !
