### ISSUE TITLE
[SplashScreen] Video not working

### ISSUE THREAD

**Issue by swanlon** [darklinkpower/PlayniteExtensionsCollection#170]
### Extension name

SplashScreen

### Bug Description

Can not reproduce video switching between desktop and fullscreen, although video plays on specific games
![download](https://user-images.githubusercontent.com/79228923/150460534-1a971cce-4e8a-4896-a960-29e571ff15e8.png)
Those options are enabled and I can see the videos on the setup window

The videos I'm trying to use for desktop and fullscreen:
For Desktop

https://user-images.githubusercontent.com/79228923/150460620-d05c4f8b-4b66-4cdf-b77d-763867315b72.mp4

For Fullscreen

https://user-images.githubusercontent.com/79228923/150460624-8b25f628-4841-4e62-8ca8-55ba5f282a1e.mp4

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7910293/extensions.log)

**Comment by darklinkpower** [comment]
Closing since the bug was a confusion about what the extension does as discussed on Discord
