### ISSUE TITLE
[Search Collection] Add custom searches via GUI

### ISSUE THREAD

**Issue by WildGenius** [darklinkpower/PlayniteExtensionsCollection#172]
### Extension name

Search Collection

### Feature Description

Currently, it's possible to manually edit SearchCollection.psm1 to write in additional search engines or amend existing ones ([see example of changing YouTube to add "gameplay" to the search](https://playnite.link/forum/thread-163-post-7348.html#pid7348)). Would be nice to have that option more easily accessible, e.g. see screenshot from Augmented Steam.

### Screenshots

![image](https://user-images.githubusercontent.com/8071762/150677125-1afb3433-22d9-4569-a74b-e22c1e39f0c4.png)

**Comment by darklinkpower** [comment]
Should be done after a complete rewrite of the extension in C# since it currently is made in Powershell

**Comment by darklinkpower** [comment]
I've rewritten the extension from scratch in C# and implemented this in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/8194cebba2295720d721da93896bd000660837a6
