### ISSUE TITLE
[Splash Screen] Windows key gets pressed when exiting game

### ISSUE THREAD

**Issue by twamer64** [darklinkpower/PlayniteExtensionsCollection#174]
### Extension name

Splash Screen

### Bug Description

When exiting a game while in fullscreen, after the splash screen goes away and I get to playnite, the windows key gets pressed twice after a couple of seconds. It doesn't do it for desktop mode, only on fullscreen mode. I tried disabling and reenabling it, as well as reinstalling it. I didn't have an older version installed before.

### Extensions log

23-01 22:31:47.102|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:31:47.102|INFO |SplashScreen#SplashScreen:Logo not found
23-01 22:31:47.107|INFO |SplashScreen#SplashScreen:Platform video found in C:\Users\Chrome\AppData\Roaming\Playnite\ExtraMetadata\platforms\3a889152-3bed-4052-a1b9-c1ab22bd39fc\VideoIntro.mp4
23-01 22:33:11.795|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:33:11.795|INFO |SplashScreen#SplashScreen:Logo not found
23-01 22:33:11.795|INFO |SplashScreen#SplashScreen:Platform video found in C:\Users\Chrome\AppData\Roaming\Playnite\ExtraMetadata\platforms\3a889152-3bed-4052-a1b9-c1ab22bd39fc\VideoIntro.mp4
23-01 22:33:46.033|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:33:46.033|INFO |SplashScreen#SplashScreen:Logo not found
23-01 22:33:46.033|INFO |SplashScreen#SplashScreen:Platform video found in C:\Users\Chrome\AppData\Roaming\Playnite\ExtraMetadata\platforms\3a889152-3bed-4052-a1b9-c1ab22bd39fc\VideoIntro.mp4
23-01 22:34:46.644|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:34:46.644|INFO |SplashScreen#SplashScreen:Logo not found
23-01 22:34:46.644|INFO |SplashScreen#SplashScreen:Platform video found in C:\Users\Chrome\AppData\Roaming\Playnite\ExtraMetadata\platforms\3a889152-3bed-4052-a1b9-c1ab22bd39fc\VideoIntro.mp4
23-01 22:36:28.001|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:36:28.001|INFO |SplashScreen#SplashScreen:Logo not found
23-01 22:36:28.001|INFO |SplashScreen#SplashScreen:Platform video found in C:\Users\Chrome\AppData\Roaming\Playnite\ExtraMetadata\platforms\3a889152-3bed-4052-a1b9-c1ab22bd39fc\VideoIntro.mp4
23-01 22:36:39.724|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:36:39.724|INFO |SplashScreen#SplashScreen:Logo not found
23-01 22:36:39.724|INFO |SplashScreen#SplashScreen:Platform video found in C:\Users\Chrome\AppData\Roaming\Playnite\ExtraMetadata\platforms\3a889152-3bed-4052-a1b9-c1ab22bd39fc\VideoIntro.mp4
23-01 22:39:22.183|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:39:22.183|INFO |SplashScreen#SplashScreen:Logo not found
23-01 22:39:22.186|INFO |SplashScreen#SplashScreen:Video not found
23-01 22:42:10.476|INFO |SplashScreen#SplashScreen:Removed "[Splash Screen] Skip splash image" feature from "Hollow Knight: Voidheart Edition"
23-01 22:44:01.422|INFO |SplashScreen#SplashScreen:Found game icon
23-01 22:44:01.422|INFO |SplashScreen#SplashScreen:Platform video found in C:\Users\Chrome\AppData\Roaming\Playnite\ExtraMetadata\platforms\3a889152-3bed-4052-a1b9-c1ab22bd39fc\VideoIntro.mp4
23-01 22:44:55.950|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:44:55.952|INFO |SplashScreen#SplashScreen:Found game icon
23-01 22:44:55.952|INFO |SplashScreen#SplashScreen:Platform video found in C:\Users\Chrome\AppData\Roaming\Playnite\ExtraMetadata\platforms\3a889152-3bed-4052-a1b9-c1ab22bd39fc\VideoIntro.mp4
23-01 22:45:49.719|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:45:49.719|INFO |SplashScreen#SplashScreen:Found game icon
23-01 22:45:49.719|INFO |SplashScreen#SplashScreen:Video not found
23-01 22:49:21.013|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:49:21.014|INFO |SplashScreen#SplashScreen:Found game icon
23-01 22:49:21.014|INFO |SplashScreen#SplashScreen:Video not found
23-01 22:51:47.940|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:51:47.940|INFO |SplashScreen#SplashScreen:Found game icon
23-01 22:51:47.940|INFO |SplashScreen#SplashScreen:Video not found
23-01 22:52:15.942|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:52:15.942|INFO |SplashScreen#SplashScreen:Found game icon
23-01 22:52:15.942|INFO |SplashScreen#SplashScreen:Video not found
23-01 22:52:45.249|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:52:45.249|INFO |SplashScreen#SplashScreen:Found game icon
23-01 22:52:45.249|INFO |SplashScreen#SplashScreen:Video not found
23-01 22:58:18.779|INFO |SplashScreen#SplashScreen:Found game background image
23-01 22:58:18.779|INFO |SplashScreen#SplashScreen:Found game icon
23-01 22:58:18.779|INFO |SplashScreen#SplashScreen:Video not found
23-01 23:04:43.639|INFO |SplashScreen#SplashScreen:Found game background image
23-01 23:04:43.639|INFO |SplashScreen#SplashScreen:Found game icon
23-01 23:04:43.639|INFO |SplashScreen#SplashScreen:Video not found

**Comment by darklinkpower** [comment]
That's intended. There's an issue when the extension is used in FS mode where after exiting a game, the controller input will stop working. The only fix is to take Playnite out and in of focus and the key presses are used as a temporary measure to fix this issue, although I'm afraid I don't know when/if a proper fix will be made since I have not had luck fixing it so hopefully someone else interested can take a look and try to fix it.

Leaving the issue open so people can see it if they don't know why this is done by the extension.

**Comment by Hassiopeia** [comment]
Hey I just saw this on Reddit: https://www.reddit.com/r/playnite/comments/tixd1d/playnite_script_to_focus_playnite_after_a_game/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

I wonder if something like that would remedy the issue?

**Comment by darklinkpower** [comment]
The extension will no longer press the key.
