### ISSUE TITLE
[Cooperative Modes Importer] Matches Xbox version of Minecraft instead of PC version

### ISSUE THREAD

**Issue by bverkron** [darklinkpower/PlayniteExtensionsCollection#178]
### Extension name

Cooperative Modes Importer

### Bug Description

Incorrectly pulls Xbox One co-op information for Minecraft instead of PC version. The Xbox One co-op information is different than PC so it gives false metadata, most notably about local co-op which is supported on the Xbox version but not PC version.

Xbox One entry: https://www.co-optimus.com/game/5111/xbox-one/minecraft.html
PC entry: https://www.co-optimus.com/game/3949/pc/minecraft.html

### To Reproduce

Enable these settings for the extension:
* Add Co-Optimus game link...
* Import Local Co-Op data

Run the plugin against Minecraft in the library. The Feature of "Local Co-Op: 4 players" will be added to the game's metadata. The Links -> Co-Optimus value will point to the Xbox One version

### Extensions log

Seems to be empty when running the narrowly scoped test described in the To Reproduce section

**Comment by darklinkpower** [comment]
I can't reproduce it, I just checked and it correctly added this one for me https://www.co-optimus.com/game/3949/pc/minecraft.html

![image](https://user-images.githubusercontent.com/1389286/152301023-929885e6-55c1-4a71-bb41-e4ae72612179.png)

Verify that you have the correct platform in the game info and platform specification

![image](https://user-images.githubusercontent.com/1389286/152301081-7dc75c21-f176-4dc7-92f4-12665c27df01.png)

![image](https://user-images.githubusercontent.com/1389286/152301139-7a555bfa-b817-455c-b108-f8b1f534a449.png)

**Comment by bverkron** [comment]
That seems to have solved it. The Platform was set with both Xbox One and PC. Not sure if it got set that way because it came from the Xbox library extension (annoying they call it that when it's purely on the PC) or during a metadata update via another extension.

Thanks for checking!
