### ISSUE TITLE
[Resolution Changer] Option to specify the (default) resolution after game is closed

### ISSUE THREAD

**Issue by Patbott** [darklinkpower/PlayniteExtensionsCollection#179]
### Extension name

Resolution Changer

### Feature Description

Currently, after closing a game, the resolution is set to the highest/first resolution that is detected. For me this causes issue as I have DSR resolutions enabled in the Nvidia Control panel (which are higher than my base resolution). So after closing a game, my resolution gets set to 5120x2880 instead of to 2560x1440. Hence, this feature request for an option to manually specify the default/base resolution the resolution will be changed to after closing a game. 

Alternatively, an option would be to check the current resolution before starting a game (so before the resolution is changed by the extension) and resetting it to that resolution when the game is stopped.

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/4c04bb6c8ba2163874c9d7df5deb451e10fcc1e6.

The previous screen resolution will be restored after exiting the game.
