### ISSUE TITLE
[Splash screen] Hide tray context menu when 

### ISSUE THREAD

**Issue by maicol07** [darklinkpower/PlayniteExtensionsCollection#182]
### Extension name

Splash screen

### Bug Description

Playnite tray context menu (where all games are listed) is open and visible above the splash screen when a game is started from there

### To Reproduce

1. Open Playnite
2. Close Playnite main window
3. Right click the Playnite icon in tray to open the context menu
4. Start a game listed in the tray context menu
5. See the tray context menu (where all games are listed) is open and visible above the splash screen

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7963344/extensions.log)

**Comment by darklinkpower** [comment]
Fixed
