### ISSUE TITLE
[Steam Tags Importer] Exception Importing Steam Game from Non-Steam Store

### ISSUE THREAD

**Issue by SquareCircleTriangle** [darklinkpower/PlayniteExtensionsCollection#187]
### Extension name

Steam Tags Importer

### Bug Description

When I try to import some games from non-Steam stores that are also available on Steam I get an error. This happens reliably for the same game. I've reproduced it with several games across several stores.

### To Reproduce

Find an itch.io game that also exists on Steam (I've consistently reproduced this on Fidel Dugneon Rescue), select it, and import tags from the Extensions menu. This results in a dialog indicating that an exception occurred (see the screenshot).

I've also reproduced this with Creatorcrate from the Humble Trove.

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8055730/extensions.log)

### Screenshots

![steam-tags-bug](https://user-images.githubusercontent.com/99601856/153757943-8ec3ac8f-1b6d-49b1-9419-f5c4d07461a3.png)

**Comment by darklinkpower** [comment]
This issue should be fixed for v3.0

I'm no longer developing and maintaining the extension. The extension is now developed by Jeshibu over at https://github.com/Jeshibu/PlayniteExtensions, if there are new feature requests or bug reports please open an issue in that repository
