### ISSUE TITLE
[InstallationStatusUpdater] See which games have been marked as un/installed by clicking on the notification.

### ISSUE THREAD

**Issue by woutercools** [darklinkpower/PlayniteExtensionsCollection#188]
### Extension name

Installation Status Updater

### Feature Description

See which games have been marked as un/installed by clicking on the notification.

### Screenshots

![image](https://user-images.githubusercontent.com/16439116/153762246-a9b4f295-c7b6-4da5-bed3-20a88cba0502.png)

**Comment by cresscendo** [comment]
Every time I restart Playnite, I get a notification "Marked 1 games as installed" but I can't seem to find what game is causing this issue...So I know it's sort of a bug for me, but this feature would be very useful in my troubleshooting.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/204282a12f41f5d39838fcb6972c8794d3ebd833
