### ISSUE TITLE
Game Pass Browser - Feature Request - Remove games from Playnite when they are removed from Playnite

### ISSUE THREAD

**Issue by SlipperyJim** [darklinkpower/PlayniteExtensionsCollection#19]
I imagine this would be a bit more complex to add, but the ability to remove games from Playnite when they are removed from Game Pass would be the final thing to effectively turn this into a full library plugin as well as a browser.

As discussed on Discord, probably only removing games that you have not played (and so are not going to be re-added by the Xbox plugin) would be the way to go. 

Maybe the option of tagging games that you have played with a 'Formerly on Game Pass' tag when they are removed (or similar) might be possible? Also a notification could I guess prompt you to uninstall a game with a link to Add\Remove Programs? Just a few thoughts anyway.

**Comment by darklinkpower** [comment]
Remove game from Playnite library feature done in https://github.com/darklinkpower/PlayniteScriptExtensions/commit/b96cc5872d3738aa605bc2978e271af98abb2900

**Comment by darklinkpower** [comment]
Closing as previous comment.
