### ISSUE TITLE
Compact Extension Suggestion

### ISSUE THREAD

**Issue by ArtexJay** [darklinkpower/PlayniteExtensionsCollection#2]
I feel like there's a few things missing from the Compact Extension.

The extension should be able to recognize if a game/program was compressed and offer the option to uncompress it.

Also the extension should show the size before and after (comparing the size) a game/program was compressed.

And also I think it would be great if a button could be added to the game's description or next to the "more button" which is a button to compress/uncompress the game that you're looking at.

At the moment I am using CompactGUI

**Comment by darklinkpower** [comment]
Definitely should be added, I'll look if I can add those features in the future.

**Comment by darklinkpower** [comment]
Closing as I'm not supporting the extension anymore. I suggest to use Compactor instead https://github.com/Freaky/Compactor
