### ISSUE TITLE
Game Pass Browser - View In Xbox App

### ISSUE THREAD

**Issue by sparkygman** [darklinkpower/PlayniteExtensionsCollection#20]
Requesting to add the option to open games in the Xbox app instead of/in addition to viewing in the Microsoft Store.

**Comment by darklinkpower** [comment]
I'd love to add this but unfortunately I don't think there's a way to tell the app to open app and go to a specific page. If you or someone finds a way please let me know. It would help if there is already a page or software that does this to examine how it does, but I could not find something that does it.

**Comment by ktdd** [comment]
To open Xbox and go to a specific game you use the following:

msxbox://game/?productId=ID_OF_GAME

For example, A Plague Tale: Innocence is:

msxbox://game/?productId=9ND0CG3LM22K

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/b302a7e87054907b6d5d065aa348954375e47a1c
