### ISSUE TITLE
[Game Enigne Checker] Does not return any data anymore

### ISSUE THREAD

**Issue by joyrider3774** [darklinkpower/PlayniteExtensionsCollection#205]
### Extension name

Game Engine Checker

### Bug Description

PCGamingwiki seems to have changed a bit making it fail to get data with the current system you are using. It will always return empty printouts even though the game on the website you are looking for does have such data.

I figured out an alternative way to get the data using this api call for tombraider 2013 (steamappid 203160) https://www.pcgamingwiki.com/w/api.php?action=cargoquery&format=json&tables=Infobox_game&fields=Engines%2C_pageName%3Dtitle&where=Steam_AppID%20HOLDS%20203160

you can do the exact same thing with GOGcom_ID in the where parameter for gog games.

https://www.pcgamingwiki.com/w/api.php?action=cargoquery&format=json&tables=Infobox_game&fields=Engines%2C_pageName%3Dtitle&where=GOGcom_ID%20HOLDS%202049187585

So the extension needs some adapting to make it work again with the current way pcgamingwiki works

You can also use this page to test out things
https://www.pcgamingwiki.com/wiki/Special:ApiSandbox#action=cargoquery&format=json&tables=Infobox_game&fields=Engines%2C_pageTitle%3Dtitle&where=Steam_AppID%20HOLDS%20203160

### To Reproduce

for example this game : https://www.pcgamingwiki.com/wiki/Tomb_Raider_(2013) has engine set

https://www.pcgamingwiki.com/w/api.php?action=askargs&conditions=Steam+AppID::203160&printouts=Uses_engine|Unity_engine_build&format=json does not produce data (printouts will be always empty) and is whats currently used in the plugin

this does produce data for the same steam appid (be aware though i don't know how to make it return "Foundation" as it shows on the page, but foundation is just another name for "Crystal Engine". I also know the engine database is "Engine" but i did not use it

https://www.pcgamingwiki.com/w/api.php?action=cargoquery&format=json&tables=Infobox_game&fields=Engines%2C_pageName%3Dtitle&where=Steam_AppID%20HOLDS%20203160

### Extensions log

nope

### Screenshots

![image](https://user-images.githubusercontent.com/10714776/158033092-964f9b40-b821-4b9b-aa87-429f2810e96e.png)

**Comment by darklinkpower** [comment]
Additional info provided on Discord regarding obtained data

![image](https://user-images.githubusercontent.com/1389286/162024242-4ca0b430-9607-4e9a-b107-2b3255a4f9b7.png)

**Comment by joyrider3774** [comment]
https://media.discordapp.net/attachments/699577276571975760/961345744500039741/unknown.png

Need to use cargo as i already suggested above

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/4b114572d66ba41ffa5b519129e0a888777ebef9

**Comment by joyrider3774** [comment]
@darklinkpower thanks did not test yet though but will probably work. also not sure it still grabs unit engine used i think it did in the past but did not verify that
