### ISSUE TITLE
[GamePassCatalogBrowser] Importing games into library doesn't have a completion status

### ISSUE THREAD

**Issue by Jhanlon95** [darklinkpower/PlayniteExtensionsCollection#206]
### Extension name

Game Pass Catalog Browser

### Bug Description

When automatically importing games from Gamepass there is no completion status set, this isn't consistent with how importing games from other sources into Playnite work. This is a minor inconvience for me, as I can fix them myself but hopefully wouldn't be too much work to add

I have added a screenshot to show what it looks like for me as I have an icon that shows when there is no completion status set, compared to "Not Played" and the other options etc

### To Reproduce

Import any game from Gamepass into Playnite and check the completion status

### Extensions log

n/a

### Screenshots

![image](https://user-images.githubusercontent.com/11045596/158084863-05391e64-0e9e-4d67-a437-30508c7c9db2.png)

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/00f160ddba9fd7917b059b366ef0c00ed557226e
