### ISSUE TITLE
[Special K Helper] Error message when trying to open Profiles Editor

### ISSUE THREAD

**Issue by Super1337Boy** [darklinkpower/PlayniteExtensionsCollection#208]
### Extension name

Special K Helper

### Bug Description

When I try to open the Special K Helper Profiles Editor from the Extensions sub menu, I get the attached error message and the Editor does not open.

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8243916/extensions.log)

### Screenshots

![Special_K_Helper_error_message](https://user-images.githubusercontent.com/6672819/158154498-01a1e21e-6bc5-40c0-ab71-b4d34c62db20.jpg)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/639589e4ec45ee2697c0a62dad45458e1b6b577c

**Comment by Super1337Boy** [comment]
It doesn't seem to be fixed for me with the latest update (1.5). I can probably fix it by just emptying my profiles folder and starting over (not a big problem for me), but here's a zip of the folder in case it's useful:
[Profiles.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8248832/Profiles.zip)

**Comment by Super1337Boy** [comment]
Seems like it was my profile for Cuphead that was the culprit. After deleting it and keeping the rest, the editor opens just fine. Hope that helps you narrow down the issue.

**Comment by darklinkpower** [comment]
Thanks, I'll take a look. Issue reopened

**Comment by darklinkpower** [comment]
I found the issue. The fix I made is only if the ini has duplicate keys but in this case the duplicate is a section. I'll see how to fix it 
![image](https://user-images.githubusercontent.com/1389286/158281282-ad954868-193f-4123-a482-d85f0a5edad1.png)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/4e952986ccb67eca7f6845947d7ce30ac159e00c
