### ISSUE TITLE
[Playstate] Extension doesn't detect and therefore suspend Lost Ark properly

### ISSUE THREAD

**Issue by Th3Legendary** [darklinkpower/PlayniteExtensionsCollection#211]
The game appears to have two executables which are Launch_Game.exe and LOSTARK.exe

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/a747f4a020d053fce440216a2a3ccb0f2ad994e7
