### ISSUE TITLE
[Playstate] AutoHotKey not opening when I launch a game

### ISSUE THREAD

**Issue by infideleraser** [darklinkpower/PlayniteExtensionsCollection#212]
Autohotkey doesnt open when i launch any game, so the playstate extension never works.

**Comment by darklinkpower** [comment]
The extension doesn't use AutoHotKey for its functionality. If the extension is not working please open a new issue providing the extension log. Also make sure to update the extension before since I just released a new update with extra logging to help identify issues.

**Comment by infideleraser** [comment]
where do i find the extension logs

**Comment by infideleraser** [comment]
also what are the default hotkeys. It used to be home but it doesn't work anymore
