### ISSUE TITLE
[Steam Launcher Utility] Add some launch options

### ISSUE THREAD

**Issue by ld892012** [darklinkpower/PlayniteExtensionsCollection#246]
### Extension name

Steam Launcher Utility

### Feature Description

Add ability to launch Steam BigPicture in windowed mode (with -windowed -480p (or -720p) flag) and reduce the launching time with -nointro flag

**Comment by darklinkpower** [comment]
I thought about it and it will be difficult to keep adding arguments that different people use. As an alternative and better solution, I have added support to add additional arguments from the extension settings, where you can add the arguments you suggested

![image](https://user-images.githubusercontent.com/1389286/180621192-5980df72-3277-42ca-9814-7ecda986678f.png)
