### ISSUE TITLE
[Extension name] Bug description

### ISSUE THREAD

**Issue by woutercools** [darklinkpower/PlayniteExtensionsCollection#247]
### Extension name

Installation Status Updater

### Bug Description

GTA V on Epic keeps getting flagged as uninstalled, while it isn't.

What can I do to prevent this?

### To Reproduce

Install GTA V on Epic.
Restart pc.

### Extensions log

I:\EPIC is my default install location for the Epic Launcher

GTA V is in stalled in I:\EPIC\GTAV

Extensions.log contains a path to P:\EPIC\GTAV (I use Playnite portable on drive P:\)

I think I used to install Epic games in the P:\EPIC\ folder, but I changed that.
How can I remove this from the extension's "memory"?

### Screenshots

![image](https://user-images.githubusercontent.com/16439116/167696323-03ac0405-0de2-47cf-b34b-819a11cc64d0.png)

**Comment by woutercools** [comment]
> 2. From what can be seen in the screenshot, the "Installation Status Updater" extension is not related to this. It's being marked as uninstalled by the Epic Library plugin so this would be the incorrect repository to report this issue

Indeed... Updating the Epic game library causes GTA V to be marked as uninstalled.

I'll make an issue in the appropriate Github.

**Comment by woutercools** [comment]
I got it solved with the help of Josef: https://github.com/JosefNemec/PlayniteExtensions/issues/182#issuecomment-1122795398

But there is still one more thing.

I still get this notification:

![image](https://user-images.githubusercontent.com/16439116/167921860-df3361be-bd16-47c8-b59a-df762b04bd3d.png)

I thought it was GTA V that always got marked as uninstalled, but since the issue is solved... Which game has been installed?
That's why I asked if it would be possible to be notified which game(s) has been (un)installed.

**Comment by darklinkpower** [comment]
You can check changes made by the extension in the extensions.log file. You can exclude games using the menu item in the extension main menu section.
