### ISSUE TITLE
[Extra Metadata Loader] Downloading videos from Youtube failing

### ISSUE THREAD

**Issue by Arkkitehti** [darklinkpower/PlayniteExtensionsCollection#248]
### Extension name

Extra Metadata Loader

### Bug Description

Using the "Download video from Youtube" or "Download videos from Youtube for all selected games automatically" options end up with an error: "Failed to download video from YouTube. Please try with a different video." (screenshot included). 
After starting the download, yt-dlp window pops up and closes after a few seconds (nothing shows up in the yt-dlp window)
This happens with all videos.

### To Reproduce

The same thing happens when trying to download any video.

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8668885/extensions.log)

### Screenshots

![image](https://user-images.githubusercontent.com/105354706/167824886-41d26e55-c501-489d-8c2c-529366af9c12.png)

**Comment by darklinkpower** [comment]
Please install this debug build, try to download a video again and upload your extension.log file
[ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_50.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8674458/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_50.zip)

**Comment by Arkkitehti** [comment]
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8675361/extensions.log)

Here it is.
"[download] C:\Users\simok\AppData\Local\Temp\VideoTemp.mp4 has already been downloaded" is what I found interesting myself, could that have something to do with the problem? I went to take a look at the location and there is indeed a VideoTemp.mp4 file there.

**Comment by darklinkpower** [comment]
Your log says that it has 0 bytes, weird.

```
[download] C:\Users\simok\AppData\Local\Temp\VideoTemp.mp4 has already been downloaded

[download] 100% of 0.00B
````

Can you try deleting that file and trying to download the video again and upload the log again afterwards?

**Comment by darklinkpower** [comment]
I was able to reproduce it, the issue was that. Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/4ee4c79af8e4714687499fc39be441b4d5a02999
