### ISSUE TITLE
[Splash Screen] a fade in animation of the logo on top of the wallpaper just like ps5 splash screen

### ISSUE THREAD

**Issue by aminenr-hub** [darklinkpower/PlayniteExtensionsCollection#253]
### Extension name

Splash Screen

### Feature Description

can we get a fade in animation of the logo just like the ps5 splash screen 

you can see an example for the feature on this clip : https://youtube.com/clip/Ugkx3wzsuah8zCNhr73ykjJ0ZEQiUVwIIjUy
 
Thanks for your work

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/9f9df3fa24adeadd9fbbbc92c368febd70d264a5
