### ISSUE TITLE
[ InstallationStatusUpdater ] Invalid character in path error during status check

### ISSUE THREAD

**Issue by sprudel79** [darklinkpower/PlayniteExtensionsCollection#260]
### Extension name

Installation Status Updater

### Bug Description

Hi everyone, 
I am trying to use the extension "Installation status updater".  When trying to use it manually via menu option "check installation status of all games" I get an error message saying "invalid character in path". 
What went wrong here? It would be great if the extension could be updated to show more details in the error so I can see which game might cause the issue. 
Thank you.

In order to provide a small log file I have deleted the existing one, restarted Playnite and directly executed the action.
As it seems there's an exception thrown in German language (since my system has this culture setting).

### Extensions log

03-06 22:32:30.218|INFO |ProgramEntry:App arguments: ''
03-06 22:32:30.259|INFO |PlayniteApplication:Application already running, shutting down.
03-06 22:32:30.376|INFO |PlayniteApplication:Executing command "Focus" from pipe with arguments ""
03-06 22:32:37.837|ERROR|MainMenu:Main menu extension action failed.
System.ArgumentException: Illegales Zeichen im Pfad.
   bei System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   bei System.IO.Path.Combine(String path1, String path2)
   bei InstallationStatusUpdater.InstallationStatusUpdater.DetectIsFileActionInstalled(GameAction gameAction, String installDirectory) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\InstallationStatusUpdater\InstallationStatusUpdater.cs:Zeile 359.
   bei InstallationStatusUpdater.InstallationStatusUpdater.DetectIsAnyActionInstalled(Game game, String installDirectory) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\InstallationStatusUpdater\InstallationStatusUpdater.cs:Zeile 397.
   bei InstallationStatusUpdater.InstallationStatusUpdater.IsGameInstalled(Game game) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\InstallationStatusUpdater\InstallationStatusUpdater.cs:Zeile 485.
   bei InstallationStatusUpdater.InstallationStatusUpdater.DetectInstallationStatus(Boolean showResultsDialog) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\InstallationStatusUpdater\InstallationStatusUpdater.cs:Zeile 414.
   bei InstallationStatusUpdater.InstallationStatusUpdater.<GetMainMenuItems>b__33_0(MainMenuItemActionArgs a) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\InstallationStatusUpdater\InstallationStatusUpdater.cs:Zeile 233.
   bei Playnite.DesktopApp.Controls.MainMenu.<>c__DisplayClass18_2.<AddExtensionItems>b__1(Object _, RoutedEventArgs __) in C:\projects\playnite\source\Playnite.DesktopApp\Controls\Menus\MainMenu.cs:Zeile 387.

**Comment by MichaelMKenny** [comment]
I'm having this exact issue too. My language is English (United States).

**Comment by darklinkpower** [comment]
> Narrowed it down to this game: "Star Wars: Battlefront II". This is its install directory: "Z:\Origin\STAR WARS Battlefront II". I should note this has a custom play action, due to me owning it on Epic.

Can you show me a screenshot of your game Play Action tab please to try to reproduce it?

Also, can you install this debug build, try again and send me the extensions.log file please?

[Installation_Status_Updater_2_30.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8882213/Installation_Status_Updater_2_30.zip)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/bf1fc66c7c1c8c6ed7bb289b3c9e5021a03dead3
