### ISSUE TITLE
[Splashscreen] Use specific image for specific game (Different from the game background image)? - Enhancement

### ISSUE THREAD

**Issue by WilliamLeGod** [darklinkpower/PlayniteExtensionsCollection#261]
Is it possible to add Spashscreen a feature as: use specific image for specific game 

Thanks!

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/c1901b5f0bc23c0cd946e0cadfd14847410500a5 and https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/63703ba6fed941813f1eeec0841ece10ba9e0fef
