### ISSUE TITLE
[Installation Status Updater] Why is this game marked as uninstalled?

### ISSUE THREAD

**Issue by chocolatechipcats** [darklinkpower/PlayniteExtensionsCollection#262]
### Extension name

Installation Status Updater

### Bug Description

Playnite 9.18.

I have the GOG version of Dragon Age Origins. "Launch games via GOG Galaxy Client Enabled" is checked, but here I disabled the library play action in lieu of custom actions pointing directly at the game exe.

However, unless I have the library play enabled (which produces an extra prompt message upon launch), Installation Status Updater keeps marking the game as uninstalled. Did I make a mistake somewhere with the paths?

### Extensions log

11-06 12:40:59.457|DEBUG|ItchioLibrary#ItchioLibrarySettingsViewModel:Updating itch settings from version 0.
11-06 12:41:20.755|INFO |GameActivity#PluginDatabaseObject`4:LoadDatabase with 415 items - 00:18.63
11-06 12:41:20.755|INFO |CheckDlc#PluginDatabaseObject`4:LoadDatabase with 408 items - 00:20.02
11-06 12:41:20.774|INFO |SuccessStory#PluginDatabaseObject`4:LoadDatabase with 407 items - 00:15.30
11-06 12:41:22.388|INFO |InstallationStatusUpdater#InstallationStatusUpdater:Game: Dragon Age: Origins marked as uninstalled
11-06 12:43:30.786|INFO |InstallationStatusUpdater#InstallationStatusUpdater:Game: Dragon Age: Origins marked as uninstalled

### Screenshots

![2022-06-11 12_52_59-Edit Game Details](https://user-images.githubusercontent.com/47759676/173195224-3f837def-742d-4d40-85a7-bd24fec7a6a4.png)
![2022-06-11 12_53_03-Edit Game Details](https://user-images.githubusercontent.com/47759676/173195225-6de53035-2db4-484c-9c15-da3829f77a43.png)

**Comment by chocolatechipcats** [comment]
Addon settings

![2022-06-11 13_11_52-Add-ons…](https://user-images.githubusercontent.com/47759676/173195873-5ecd3f70-193e-4ee0-9048-4b6e9f885eaa.png)

**Comment by darklinkpower** [comment]
Does the executable exists in `C:\Games\Dragon Age Origins\DAOrigins.exe`?

You can also verify this by running this in a powershell window

```powershell
Test-Path "C:\Games\Dragon Age Origins\DAOrigins.exe" -PathType Leaf
```

**Comment by chocolatechipcats** [comment]
The path is `C:\Games\Dragon Age Origins\bin_ship\DAOrigins.exe`

**Comment by chocolatechipcats** [comment]
Should the bin_ship have been in the path rather than the working directory?
