### ISSUE TITLE
[Splashscreen] Options to adjust splashscreen settings per game

### ISSUE THREAD

**Issue by BrunoYagami** [darklinkpower/PlayniteExtensionsCollection#265]
### Extension name

Spashcreen

### Feature Description

suggestion: be able to choose the image that will appear on the splashscreen of each game individually, not depending on the background image.
for example: in the background image of the game it is an image but in the splashscreen it is another one I selected.
or being able to choose how the icon will react for each game individually, if I want the icon to appear on the splashscreen of a game on the left side, and in another game on the right side.
currently there is only one global option, all icons on the right or all on the left, for example.
thankful.
great job, keep it up

### Screenshots

background image example:
![glffffo](https://user-images.githubusercontent.com/55263547/173459263-ef157f12-e19b-437d-9539-372d9b227240.png)

spashscreen image exemple:
![glo](https://user-images.githubusercontent.com/55263547/173459101-aaf70052-ae7e-4be8-94f1-d20af2c4f80d.png)

**Comment by darklinkpower** [comment]
Splashscreen specific image has already been suggested and can be tracked in #261

**Comment by Obspogon** [comment]
adding to this: option to disable splash screen per game

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/c1901b5f0bc23c0cd946e0cadfd14847410500a5 and https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/63703ba6fed941813f1eeec0841ece10ba9e0fef
