### ISSUE TITLE
Extra metadata images like slide Feature description

### ISSUE THREAD

**Issue by BrunoYagami** [darklinkpower/PlayniteExtensionsCollection#266]
### Extension name

Extra metadata

### Feature Description

suggestion: give the option to add images of the game instead of videos, where these images will pass in the style of a slide.
thankful.
great job.
keep it up.

**Comment by darklinkpower** [comment]
I'm sorry but this would require creating a new extension/control and is something that I don't have the time to make as it would be a lot of work. I'm also refraining from creating new extensions as I'm already developing and maintaining a lot of extensions and themes and I can't add more to the list,  I hope you understand.
