### ISSUE TITLE
[NVIDIA GE GameStream Export] Can't find object at specified path

### ISSUE THREAD

**Issue by WiseEXE** [darklinkpower/PlayniteExtensionsCollection#267]
### Extension name

NVIDIA GE GameStream Export

### Bug Description

When trying to export any game including games already included within my GameStream's game list. I get the error.

"Failed to execute menu action.
An object at the specified path C:\Users\WisePC~1 does not exist."

I would like to mention my user profile does not include the additional "~1" at the end of it's name field.

### To Reproduce

Trying to export any game using the extension.

### Extensions log

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8895710/extensions.log)

### Screenshots

![image_2022-06-13_210003149](https://user-images.githubusercontent.com/105170549/173477415-d2539239-9014-489a-9e99-14509f19ab03.png)

**Comment by WiseEXE** [comment]
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/8896092/playnite.log)

**Comment by WiseEXE** [comment]
Was able to patch the bug myself, will send a push request if needed.

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/06913e597e6ebac42b839b5d85f6fe82ce01b23a
