### ISSUE TITLE
[InstallationStatusUpdater] Option to Exclude Specific Games

### ISSUE THREAD

**Issue by burnpsy** [darklinkpower/PlayniteExtensionsCollection#271]
### Extension name

Installation Status Updater

### Feature Description

I would like to exclude certain games from this extension. Perhaps via a tag. My circumstances for why are below, but that's basically it.

--

In brief, any games I have on Origin via Epic don't launch properly at present unless I disable the play action and add a manual one of the type Link, which tells Origin to authenticate the game via Epic.

This works fine since I know to do this. However, that causes issues with this add-on. The current available settings either let me set all games with a play action of the type Link as Installed, or all as Uninstalled. So if I, for example, have Star Wars: Squadrons installed through Epic and Star Wars Jedi: Fallen Order owned through Epic but not installed, this add-on will either set both as Installed or both as Uninstalled. Both possibilities are wrong.

So I would like to tell your extension to just leave these particular games alone.

**Comment by darklinkpower** [comment]
This is already possible from here

![image](https://user-images.githubusercontent.com/1389286/176307648-d565d888-3ce2-4549-af57-a2b5ec2ee9ca.png)
