### ISSUE TITLE
[Playstate] Disable notification window for pausing game and resuming game

### ISSUE THREAD

**Issue by WilliamLeGod** [darklinkpower/PlayniteExtensionsCollection#275]
### Extension name

Playstate

### Feature Description

Is it possble to add in extension “Playstate” a feature to: disable notification window for pausing game and resuming game? Its like i know the game is paused by looking at it as it is freeze and dont want to see the pop up window says its paused or resumed.

Thanks!

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/24e5a2d05261349a49d0db9ceff94209af65ad71
