### ISSUE TITLE
[NVIDIAGeForceNowLibrary] Name Matching for Origin and Epic games is broken when using the "display games as library feature"

### ISSUE THREAD

**Issue by joyrider3774** [darklinkpower/PlayniteExtensionsCollection#303]
### Extension name

NVIDIAGeForceNowLibrary

### Bug Description

[NVIDIAGeForceNowLibrary] Name Matching for Origin and Epic games is broken when using the "display games as library feature"

a sanitized name (from the playnite database) is compared against an unsantized name from Gefore now in this case (see screenshot)

### To Reproduce

Use feature to display the games as a library instead of modifying existing games and try adding a game from origin or epic games it should mostly fail even when the game name is 100% the same as in the database viewer

you can use the demo from this game for example to test https://store.epicgames.com/en-US/p/immortals-fenyx-rising

### Logs

not applicable

### Screenshots

![image](https://user-images.githubusercontent.com/10714776/186287817-ccdf6d45-6a2e-40e6-be01-88a5b69e44e0.png)

**Comment by joyrider3774** [comment]
you just need to call SanitizeGameName on ItemVariant.title in this case in this location

**Comment by joyrider3774** [comment]
hmm the bug might be elsewhere maybe the changes done by SatinizeSupportedListTitles are not applied or the function is not called somewhere where it should

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/7bec0d4dd13e3aeb43f388577538a259c42e5ce2
