### ISSUE TITLE
[Installation Status Updater] Make use of the {EmulatorDir} variable

### ISSUE THREAD

**Issue by Ven0m0** [darklinkpower/PlayniteExtensionsCollection#318]
### Extension name

Installation Status Updater

### Feature Description

The updater marks emulated games as uninstalled when using the {EmulatorDir} variable for the Installation folder instead of a static folder. For example if i had games in "C:\Users\Username\Downloads\Games" and i set that as the Installation folder it works, but if i had the {EmulatorDir} variable as "C:\Users\Username\Downloads\Games" it would not accept {EmulatorDir} as an install folder. This forces you to have static values and if you move the emulator you would have to change the installation folder for every single game.

**Comment by darklinkpower** [comment]
Fixed. The used path will be the emulator used in the first found Play Action in the game

**Comment by NoShotz** [comment]
Just a heads up, this issue appears to be back, all my emulated games that use {EmulatorDir} in the installation folder path get marked as uninstalled when the status updater is ran, manually setting a game to be installed again and making the installation folder path a static path, and running the status updater results in the game not being marked as uninstalled.
