### ISSUE TITLE
[PlayState] New included hotkey

### ISSUE THREAD

**Issue by PaulReg** [darklinkpower/PlayniteExtensionsCollection#321]
### Extension name

PlayState

### Feature Description

Just a reminder to add an extra default shortcut for 'Win + Alt + PrtScn'.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/5b70ddd4c8f0ad08d896ad587a69bfba707564aa
