### ISSUE TITLE
[LibraryExporter] Add support for Roms

### ISSUE THREAD

**Issue by rigerc** [darklinkpower/PlayniteExtensionsCollection#324]
### Extension name

LibraryExporter

### Feature Description

I would like to be able to export the path to the ROM/binary file as well. This way I could select games from my rom collection I don't want and delete or move them from my hard drive! The use case for this is I want to curate my collection before I move the roms to a portable device

Great work btw!

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/c09d4bfdac7a348eda5a878e7b23cb170cc06c05
