### ISSUE TITLE
[Installation Status Updater] Check InstallDir does not support game variables

### ISSUE THREAD

**Issue by flyklmwl** [darklinkpower/PlayniteExtensionsCollection#328]
### Extension name

Installation Status Updater

### Bug Description

hello， i found a questions, if playnite InstallDir include game variables(like {PlayniteDir} ) , this extension does not support check dir where InstallDir has exists, can you fix it ,thanks

### Logs

no logs

### Screenshots

![1](https://user-images.githubusercontent.com/16217588/197325389-4f7eaed9-77ca-4f5a-af50-f2f29d769e82.jpg)

**Comment by darklinkpower** [comment]
Fixed
