### ISSUE TITLE
"failed to import games, an item with the same key has already been added"

### ISSUE THREAD

**Issue by Kdog88** [darklinkpower/PlayniteExtensionsCollection#336]
### Extension name

importer for anilist

### Bug Description

says fails to import titles as an item with the same key as already been added.  also. the file names are just the first items' names in the directories, but both zip files have everything in the respective directories

### To Reproduce

update the anilist library.....idk if its just my library or all users' libraries

### Logs

[config.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/9990524/config.zip)
[Localization.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/9990526/Localization.zip)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/9990556/playnite.log)

### Screenshots

![IMG_0284](https://user-images.githubusercontent.com/49170700/201350054-94d1031b-64d2-4e6e-a3fc-382896c73b16.JPG)

**Comment by darklinkpower** [comment]
Can you upload your extensions log please? The information I need to investigate it is in that file

**Comment by Kdog88** [comment]
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/9993222/extensions.log)

**Comment by Kdog88** [comment]
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/10012778/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/10012779/playnite.log)
 

updated logs as requested by darklinkpower

**Comment by darklinkpower** [comment]
Fixed
