### ISSUE TITLE
[Extra Metadata Loader] Relative Directories

### ISSUE THREAD

**Issue by Kyzoku** [darklinkpower/PlayniteExtensionsCollection#344]
### Extension name

Extra Metadata Loader

### Feature Description

Perhaps it is already an feature and I'm missing it, but is it possible to use relative directories for the FFMPEG, FFPROBE, and YT-DLP executables?

I use Playnite as a portable application, but if I transfer my portable drive to a different computer it is very possible the drive letter will be different.  I've currently placed the executables in "F:\Playnite\Extensions\ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429\Extras" and the extension is configured to that directory.  However plugging the device in my son's computer changes the drive letter to E:\ and the extension ceases to work.

Is there a variable, or can I even use a variable, to point to the Playnite folder.  I know that {PlayniteDir} is an existing variable, but you can't directly add that to the text fields.

Thanks in advance for your response.

**Comment by darklinkpower** [comment]
Currently not possible, I'd need to add support for it. For the moment to fix it by assigning the same drive letter to the USB in both PCs https://www.groovypost.com/howto/assign-permanent-letter-removable-usb-drive-windows/
