### ISSUE TITLE
[Game Pass Catalog Browser] Gamepass games not tagged at all

### ISSUE THREAD

**Issue by jedcooper** [darklinkpower/PlayniteExtensionsCollection#351]
### Extension name

Game Pass Catalog Browser

### Bug Description

The browser does NOT tag the games being in Gamepass or games that are not anymore does NOT tag in Gamepass (formerly on). I'm using German Playnite if that might be the issue? Can't think of another.

### Logs

[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/10247575/playnite.log)
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/10247578/extensions.log)

### Screenshots

![Playnite_Breathedge_formerly_on_02](https://user-images.githubusercontent.com/8408474/208150072-3f79874e-b0f5-4905-a0d2-e6d8219a72f5.PNG)
![Playnite_GPAddonSettings](https://user-images.githubusercontent.com/8408474/208150777-92d0a46d-37ab-4177-aea4-0cf4da9c383b.PNG)

**Comment by SpyderZT** [comment]
I was actually just coming here to note this issue as well.

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/pull/545
