### ISSUE TITLE
[Details to Grid View Converter] Details to Grid View Converter	doesn't work

### ISSUE THREAD

**Issue by ThinkSalat** [darklinkpower/PlayniteExtensionsCollection#364]
### Extension name

Details to Grid View Converter	

### Bug Description

Doesn't matter which theme I use (dh dawn for example) it just stays in list mode.

### Logs

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/10610081/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/10610082/playnite.log)

### Screenshots

![image](https://user-images.githubusercontent.com/31082405/216798030-7874558d-a969-463f-84ef-0490b4952c77.png)

**Comment by darklinkpower** [comment]
Have you enabled the theme in the extension settings?
![image](https://user-images.githubusercontent.com/1389286/216798742-65197c1b-9efa-480d-b3c6-4038128471fe.png)

Your screenshot is also showing **Details View** but the conversion is actually done in **Grid View**
![image](https://user-images.githubusercontent.com/1389286/216798725-69a0a00f-ccf5-453c-b7b0-35c997486593.png)

**Comment by ThinkSalat** [comment]
I do have the theme enabled. So in the grid view it just uses the details pane from the details view? I think I understand then.

**Comment by darklinkpower** [comment]
That's correct. From https://playnite.link/addons.html#ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3

> Converts the layout in Details View to Grid View of supported Desktop Mode themes. Conversion of supported themes must be enabled individually in the extension settings

If everything is clear now and working correctly, please let me know to close the issue.

**Comment by ThinkSalat** [comment]
Oh ok. I would word that differently because I was under the impression that the layout of the details view was changed. I would say "Allows to view the details panel from the grid view, converting the grid view information panel to the same view you would see in the "Details View"
