### ISSUE TITLE
[LibraryExporter] Ability to choose the separator for the CSV file

### ISSUE THREAD

**Issue by jullebarge** [darklinkpower/PlayniteExtensionsCollection#366]
### Extension name

LibraryExporter

### Feature Description

It would be nice to be able to choose the csv separator for the result file, as I have a lot of game with the separator in the name (coma) and it's difficult to edit the file with Excel because of that.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/a3540ec86184e5090db485166863f0072cc34caf
