### ISSUE TITLE
Text invisible in "Installation Status Updater" in Playnite 9

### ISSUE THREAD

**Issue by ferrazpedro** [darklinkpower/PlayniteExtensionsCollection#37]
Hey! I'm having this problem with "Installation Status Updater" in P9. The options screen isn't showing any text at all:

![image](https://user-images.githubusercontent.com/37643357/132133826-340b7807-c67a-4dc8-9cc2-026d5d16ef25.png)

Don't know if matter, but my P9 is in brazilian portuguese.

**Comment by darklinkpower** [comment]
Thanks for the heads up, fixed and you should be notified that there's an update.
