### ISSUE TITLE
[Purchase Date Importer] does not work for EA app/Origin

### ISSUE THREAD

**Issue by sengtsan** [darklinkpower/PlayniteExtensionsCollection#375]
### Extension name

Purchase Date Importer

### Bug Description

After successfully logging in to EA via the pop window for the extension in playnite and closing the broswer window, I try to import the purchase dates but receive an unrecoverable error message.

### Logs

[originpurchaseerror.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/10870173/originpurchaseerror.zip)

### Screenshots

![image](https://user-images.githubusercontent.com/63714826/222399982-c0dc0b60-e8cc-44a5-acc2-ff6d04f0863e.png)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/35861c470127f93211fb1ebe429416dabb44b036

**Comment by sengtsan** [comment]
Hi,
I tried to use the plugin, following the steps outlined as before. I received an error again when attempting to import EA data, this time it looked like this: 

![image](https://user-images.githubusercontent.com/63714826/222695014-486d788b-136c-4e09-b375-5839ddecf1b7.png)

**Comment by darklinkpower** [comment]
You need to update to the new version with the fix that I uploaded, you can do it from Main menu -> Addons -> Updates

**Comment by sengtsan** [comment]
can confirm it worked. thank you
