### ISSUE TITLE
Extra Metadata Loader use existing icons

### ISSUE THREAD

**Issue by TheJAXi** [darklinkpower/PlayniteExtensionsCollection#376]
Is there a way to use existing icons as logos? I remember there being an option like that before? I have every icon already downloaded for my games and they're basically manually set from different metadata sources. Took me 100 hours to do so. The SteamGridDB doesn't have most emulator game "logos" so I had to basically do it by hand. Now, if I want to use the icons=logos with your plugin. I'd need to manually go through every game copy the icon from library folder to the extrametadata folder and rename every "340921140904" random icon name to logo.png. Got 20 000 or so games in my library and it would take years to go through that.

= Can you implement (if not already existing) the feature to use existing icons as logos???

**Comment by darklinkpower** [comment]
There isn't an option for it, I don't know, I don't like the idea of adding support for an unintended asset. You can move your icons to the correct logo paths with this script, use it from Main menu > Extensions > Interactive Powershell

```powershell
function Set-GameDirectory
{
    param (
        $game
    )

    $directory = $PlayniteApi.Paths.ConfigurationPath + "\ExtraMetadata\" + "games\" + $game.Id
    if(!(Test-Path $directory))
    {
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
    }

    return $directory
}

foreach ($game in $PlayniteApi.Database.Games) {
    if ($null -eq $game.Icon)
    {
        continue
    }

    $iconPath = $PlayniteApi.Database.GetFullFilePath($game.Icon)
    $iconExtension = [System.IO.Path]::GetExtension($iconPath)
    if ($iconExtension -eq ".png" -and Test-Path $iconPath)
    {
        $extraMetadataDirectory = Set-GameDirectory $game
        $logoPath = Join-Path $extraMetadataDirectory -ChildPath "Logo.png"
        if (Test-Path $logoPath -eq $false)
        {
            Copy-Item $iconPath -Destination $logoPath -Force
        }
    }
}
```

**Comment by TheJAXi** [comment]
Move? Shouldn't I copy them over? Wouldn't moving them to the logo section ruin "icons" for all other themes&/extensions? That's why I said using the existing icons as logos would be optimal.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by darklinkpower** [comment]
I used the wrong word. The script will copy the icons to the logo path, not move.

**Comment by TheJAXi** [comment]
At line:9 char:39
+     if ($iconExtension -eq ".png" -and Test-Path $iconPath)
+                                       ~
You must provide a value expression following the '-and' operator.
At line:9 char:40
+     if ($iconExtension -eq ".png" -and Test-Path $iconPath)
+                                        ~~~~~~~~~
Unexpected token 'Test-Path' in expression or statement.
At line:9 char:40
+     if ($iconExtension -eq ".png" -and Test-Path $iconPath)
+                                        ~~~~~~~~~
Missing closing ')' after expression in 'if' statement.
At line:1 char:48
+ foreach ($game in $PlayniteApi.Database.Games) {
+                                                ~
Missing closing '}' in statement block or type definition.
At line:9 char:59
+     if ($iconExtension -eq ".png" -and Test-Path $iconPath)
+                                                           ~
Unexpected token ')' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ExpectedValueExpression
    
    Not to reopen this issue for nothing, but getting this error while running the script.

**Comment by minhnhattonthat** [comment]
Fixed the code below, it doesn't throw error, but also doesn't do anything, so still need @darklinkpower to revise this.

```
function Set-GameDirectory
{
    param (
        $game
    )

    $directory = $PlayniteApi.Paths.ConfigurationPath + "\ExtraMetadata\" + "games\" + $game.Id
    if(!(Test-Path $directory))
    {
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
    }

    return $directory
}

foreach ($game in $PlayniteApi.Database.Games)
{
    if ($null -eq $game.Icon)
    {
        continue
    }

    $iconPath = $PlayniteApi.Database.GetFullFilePath($game.Icon)
    $iconExtension = [System.IO.Path]::GetExtension($iconPath)
    if ($iconExtension -eq ".png" -and (Test-Path $iconPath))
    {
        $extraMetadataDirectory = Set-GameDirectory $game
        $logoPath = Join-Path $extraMetadataDirectory -ChildPath "Logo.png"
        if (Test-Path $logoPath -eq $false)
        {
            Copy-Item $iconPath -Destination $logoPath -Force
        }
    }
}
```
