### ISSUE TITLE
[Nvidia GFN Enabler] EA Games on EA app are not imported

### ISSUE THREAD

**Issue by Indusfr** [darklinkpower/PlayniteExtensionsCollection#383]
### Extension name

Nvidia GeForce Now Enabler

### Bug Description

Since Electronic Arts moved from Origin to EA app, all Electronic Arts games available in the new launcher are no longer detected and therefore not imported.

### Logs

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/11009562/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/11009563/playnite.log)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/091ebdeb5bd7847c61cfb42615b6a8c7dfb1e975
