### ISSUE TITLE
[Installation Status Updater] Marks Every Game As Uninstalled

### ISSUE THREAD

**Issue by MustaDevelop** [darklinkpower/PlayniteExtensionsCollection#385]
### Extension name

Installation Status Updater

### Bug Description

Idk if I'm doing something wrong because I didn't see any other issue about this.
Whenever the Extension checks for installation status, for some reason it marks everything (Manually added games excluded) as uninstalled.
I looked through it again and again but I found nothing.

### Logs

[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/11017161/playnite.log)

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/11017163/extensions.log)

**Comment by darklinkpower** [comment]
Can you share your extension settings please?

**Comment by Musta-VG** [comment]
> Can you share your extension settings please?

![Playnite DesktopApp_JlH7TxsGSP](https://user-images.githubusercontent.com/77793061/226614845-c14f683f-8c16-45ac-a342-545e9cf6cb37.png)

**Comment by darklinkpower** [comment]
Can you enable the "Skip games that include the play action of their library" option and try again? If that doesn't help, can you show me the Play Actions tab in the Edit window of a game having this issue?

**Comment by Musta-VG** [comment]
> Can you enable the "Skip games that include the play action of their library" option and try again? If that doesn't help, can you show me the Play Actions tab in the Edit window of a game having this issue?

This will probably not work, because it happens on games that are from a library like Steam and Epic Games. So they normally don't have a play action.
Maybe it's just a matter of compatibility and nothing else.
