### ISSUE TITLE
[SteamWishlistDiscountNotifier] Unhandled exception happens from time to time when computer wakes up.

### ISSUE THREAD

**Issue by tekert** [darklinkpower/PlayniteExtensionsCollection#386]
### Extension name

Steam Wishlist Discount Notifier

### Bug Description

About 75% of the time the computer wakes up from suspended state, playnite crahes, looking at the logs (at least the last 3 times this happened) it always crashes after the following two lines:

```
DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifier:Started checking for wishlist. Status: NoConnection, steamId: 
DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifier:Finished checking for wishlist
```
20ms later an exception is logged
`ERROR|PlayniteApplication:Unhandled exception occured.`

This pattern repeats on the last 3 crashes, i don't know if this extension is the causing the crash or an intermediate code after the extension is loaded.

The exception type is always a System.ObjectDisposedException "can't access a discarded object":

```
System.ObjectDisposedException: No se puede obtener acceso al objeto desechado.
Object Name: 'IBrowser'.
   en CefSharp.DevTools.DevToolsClient.ExecuteDevToolsMethodAsync[T](String method, IDictionary`2 parameters)
   en CefSharp.DevTools.Emulation.EmulationClient.SetUserAgentOverrideAsync(String userAgent, String acceptLanguage, String platform, UserAgentMetadata userAgentMetadata)
   en Playnite.WebView.OffscreenWebView.<Browser_BrowserInitialized>d__20.MoveNext() en C:\projects\playnite\source\Playnite\WebView\OffscreenWebView.cs:línea 86
```

### Logs

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/11070024/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/11070025/playnite.log)

**Comment by darklinkpower** [comment]
The issue seems to happen when the wishlist is checked in the background while there is no internet connection. Those times when it happens on wake up is because the check starts before the PC has connected

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/5ece48875c3915936a19db04fd3c48c5a26a5505
