### ISSUE TITLE
[Extra Metadata Loader] Playnite Crash

### ISSUE THREAD

**Issue by Kyzoku** [darklinkpower/PlayniteExtensionsCollection#392]
### Extension name

Extra Metadata Loader

### Bug Description

Playnite crashes when viewing certain games.

I have a few games that do not have a video trailer available.  I disabled the "Enable video player" setting and went to the Extra Metadata directory for the game and there is no video file present.  This has happened on 3 games I have added today. 

### To Reproduce

Not entirely sure other than adding a game that has no video trailers available.

### Logs

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/11147062/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/11147063/playnite.log)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/eba594e1bd302e572f07de1b43d94fa4465244ac
