### ISSUE TITLE
[Purchase Date Importer] Epic sync stuck and crash

### ISSUE THREAD

**Issue by Werve** [darklinkpower/PlayniteExtensionsCollection#403]
### Extension name

Purchase Date Importer

### Bug Description

The plugin synchronized correctly with other services (Steam, Origin etc.) but with Epic it seems to block the whole client, no windows even after 10 minutes. If I try to right click on the Playnite icon in the system tray bar, the app crashes.

### Logs

[playnite.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/11523234/playnite.zip)

**Comment by darklinkpower** [comment]
I believe this should be fixed. I'll close the issue but if it's happening still please let me know.
