### ISSUE TITLE
[Steam Wishlist Discount Notifier] Returning 0 Results

### ISSUE THREAD

**Issue by Grogwort** [darklinkpower/PlayniteExtensionsCollection#405]
### Extension name

Steam Wishlist Discount Notifier

### Bug Description

Recently stopped working.
Not getting notifications.
Clicking "View Steam Wishlist" shows progress bar, but returns 0 results.
I am authenticated through Steam in settings.

### Logs

[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/11557075/playnite.log)
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/11557076/extensions.log)

**Comment by da3ch1r** [comment]
I have identified the problem. No results are returned because some of the data returned, i assume, has changed.
The field for sub `id` has probably been changed to `packageid` and is `null` when not set (instead of 0?) Same goes for the `discount_pct` of the `sub`.

**Comment by solemgar** [comment]
Same issue here

**Comment by SiTWulf** [comment]
Same issue here

**Comment by Grogwort** [comment]
Thanks for fixing!

**Comment by darklinkpower** [comment]
I believe this should be fixed, if not please let me know to reopen the issue.
