### ISSUE TITLE
[Display Helper] Resolution not changing back when the game is closed

### ISSUE THREAD

**Issue by lelele5** [darklinkpower/PlayniteExtensionsCollection#433]
### Extension name

Display Helper

### Bug Description

It used to work perfectly before the update (the addon was named Resolution Changer then). The game launches in desired resolution but when it's closed the resolution stays the same, instead of reverting it to native resolution.

### Logs

Not available

**Comment by darklinkpower** [comment]
Please upload the logs that are requested in the issue template when you are opening the issue, otherwise I don't have any info to start by.

**Comment by lelele5** [comment]
The problem was gone after a format but suddenly it appeared again. I changed nothing, was just testing multiple resolutions for a game.

I can't upload a log because I can't find it.

**Comment by lelele5** [comment]
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12644044/extensions.log)

okay I think this it.

**Comment by XxRecKLesSxX** [comment]
I just download playnite and i got this add-on but it doesn't change the resolution back after i change and sometime it doesn' t change the resolution at all

**Comment by XxRecKLesSxX** [comment]
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12707207/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12707208/playnite.log)

Those are my logs for it

**Comment by darklinkpower** [comment]
Can you share the following?

1. What operating system are you using?
2. Is it 32 or 64 bits?
3. Are you using multiple monitors?
4. What resolutions and refresh rates does your monitor support? A screenshot of all of them would be helpful
5. Is there anything special in your setup or display configuration that you could think of?
6. @XxRecKLesSxX The extensions log indicate that you changed to 1366x768 resolution and 60hz and also that the original resolution is 1920x1080 and 60hz. Is that correct?

**Comment by XxRecKLesSxX** [comment]
1- Windows 11
2-64
3 No
4- it's 1920x1080 and 60hz
5- no i don't think so
6- yes my normal resolution is 1920x1080 and the one i chose for the game is 1366x768 it went into the chosen resolution when it started but it didn't revert back

**Comment by lelele5** [comment]
> Can you share the following?
> 
> 1. What operating system are you using?
> 2. Is it 32 or 64 bits?
> 3. Are you using multiple monitors?
> 4. What resolutions and refresh rates does your monitor support? A screenshot of all of them would be helpful
> 5. Is there anything special in your setup or display configuration that you could think of?
> 6. @XxRecKLesSxX The extensions log indicate that you changed to 1366x768 resolution and 60hz and also that the original resolution is 1920x1080 and 60hz. Is that correct?

Hello darklinkpower,

1. Windows 10 Pro
2. 64 bit
3. Single monitor
4. 
![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/85812468/34bf5f46-8cbe-4f2c-8f04-a2d9b48d5c32)
5. I don't think so. I used CRU to modify my Freesync range and removed 75 Hz mode from the resolution list. I have to say I did all these modifications right after a fresh format and right **before** using Display Helper. It worked flawlessly for a few days, and then I was testing resolutions for Starfield and out of a sudden it stopped reverting to native resolution.

**Comment by darklinkpower** [comment]
Can you test with these versions and tell my which (if any) work?

There are 3 different test builds included in the zip:
[DisplayHelper_TestBuilds.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12749657/DisplayHelper_TestBuilds.zip)

Before testing each one please delete your extensions.log file so it's cleared and create a copy of it after testing each one so you can send it to me separately please.

**Comment by darklinkpower** [comment]
Thanks for testing. Can you check if this test version works?

[ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_24.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12754601/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_24.zip)

**Comment by XxRecKLesSxX** [comment]
yea sure 
ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_24
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12756175/extensions.log)
Worked No Problems

**Comment by lelele5** [comment]
> Thanks for testing. Can you check if this test version works?
> 
> [ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_24.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12754601/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_24.zip)


This one also worked. Here is the log:

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12772841/extensions.log)

**Comment by darklinkpower** [comment]
Thanks for testing, I have released an update with the changes.

**Comment by darklinkpower** [comment]
I'm glad to know it's useful. I have plans for further improvements to the extension, although it's difficult to say when I'll get to it as time is limited and I have tons of other extensions and themes at hand too. If you have any ideas or suggestions please don't hesitate to open an issue.
