### ISSUE TITLE
[Search Collection] Games with ampersand in their names are not searched correctly

### ISSUE THREAD

**Issue by lighto-kun** [darklinkpower/PlayniteExtensionsCollection#437]
### Extension name

Search Collection

### Bug Description

Games with ampersand in their names are not searched correctly. The ampersand ends up in the URL **unencoded** causing the text after the ampersand to become a separate GET argument in the URL (basically cut off).

### To Reproduce

The bug occurs with any game that has and ampersand as part of its name.

Example game name: Command & Conquer Renegade

In the library right click the game, then select "Search" and "Google" (or any other search target).
In case of Google the address bar in the browser shows the following query: `https://www.google.com/search?q=Command%20&%20Conquer%20Renegade`
The google page shows that we searched for "Command".

### Logs

These are partial logs with only rows mentioning Search Collection.
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12591493/playnite.log)
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/12591494/extensions.log)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/363884c6e96ec37d003ce4b672163e128e0858d5
