### ISSUE TITLE
[Extra Metadata Loader] Logos from SteamGridDB don't seem to download for logoless Steam games

### ISSUE THREAD

**Issue by Elaborendum** [darklinkpower/PlayniteExtensionsCollection#438]
### Extension name

Extra Metadata Loader

### Bug Description

I have some Source mods installed on Steam that aren't available in the actual Steam store. When trying to download their available logos from SteamGridDB, the process is successful according to the popups, but no logo is downloaded or shown. Downloading it from Google or uploading it from a local file works normally.

Tried it with a bunch of different themes, and it happened in every one.

This somehow only happens with these games specifically.

### Logs

13-09 22:09:57.787|DEBUG|Extras#ThemeExtras:Pushed "Details View - Pre-Fortress 2"
13-09 22:10:08.126|DEBUG|ExtraMetadataLoader#Downloader:Downloading string from https://www.steamgriddb.com/api/v2/logos/steam/15042072108903675942?&nsfw=false&humor=false with method GET
13-09 22:10:08.464|ERROR|ExtraMetadataLoader#Downloader:Request was not completed for url
System.Net.Http.HttpRequestException: El código de estado de la respuesta no indica un resultado correcto: 404 (Not Found).
   en System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   en WebCommon.Downloader.<>c__DisplayClass11_0.<<GetHttpRequestString>b__0>d.MoveNext() en C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Common\WebCommon\Downloader.cs:línea 155

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/9612f1a394f4d592eb20b228ac8fe370c8b123a8
