### ISSUE TITLE
[Steam News and Players Viewer] Body text formatting is being lost due to Steam specific XML RSS Feed formatting.

### ISSUE THREAD

**Issue by Jas-SinghFSU** [darklinkpower/PlayniteExtensionsCollection#444]
### Extension name

Steam News and Players Viewer

### Bug Description

The News section doesn't seem to apply formatting such as Headers because the XML RSS Feed formatting data from Steam contains Steam specific styling. Headers are using styled divs `<div class="bb_h1">` instead of the standard headers `<h1>`. This means that unless the extension has imported all of the styling, then the body text just displays as regular text; without the formatting.

I have found a JSON RSS Feed for Steam news https://api.steampowered.com/ISteamNews/GetNewsForApp/v0002/?appid=899770&count=20

The documentation for the API can be found here https://partner.steamgames.com/doc/webapi/ISteamNews . The documentation also contains a list of all URL parameters supported the API.

You'll notice that the body text in this contains standard formatting that is not specific to Steam so this can be plugged in and used anywhere. Hopefully this is sufficient enough to fix the formatting issues.
### To Reproduce

Open any game that has Steam news.
Click the link at the bottom of the news to open in the browser.
Notice that the browser shows proper formatting for news that contains things such as header.
Meanwhile the same news in the extension has no formatting.

### Screenshots

Notice how the Headers display properly in this snippet of news.

![Correct News Formatting](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/21210205/b52a0575-a142-475e-80b0-d45e28fbefc1)

Notice that the same Headers from above are not formatted properly here. All formatting is lost and all text looks the same.

![Incorrect Extension Formatting - Notice the Headers](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/21210205/af300919-a160-4019-b0ee-bbdcf9bcba47)

**Comment by darklinkpower** [comment]
Done with https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/39ef67e61a956a3c2fb6f16b1d418a19f17198d1 and https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/d5ba01987c21e161f6770e9b7bd824d195966935

I reworked the extension to use that API endpoint but at the end of it I saw why I didn't use it initially: The news is in bbcode, which is very difficult to convert to html to display in the extension and had to rework it to use the current RSS method.

Please let me know if it's displaying as it should to close the issue.

**Comment by Jas-SinghFSU** [comment]
Apologies for the late reply. Yes, all the formatting seems to be spot on now. Thank you for such a quick turnaround!

**Comment by darklinkpower** [comment]
No worries, thanks for confirming it

**Comment by Jas-SinghFSU** [comment]
It seems that for certain games (Diablo IV) almost all of the formatting is replaced by an underline. I just discovered this today.
![Screenshot 2023-11-02 215353](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/21210205/0146bcec-fa00-4ab8-94c4-20809ac5a08f)

**Comment by darklinkpower** [comment]
That discrepancy is from Steam itself, the source the extension uses is setting the underline:
https://store.steampowered.com/feeds/news/app/2344520/l=english

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/f15b7d59-d5f3-4f4f-9a70-7077cf74a67e)

And checking the game community hub, it seems they also have this discrepancy where it shows like this before opening:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/11cc9297-0302-40f7-bf47-bb3a4501e564)

**Comment by Jas-SinghFSU** [comment]
Ah gotcha, yea in that case that's on Steam then. Tough to "guess" when their underlines are incorrect so nothing to fix here I suppose.
