### ISSUE TITLE
Filter Presets

### ISSUE THREAD

**Issue by Itachi0833** [darklinkpower/PlayniteExtensionsCollection#449]
### Extension name

PS5ish

### Feature Description

Hello, I understand that you have added Filter Presets to Playsite, which is a perfect change, but it only started on 10.10. However, I have encountered an issue where the PS5ish theme cannot be dropped down in the description box on 10.10. I don't know where the problem lies, and the main author should already have AFK, which prevents me from upgrading Playsite. Therefore, I hope you can add Filter Presets on top of 10.09? I really need this feature, thank you!

**Comment by Itachi0833** [comment]
Hello, I understand that you have added Filter Presets to Playnite, which is a perfect change, but it only started on 10.10. However, I have encountered an issue where the PS5ish theme cannot be dropped down in the description box on 10.10. I don't know where the problem lies, and the main author should already have AFK, which prevents me from upgrading Playsite. Therefore, I hope you can add Filter Presets on top of 10.09? I really need this feature, thank you!

**Comment by darklinkpower** [comment]
That's not possible. Extensions can't do that for fullscreen mode, this can only work on Desktop Mode.
