### ISSUE TITLE
[Steam Wishlist Discount Notifier] Can no longer authenticate

### ISSUE THREAD

**Issue by BloodShed-Oni** [darklinkpower/PlayniteExtensionsCollection#450]
### Extension name

Steam Wishlist Discount Notifier

### Bug Description

Trying to authenticate open's the window to login to Steam.
But the screen just shows 'new to Steam?' with button to register, but no QR code or login field.

Window also seems to auto-refresh ever 3 seconds

It stays like this forever

### To Reproduce

Open the extension settings and click on the 'Authenticate' button.

### Logs

-Nothing is generated in the logs when clicking the 'Authenticate' button

Below is the only thing generated in extention.log when clicking the Steam whistlist button in the sidebar

28-10 16:27:59.843|DEBUG|SteamWishlistDiscountNotifier#SteamLogin:Steam GetLoggedInSteamId64 not logged. Address: https://store.steampowered.com/login/?redir=account%2F%3Fl%3Denglish&redir_ssl=1
28-10 16:27:59.860|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifier:Started checking for wishlist. Status: AuthRequired, steamId: 
28-10 16:28:01.319|DEBUG|ExtraMetadataLoader#Downloader:Downloading file from https://store.steampowered.com/api/appdetails?appids=726020 to E:\Playnite474\ExtensionsData\705fdbca-e1fc-4004-b839-1d040b8b4429\61bf862e-1904-44d5-99ba-dd25d8404e89_SteamAppDetails.json.

### Screenshots

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/10365453/1362f3d2-39f3-4807-9846-76892d345a5a)

**Comment by darklinkpower** [comment]
Can you try with this build please?

[SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13196262/SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24.zip)

I made some small modifications and it works fine for me, it also refreshes after a small delay and correctly displays the login section.

**Comment by BloodShed-Oni** [comment]
> Can you try with this build please?
> 
> [SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13196262/SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24.zip)
> 
> Also try resizing the window.
> 
> I made some small modifications and it works fine for me, it also refreshes after a small delay and correctly displays the login section.
> 
>  Playnite.DesktopApp_anSj5FpZHG.mp4

I tried maximizing the window but that didn't change anything.

The modified version fixed the problem however (was logged in immediately after restarting playnite).

**Comment by darklinkpower** [comment]
> The modified version fixed the problem however (was logged in immediately after restarting playnite).

That's weird, the changes I made in that build were to actually fix that issue. Can you check if you are still not being logged out with this build?

[SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24 test2.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13196733/SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24.test2.zip)

After checking it, please upload your extensions.log file and if possible, please record a video to see what is happening when pressing the button.

**Comment by BloodShed-Oni** [comment]
> > The modified version fixed the problem however (was logged in immediately after restarting playnite).
> 
> That's weird, the changes I made in that build were to actually fix that issue. Can you check if you are still not being logged out with this build?
> 
> [SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24 test2.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13196733/SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24.test2.zip)
> 
> After checking it, please upload your extensions.log file and if possible, please record a video to see what is happening when pressing the button.

Got logged out today.
Both that and test2 behaves the same (as seen in the video).
It will just refresh that page without being logged in.

Here you go

```
29-10 19:23:20.843|DEBUG|SteamWishlistDiscountNotifier#SteamLogin:Steam GetLoggedInSteamId64 not logged. Address: https://store.steampowered.com/login/?redir=account%2F%3Fl%3Denglish&redir_ssl=1
29-10 19:23:20.843|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifier:Started checking for wishlist. Status: AuthRequired, steamId: 
29-10 19:23:20.843|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifier:Finished checking for wishlist
29-10 19:23:54.089|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Deleted ".steamcommunity.com" cookies
29-10 19:23:54.089|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Deleted "steamcommunity.com" cookies
29-10 19:23:54.135|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Deleted "store.steampowered.com" cookies
29-10 19:23:54.135|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Deleted "help.steampowered.com" cookies
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Deleted ".steampowered.com" cookies
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Deleted "steam.tv" cookies
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Deleted "checkout.steampowered.com" cookies
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Deleted "login.steampowered.com" cookies
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: _ga4s, domain: truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: _ga4sid, domain: truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: _ga4s, domain: truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: _ga4sid, domain: truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: ASP.NET_SessionId, domain: truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: ContentRecordRegionID, domain: truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: _ga, domain: .truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: _ga4, domain: .truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: _ga4s, domain: truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: _ga4sid, domain: truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: dnsDisplayed, domain: .truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: ccpaApplies, domain: .truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: signedLspa, domain: .truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: consentUUID, domain: truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: google-analytics_v4_mITV__ga4, domain: .truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: google-analytics_v4_mITV__engagementPaused, domain: .truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: google-analytics_v4_mITV__session_counter, domain: .truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: google-analytics_v4_mITV__engagementStart, domain: .truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: google-analytics_v4_mITV__counter, domain: .truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: google-analytics_v4_mITV__let, domain: .truesteamachievements.com
29-10 19:23:54.141|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: _ga, domain: truesteamachievements.com
29-10 19:23:54.157|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: _ga_0CPE0JFSCT, domain: .truesteamachievements.com
29-10 19:23:54.157|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: steamCountry, domain: .store.steampowered.com
29-10 19:23:54.157|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: sessionid, domain: .store.steampowered.com
29-10 19:23:54.157|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: timezoneOffset, domain: .store.steampowered.com
29-10 19:23:54.157|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: browserid, domain: .store.steampowered.com
29-10 19:23:54.157|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: cookieSettings, domain: .store.steampowered.com
29-10 19:23:54.157|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: steamLoginSecure, domain: .store.steampowered.com
29-10 19:23:54.157|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: cf_chl_2, domain: steamdb.info
29-10 19:23:54.157|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifierSettingsViewModel:Cookie name: __cf_bm, domain: .steamdb.info
```

https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/10365453/ef6d9030-6917-47c1-bb7f-e034f2315e2a

**Comment by darklinkpower** [comment]
Can you try with this build and also share the logs?

[SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24Test3.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13199214/SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24Test3.zip)

Also, if it still doesn't work:

1. Does the same happen when logging in in the Steam library plugin?
2. What happens if you go to some other page with the menu in the top left and try to log in?

**Comment by Funsponge** [comment]
> Can you try with this build and also share the logs?
> 
> [SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24Test3.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13199214/SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24Test3.zip)
> 
> Also, if it still doesn't work:
> 
>     1. Does the same happen when logging in in the Steam library plugin?
> 
>     2. What happens if you go to some other page with the menu in the top left and try to log in?

This version allowed me to authenticate with steam properly, and navigating around no longer reverts back to the original page.

Thanks.

**Comment by BloodShed-Oni** [comment]
> Can you try with this build and also share the logs?
> 
> [SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24Test3.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13199214/SteamWishlistDiscountNotifier_d5825a82-42bf-426b-ac47-5bea5df7aede_1_24Test3.zip)
> 
> Also, if it still doesn't work:
> 
> 1. Does the same happen when logging in in the Steam library plugin?
> 2. What happens if you go to some other page with the menu in the top left and try to log in?

That one worked.

**Comment by darklinkpower** [comment]
Thanks for testing
