### ISSUE TITLE
[Steam Wishlist Discount Notifier] Unable to authenticate after steam integration update

### ISSUE THREAD

**Issue by Funsponge** [darklinkpower/PlayniteExtensionsCollection#451]
### Extension name

Steam Wishlist Discount Notifier

### Bug Description

- Using the "Authenticate" button opens a new window to login to existing Steam account. 
- User is prompted to create a new user account without any option to login to an existing account.
- Browser window is continually refreshed, automatically closing the burger menu and redirecting the user back to the account creation page.

### To Reproduce

- Open F9 AddOns Menu.
- Navigate to Extensions Settings > Generic > Steam Wishlist Discount Notifier.
- Select "Authenticate".

### Logs

29-10 12:45:46.202|DEBUG|SteamWishlistDiscountNotifier#SteamLogin:Steam GetLoggedInSteamId64 not logged. Address: https://store.steampowered.com/login/?redir=account%2F%3Fl%3Denglish&redir_ssl=1
29-10 12:45:46.202|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifier:Started checking for wishlist. Status: AuthRequired, steamId: 
29-10 12:45:46.202|DEBUG|SteamWishlistDiscountNotifier#SteamWishlistDiscountNotifier:Finished checking for wishlist

### Screenshots

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/5205690/eaeb2676-22c6-4c74-bf19-c70a4b20cb0d)

**Comment by Funsponge** [comment]
Apologies, this is a duplicate of #450

**Comment by darklinkpower** [comment]
Closing as duplicate
