### ISSUE TITLE
[Steam Wishlist Discount Notifier] Check if game is already in the library

### ISSUE THREAD

**Issue by MalissaVeenstra** [darklinkpower/PlayniteExtensionsCollection#452]
### Extension name

Steam Wishlist Discount Notifier

### Feature Description

Hi! I was wondering if it would be possible to add an option to check if a game on the Steam wishlist is already present in the playnite library. I sometimes discover that I already had a game on for instance Epic or Amazon that I picked up as a free game. However, on some occasions, I discovered this too late and bought a game that I already had, which is money I could have spent on a different game ;)

**Comment by darklinkpower** [comment]
Hi, just to clarify, is this a feature you want for the notifications, the sidebar wishlist view or both?

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/e4b309ff844b1977f821bba84c1387a51250cb02 and available in new update.

Implemented support in wishlist view, as well as an option for notifications.

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/a87c7cdd-1657-4158-989d-9de34b038181)
