### ISSUE TITLE
Date Importer - not working in Playnite 9

### ISSUE THREAD

**Issue by SlipperyJim** [darklinkpower/PlayniteExtensionsCollection#46]
The date importer does not seem to be working at all. Whenever I try and do and import, on any of the stores, it comes back with:

![image](https://user-images.githubusercontent.com/34274435/132985274-0f1145c3-e2dd-4353-814e-d0bea08b52da.png)

**Comment by darklinkpower** [comment]
Duplicate https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/39
