### ISSUE TITLE
[Harmony] Blurred Game Background

### ISSUE THREAD

**Issue by Itzhak880** [darklinkpower/PlayniteExtensionsCollection#462]
### Extension name

Harmony

### Bug Description

Before the major 2.49 "Harmony" theme update, game background and window background didn't "share" settings. Now, they do. Which means that settings like: Appearance -> "Blur background" and "Darken Background" are now affecting both backgrounds instead of only the window background, and this results in a blurry game background (see screenshots).

### To Reproduce

Turn these Playnite settings on:
Appearance:
- [ ] Use game background image as window background
- [ ] Blur background
- [ ] Darken background

### Logs

Is this necessary?

### Screenshots

These images show the game background not blurred, only the window background (before the theme update):

![Desktop_GTA_V](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/131331158/c81e033c-8fc2-4b4d-bd2d-ca98aef9618e)

![Desktop_AA2](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/131331158/1b3ac413-2811-40e4-a987-244022863d3e)

And these images show the game background blurred too (after the theme update): 

![Laptop_GTA_V](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/131331158/d4949edf-2167-4439-8550-4c3bfe31978f)

![Laptop_AA2](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/131331158/8660c4f6-7f23-4b97-a5cd-f3ec0861e89c)

**Comment by darklinkpower** [comment]
It seems you got confused, this is not the correct repository.
