### ISSUE TITLE
[Game Relations] Similar Games & Same Series

### ISSUE THREAD

**Issue by ariesps** [darklinkpower/PlayniteExtensionsCollection#463]
### Extension name

Game Relations

### Feature Description

As a suggestion, I think it could be a good idea that "Similar Games" section does not show the games that are part of a series, if the "Same Series" section is active.

This option would give more visibility to other games and would avoid that "Similar Games" and "Same Series" show almost the same results.

### Screenshots

Example of result trying to avoid. Maybe a bit too extreme.

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/7125095/bb052500-42d3-4b57-9389-ba95d6b2b4b1)

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/543a607b820b8c4c7a002b83eb830455632babab and available in new update.
