### ISSUE TITLE
[Game Relations] Exclusion list based on other fields

### ISSUE THREAD

**Issue by palharesf** [darklinkpower/PlayniteExtensionsCollection#465]
### Extension name

Game Relations

### Feature Description

Hi - currently I can exclude certain tags from being used by Game Relations. I would love to be able to pick other fields to determine whether a related game is shown or not. Specifically, I would like the games that I've categorized as having "Completion Status" Beaten or Completed to be omitted from Game Relations results, but I believe other fields could be useful for other people. 

Thank you!

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/7ea46eb5a958ee0199695a7fbe184906ad8d4706 and available in new update.
