### ISSUE TITLE
[Filter Presets Quick Launcher] Open library when clicking on left sidebar

### ISSUE THREAD

**Issue by ManitaDeCerdo** [darklinkpower/PlayniteExtensionsCollection#475]
### Extension name

Filter Presets Quick Launcher

### Feature Description

When configuring the extension to appear in left sidebar, I have gone to click on the shortcuts when I was on any other screen than the library and nothing happens. It only works when the library is open.

Example: I have the "Start Page" extension and from it, when I click on any of the left sidebar shortcuts nothing happens.
I have tried with all my extensions that I have shortcuts in the left sidebar and the same thing happens with all of them.

### Screenshots

Selected in red are the extension shortcuts.
![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/116158452/fa34a542-a36a-4fb5-a064-217f2b1e745a)

En la biblioteca, si funcionan los atajos.
![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/116158452/04c4e64b-f44d-4a3c-9627-cda9cd098356)

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/99aed0de9242e47da957cec6e96670968ec234cb
