### ISSUE TITLE
Playstate causes an error after pressing the button.

### ISSUE THREAD

**Issue by Ksaan1** [darklinkpower/PlayniteExtensionsCollection#479]
### Extension name

Playstate 

### Bug Description

Hello, every time I use the hotkey set for Playstate to pause the game, nothing happens. But after the game is minimized, an error hangs.

Here are the saved error logs.

### Logs

[Error log.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13664717/Error.log.zip)

**Comment by darklinkpower** [comment]
Should be fixed with https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/a750119112c0281022770ea8ee5064734f72fdc1, can you check please with the new version?

**Comment by darklinkpower** [comment]
Closing since there was no reply.
