### ISSUE TITLE
Help on how to configure "PlayState" plugin.

### ISSUE THREAD

**Issue by GamingBoiYT** [darklinkpower/PlayniteExtensionsCollection#480]
PlayState seems like an amazing concept but i don't know how to set it up. I talked to darklinpower on reddit and he told me to open an issue here on github. I just want to know if there's any source that explains how to set it up correctly. There aren't any problems with the plugin, it's just that i don't know how to get it set up.

**Comment by darklinkpower** [comment]
Some information is available here: https://github.com/darklinkpower/PlayniteExtensionsCollection/wiki/PlayState

You can also check the extension settings to configure how you want the extension to behave, some elements there have explanations in tooltips if you hover on them for a few seconds

**Comment by amy10111111111** [comment]
> Some information is available here: https://github.com/darklinkpower/PlayniteExtensionsCollection/wiki/PlayState
> 
> You can also check the extension settings to configure how you want the extension to behave, some elements there have explanations in tooltips if you hover on them for a few seconds
Hello I read this on wiki about PlayState says:" An option to deduct the suspended time when the game is closed is available, which in practice stops playtime tracking."  how do I activate that? because its not mentioned in the wiki and  I tried to search for the option but couldn't find it.

**Comment by darklinkpower** [comment]
@amy10111111111 

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/fd42bd30-9b81-4fcb-8f46-357b3cc68825)

**Comment by amy10111111111** [comment]
> @amy10111111111
> 
> ![image](https://private-user-images.githubusercontent.com/1389286/307557007-fd42bd30-9b81-4fcb-8f46-357b3cc68825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NTc0MDIsIm5iZiI6MTcwODg1NzEwMiwicGF0aCI6Ii8xMzg5Mjg2LzMwNzU1NzAwNy1mZDQyYmQzMC05YjgxLTRmY2ItOGY0Ni0zNTdiM2NjNjg4MjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjVUMTAzMTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzA3YTA1YzBmOTdmYTY4MTQ3YjE1Mzg1Y2M1ZjU3MjBlNDYwMjliMDZmOThkOGYzNzYxYjZlYzMxYjk2MTdjYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TmiHL-6zAYfpUGTzmVPXExCwG2F6FylC99mtQB_rQ0Y)


Thanks
