### ISSUE TITLE
[PlayState] System.DllNotFoundException: Unable to load DLL 'XInputInterface'

### ISSUE THREAD

**Issue by stealth62** [darklinkpower/PlayniteExtensionsCollection#484]
### Extension name

playstate add-on

### Bug Description

31-12 10:32:26.756|ERROR|PlayniteApplication:Unhandled exception occured.
System.DllNotFoundException: Unable to load DLL 'XInputInterface': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at PlayState.XInputDotNetPure.Imports.XInputGamePadGetState(UInt32 playerIndex, RawState& state)

### To Reproduce

Newly installed win11

### Logs

[playstate error.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13800188/playstate.error.zip)

### Screenshots

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/14282189/e0298353-2bd3-4f84-8c12-5e944b5fe1c7)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/3aca80282ae73850c903e94473d6de9434be5496

**Comment by stealth62** [comment]
Thank you so much @darklinkpower  happy new year!
