### ISSUE TITLE
[Installation Status Updater] Installed games are set as uninstalled

### ISSUE THREAD

**Issue by OmarNamis** [darklinkpower/PlayniteExtensionsCollection#485]
### Extension name

Installation Status Updater

### Bug Description

After installing the latest version of the extension (2.41), all games that don't have the "library integration play action" option checked are getting marked as uninstalled.

This includes all manually added games, and some games from Epic where I turned off the option myself and selected the path of the exe file for them.

Installing the previous version (2.40) fixes the issue, and games are getting marked as installed again.

### Logs

Nothing relevant in Playnite.log file.

### Extensions.log

After installing version 2.41

> 31-12 18:17:04.792|INFO |InstallationStatusUpdater#InstallationStatusUpdater:Marked as installed: 0, as uinstalled: 204 

After reverting to version 2.40

> 31-12 18:21:09.253|INFO |InstallationStatusUpdater#InstallationStatusUpdater:Marked as installed: 204, as uinstalled: 0 

### Example for a game that got marked as uninstalled:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/14346945/a264b1c3-a412-44d6-86ce-6b5af639b72c)

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/14346945/0a14e470-5a7c-44a4-babb-6301ffa5a532)

### Extension settings:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/14346945/e95e1964-c54d-4197-9739-c70e386e416b)

**Comment by dryice213** [comment]
Having the exact same issue. Downgrading worked for me too, will stay on 2.40 for now,

For me, all manually added games and all emulated games got uninstalled. When I manually selected them as installed again, it worked until playnite restarted and it was marked uninstalled again.

**Comment by Whitechapel-1888** [comment]
I can confirm this issue as well. All games that are installed on an external drive and run via an emulator are permanently set to uninstalled, even if the external drive is added on my system.
