### ISSUE TITLE
Instillation Status Updater Setting all Games as Uninstalled

### ISSUE THREAD

**Issue by RosellaCamella** [darklinkpower/PlayniteExtensionsCollection#486]
### Extension name

Instillation Status Updater

### Bug Description

I updated the Instillation Status Updater last night to 2.41 and it instantly set all of my games to uninstalled, including emulation roms that literally don't need installing. When I leave the extension enabled, set a game as installed and then restart Playnite, it sets the game back to uninstalled. However when I turn off the Instillation Status Updater, set the game as installed and restart Playnite, it stays installed. I keep backups of my entire Playnite installation and when I paste a previous version of the Installation Status Updater and start Playnite, everything works perfectly and all the instillation status' are corrected.

### To Reproduce

To reproduce, update the Instillation Status Updater to 2.41, and restart Playnite.

### Logs

[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13801979/playnite.log)

### Screenshots

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/107732413/6df4df05-976b-408a-9b47-89038b4e2d28)
![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/107732413/f599bfc4-0a3c-4dfe-a72f-16de0695ddac)

**Comment by Bovive** [comment]
Same here. I didn't have a backup, but I did download the previous version (Installation_Status_Updater_2_40.pext) from [here](https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/tag/2023.08.18_ceff63a9) and that put my games back to installed.

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/abbb33ee50ddff0caa3a7c1738c11a68a5b17082

**Comment by RosellaCamella** [comment]
> Fixed in [abbb33e](https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/abbb33ee50ddff0caa3a7c1738c11a68a5b17082)

Do I just need to copy the contents of abbb33e somehwere?

**Comment by darklinkpower** [comment]
> > Fixed in [abbb33e](https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/abbb33ee50ddff0caa3a7c1738c11a68a5b17082)
> 
> Do I just need to copy the contents of [abbb33e](https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/abbb33ee50ddff0caa3a7c1738c11a68a5b17082) somewhere?

Just update the addon in Main menu > Add-ons > Updated
