### ISSUE TITLE
[Installation Status Updater] 2.41

### ISSUE THREAD

**Issue by Litcube** [darklinkpower/PlayniteExtensionsCollection#487]
### Extension name

Installation Status Updater

### Bug Description

The new update set all my installed games as uninstalled.

### To Reproduce

Install the update.

### Logs

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13802260/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/13802267/playnite.log)

### Screenshots

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/15916172/6b748cd1-79e9-4fe7-b527-ef0888b49237)
![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/15916172/dc992c33-c009-48a4-a481-594517a58133)

**Comment by darklinkpower** [comment]
Duplicate https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/486
