### ISSUE TITLE
[Library Exporter Advanced] Request: Option to Export "Name" and/or "Sorting Name" In Export Window

### ISSUE THREAD

**Issue by yurikoma** [darklinkpower/PlayniteExtensionsCollection#491]
### Extension name

Library Exporter Advanced

### Feature Description

Just wanted to request that the "Name" and "Sorting Name" be added to the export options.

### **Playnite**
By default, Playnite will automatically fill sorting names for batch-added games, removing "A, An, The" words from the start of game names and using this new name as the Sorting Name. (users can change this)

### **Library Exporter Advanced**
Currently "Name" is forced, likely so we are guaranteed to know what the other data is related to, however if I want to sort this alphabetically and I use Sorting Names inside Playnite, the exported list will end up in a different order than on Playnite.

While this is not too big of a deal and people could probably just manually select all then use export selection instead of export all, it would be much more convenient if it was possible for users to choose between exporting Name and Sorting Name or have an option to export both.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/69ffe112f2d1c5bc083f17295d292500745da304 and available in new update.
