### ISSUE TITLE
[PlayState] Minimize on Suspend

### ISSUE THREAD

**Issue by tynansdtm** [darklinkpower/PlayniteExtensionsCollection#493]
### Extension name

PlayState

### Feature Description

If possible, could the PlayState process suspend function optionally minimize the game automatically?

I was playing Lena's Inception, and suspending the game makes it not interactable (as expected) but it was also stuck always on top. To fix this I had to un-suspend, minimize, and re-suspend. I see that alt-tabbing is suggested in the FAQ, but I'm wondering if it could be rolled into the button combination instead.

**Comment by darklinkpower** [comment]
Implemented and available as an option in v2.72 update.
