### ISSUE TITLE
(OpenCriticMetadata) Playnite to access OpenCritic Scores for Metadata

### ISSUE THREAD

**Issue by PanzerFranzzz** [darklinkpower/PlayniteExtensionsCollection#506]
### Extension name

OpenCriticMetadata

### Feature Description

I see that you seem to have already programmed something that allows Playnite to access OpenCritic Scores as metadata source -- I just thought maybe you might please find time to compile it and create a release package of the extension  --- or better yet, perhaps even add it to the addon browser inside of Playnite --- many thanks in advance! : https://github.com/darklinkpower/PlayniteExtensionsCollection/tree/master/source/Metadata/OpenCriticMetadata

**Comment by darklinkpower** [comment]
Hi, I don't plan to release this extension publicly but please send me a private message on reddit to talk about this.
