### ISSUE TITLE
[Extra Metadata Loader] Doesn't work properly after 1.56

### ISSUE THREAD

**Issue by hallhoward221** [darklinkpower/PlayniteExtensionsCollection#509]
### Extension name

Extra Metadata Loader

### Bug Description

Hello, guys. I have a problem with Extra MetaData Loader. I am trying to get videologos from youtube or steam but cant download it. Cant even search video on youtube from this extension. Thats what i get from log file 
Dunno , last year it was working fine. About 2 month ago started to happening.
Idk, installed 1.31 version from here  https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/169 . Now extension works fine. But on the latest 1.76 doesn't. Also 1.68, 1.62 "failed to execute menu action". 1.56 doesnt download some videos from steam. 1.50 works fine ill stick with 1.50 till fix. Maybe i need install something from microsoft

### Logs

03-03 22:03:15.112|DEBUG|SteamLibrary#SteamTagNamer:Opening C:\Users\User\Downloads\Playnite914\Extensions\SteamLibrary_Builtin\SteamShared\TagLocalization\english.json
03-03 22:03:15.132|DEBUG|UniversalSteamMetadata#SteamTagNamer:Opening C:\Users\User\Downloads\Playnite914\Extensions\Universal_Steam_Metadata\SteamShared\TagLocalization\english.json
03-03 22:03:15.773|INFO |GameActivity#PluginDatabaseObject`4:LoadDatabase with 95 items - 00:00.79
03-03 22:03:15.773|INFO |SuccessStory#PluginDatabaseObject`4:LoadDatabase with 95 items - 00:00.70
03-03 22:03:15.773|INFO |HowLongToBeat#PluginDatabaseObject`4:LoadDatabase with 58 items - 00:00.76
03-03 22:03:16.354|DEBUG|EpicLibrary#EpicLibrary:Found 1 installed Epic games.
03-03 22:03:18.507|DEBUG|EpicLibrary#EpicLibrary:Found 69 library Epic games.
03-03 22:03:18.507|WARN |SteamLibrary#SteamLibrary:Found external Steam directory, but path doesn't exists: D:\SteamLibrary
03-03 22:03:18.507|DEBUG|SteamLibrary#SteamLibrary:Found 21 installed Steam games.
03-03 22:03:19.001|DEBUG|SteamLibrary#SteamLibrary:Found 243 library Steam games.
03-03 22:03:30.231|DEBUG|ExtraMetadataLoader#VideosDownloader:DownloadSteamVideo starting for game Diablo IV
03-03 22:03:30.231|DEBUG|ExtraMetadataLoader#VideosDownloader:Steam id found for Steam game
03-03 22:03:30.267|DEBUG|ExtraMetadataLoader#HttpClientFactory:Created service provider with IHttpClientFactory
03-03 22:03:30.278|ERROR|ExtraMetadataLoader#HttpRequestBuilder:Download failed
System.TypeInitializationException: Инициализатор типа "Log" выдал исключение. ---> System.TypeInitializationException: Инициализатор типа "PerTypeValues`1" выдал исключение. ---> System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.
   в System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   в System.SpanHelpers.PerTypeValues`1..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.SpanHelpers.IsReferenceOrContainsReferences[T]()
   в Microsoft.Extensions.Logging.LogValuesFormatter..ctor(String format)
   в Microsoft.Extensions.Logging.LoggerMessage.CreateLogValuesFormatter(String formatString, Int32 expectedNamedParameterCount)
   в Microsoft.Extensions.Logging.LoggerMessage.DefineScope[T1,T2](String formatString)
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.Log..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.Log.BeginRequestPipelineScope(ILogger logger, HttpRequestMessage request)
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>d__5.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в WebCommon.HttpRequestBuilder.<DownloadStringAsync>d__32.MoveNext() в C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Common\WebCommon\HttpRequestBuilder.cs:строка 202
03-03 22:05:26.110|ERROR|ExtraMetadataLoader#HttpRequestBuilder:Download failed
System.TypeInitializationException: Инициализатор типа "Log" выдал исключение. ---> System.TypeInitializationException: Инициализатор типа "PerTypeValues`1" выдал исключение. ---> System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.
   в System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   в System.SpanHelpers.PerTypeValues`1..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.SpanHelpers.IsReferenceOrContainsReferences[T]()
   в Microsoft.Extensions.Logging.LogValuesFormatter..ctor(String format)
   в Microsoft.Extensions.Logging.LoggerMessage.CreateLogValuesFormatter(String formatString, Int32 expectedNamedParameterCount)
   в Microsoft.Extensions.Logging.LoggerMessage.DefineScope[T1,T2](String formatString)
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.Log..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.Log.BeginRequestPipelineScope(ILogger logger, HttpRequestMessage request)
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>d__5.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в WebCommon.HttpRequestBuilder.<DownloadStringAsync>d__32.MoveNext() в C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Common\WebCommon\HttpRequestBuilder.cs:строка 202
03-03 22:05:27.530|ERROR|ExtraMetadataLoader#HttpRequestBuilder:Download failed
System.TypeInitializationException: Инициализатор типа "Log" выдал исключение. ---> System.TypeInitializationException: Инициализатор типа "PerTypeValues`1" выдал исключение. ---> System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.
   в System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   в System.SpanHelpers.PerTypeValues`1..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.SpanHelpers.IsReferenceOrContainsReferences[T]()
   в Microsoft.Extensions.Logging.LogValuesFormatter..ctor(String format)
   в Microsoft.Extensions.Logging.LoggerMessage.CreateLogValuesFormatter(String formatString, Int32 expectedNamedParameterCount)
   в Microsoft.Extensions.Logging.LoggerMessage.DefineScope[T1,T2](String formatString)
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.Log..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.Log.BeginRequestPipelineScope(ILogger logger, HttpRequestMessage request)
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>d__5.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в WebCommon.HttpRequestBuilder.<DownloadStringAsync>d__32.MoveNext() в C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Common\WebCommon\HttpRequestBuilder.cs:строка 202
03-03 22:05:30.012|ERROR|ExtraMetadataLoader#HttpRequestBuilder:Download failed
System.TypeInitializationException: Инициализатор типа "Log" выдал исключение. ---> System.TypeInitializationException: Инициализатор типа "PerTypeValues`1" выдал исключение. ---> System.IO.FileNotFoundException: Не удалось загрузить файл или сборку "System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" либо одну из их зависимостей. Не удается найти указанный файл.
   в System.SpanHelpers.PerTypeValues`1.MeasureArrayAdjustment()
   в System.SpanHelpers.PerTypeValues`1..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в System.SpanHelpers.IsReferenceOrContainsReferences[T]()
   в Microsoft.Extensions.Logging.LogValuesFormatter..ctor(String format)
   в Microsoft.Extensions.Logging.LoggerMessage.CreateLogValuesFormatter(String formatString, Int32 expectedNamedParameterCount)
   в Microsoft.Extensions.Logging.LoggerMessage.DefineScope[T1,T2](String formatString)
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.Log..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.Log.BeginRequestPipelineScope(ILogger logger, HttpRequestMessage request)
   в Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>d__5.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в WebCommon.HttpRequestBuilder.<DownloadStringAsync>d__32.MoveNext() в C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Common\WebCommon\HttpRequestBuilder.cs:строка 202

**Comment by darklinkpower** [comment]
Can you check if your extensions are up to date in Main menu > Addons > Updates? If that doesn't work, try uninstalling the extension and installing again

**Comment by hallhoward221** [comment]
I have already done that many times Installing latest version (1.76) doesnt fix this error. 
![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/105017072/6327fbf8-b89a-40f1-a359-42602479707d)

**Comment by darklinkpower** [comment]
Just to be sure, are you clicking the "Update add-ons" button there? From the scrollbar height it looks like there are a lot of updates there.

**Comment by Sergiokool** [comment]
Hi , i have the same error , but in my case is only youtube video search that dont appear nothing when i put any game to seach a video to download :/

**Comment by darklinkpower** [comment]
> Hi , i have the same error , but in my case is only youtube video search that dont appear nothing when i put any game to seach a video to download :/

What version of the extension do you have installed? Please also upload your logs. Main menu > About Playnite > User data directory > Playnite.log and Extensions.log

**Comment by Sergiokool** [comment]
>
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14654850/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14654851/playnite.log)
 > Hi , i have the same error , but in my case is only youtube video search that dont appear nothing when i put any game to seach a video to download :/
> 
> What version of the extension do you have installed? Please also upload your logs. Main menu > About Playnite > User data directory > Playnite.log and Extensions.log

Im using 1.77 when i search videos to download from youtube nothing shows up only the windows the letter i put to search and nothing else :/ 

this are the logs , i missing something ? :/

**Comment by Sergiokool** [comment]
> > Hi , i have the same error , but in my case is only youtube video search that dont appear nothing when i put any game to seach a video to download :/
> 
> What version of the extension do you have installed? Please also upload your logs. Main menu > About Playnite > User data directory > Playnite.log and Extensions.log

ok i found the problem, is some malware on my pc thats is interfering with youtube , i run malwarebytes and now all works greats thanks a lot and sorry :) never knows my pc has a malware xD cheers

**Comment by hallhoward221** [comment]
Dunno, I've reinstalled Playnite as portable. Installed all previous addons with latest version and Playnite started to work properly without issues.
