### ISSUE TITLE
[Details to Grid View Converter] Does not work

### ISSUE THREAD

**Issue by MangoChocobo** [darklinkpower/PlayniteExtensionsCollection#510]
### Extension name

Details to Grid View Converter

### Bug Description

I have done a fresh install of Playnite, Deleted all my settings, and I am unable to get Details to Grid View Coonverter to work with Harmony. I have gone into the extension settings and checkboxed it. The extension is also the ONLY  extension on my system. I wanted to make sure there was no possibilities of there being n incompatibility. As well as have restarted Playnite several times just in case. 

### Logs

[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14597184/playnite.log)
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14597185/extensions.log)

### Screenshots

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/25861147/fdf2c589-f0da-4596-ac25-b794b10aea38)
![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/25861147/1938423a-1aff-433f-af2b-919dbddb0646)

**Comment by darklinkpower** [comment]
You are in Details View. You need to switch to Grid View by pressing here:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/fa9f99f2-4bc8-4435-9ef9-4192a0c57607)

Also make sure to increase the Grid View details Panel width in Playnite settings.
