### ISSUE TITLE
[Status Updater] Not Updating Status to "Not Installed" after Deleing the ROM file from Disk

### ISSUE THREAD

**Issue by MotherSoraka** [darklinkpower/PlayniteExtensionsCollection#511]
### Extension name

Installation Status Updater

### Bug Description

Im not sure if its a bug or by design, but this Add-on doesnt seem to be checking on game ROMs and updating their Playnite entry accordingly.

I used the default scanner to import my old Atari/NES ROMs, then decided to delete a bunch of them from the original scanned path, then tried both "Check Installation status of All games" and Updating my Scanned folder for Roms, but nothing happened, the status of games are still set to YES

### Logs

```
StatusUpdater:
19-03 06:19:18.504|INFO |InstallationStatusUpdater#InstallationStatusUpdater:Marked as installed: 0, as uinstalled: 0 
19-03 06:19:27.895|INFO |InstallationStatusUpdater#InstallationStatusUpdater:Marked as installed: 0, as uinstalled: 0 
```
```
Playnite.Log:
19-03 06:19:17.342|INFO |MainViewModelBase:Importing emulated games from Atari 2600 (Dummy) config.
19-03 06:19:17.408|INFO |GameScanner:Scanning emulated directory C:\Games\Retro Games\ROM Archives\LaunchBox Metadata\Atari 2600.
19-03 06:19:17.429|INFO |MainViewModelBase:Starting Library Install Size scan
19-03 06:19:17.429|INFO |MainViewModelBase:Finished Library Install Size scan
```

### Screenshots

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/72297825/58a71576-8115-4ad3-a7e3-2bedde4572f4)
![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/72297825/8927e145-39ef-42a0-91b8-573c4c9a04ec)

**Comment by darklinkpower** [comment]
Thanks for the report, it was a bug and a fix is available in a new update.
