### ISSUE TITLE
[Installation Status Updater] Indiegala games are all marked "installed"

### ISSUE THREAD

**Issue by Judassem** [darklinkpower/PlayniteExtensionsCollection#515]
### Extension name

Installation Status Updater

### Bug Description

Since the last update, Installation Status Updater marks all the games I own from Indiegala as installed when I have none of them actually installed. I've tried manually clicking on "Uninstall" for each of them, but there are about 300 games and it would take a long time to do that manually. What's worse is that it marks them right back to installed after every library update.

I've tried installing version 2.40, but it didn't mark those games back to uninstalled. Is there anything I can do?

### Logs

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14666454/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14666455/playnite.log)

### Screenshots

![sdsdsdsdsdssd](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/31585209/5905d98b-30d0-4d3b-ba95-150832026f15)

**Comment by GCTuba** [comment]
I have the same problem even after the 2.46 update. To [Judassem](https://github.com/Judassem) though, you can filter your library by IndieGala, select all of them, click edit, then mark all of them as uninstalled simultaneous until the issue is resolved.

**Comment by darklinkpower** [comment]
Can you upload screenshots of a game Installation and Action Tabs, as well as your extension settings?

**Comment by GCTuba** [comment]
![game action](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/146034906/ed6250b4-fe60-420f-9124-c2ead913faed)
![game installation](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/146034906/95124170-0770-4f00-a4a4-c7a876b844d6)
![installation status updater settings](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/146034906/ab6afca2-f0a2-455c-bac1-4b65be59830f)

**Comment by darklinkpower** [comment]
The issue lies in the indiegala extension adding that `Action` to download the game. A better solution would be for the extension to not add it and handle it when pressing the Install button. on Playnite

Try enabling this option to fix this:
![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/28f35be6-9f5a-4377-9644-06cdcd1b13e1)

Or disabling this other one:
![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/20ffe2bd-4957-4dfb-90cb-9e2ac4161a1c)

**Comment by darklinkpower** [comment]
I've release an update that enables this option by default, which will prevent this issue:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/65a0e799-22dd-4e67-88d6-8bb6803aa593)

I highly recommend to ask Lacro59 to implement the download procedure when using the Playnite Install button.

**Comment by Judassem** [comment]
Hi @darklinkpower, the latest update seems to have fixed it. I did as @GCTuba said and changed all games to uninstalled, and then updated the extension, updated Indiegala library and it no longer marks those games installed. Thank you guys for the help!
