### ISSUE TITLE
[Game Relations] Make the darkening of the cover if not installed, configurable.

### ISSUE THREAD

**Issue by shakeyourbunny** [darklinkpower/PlayniteExtensionsCollection#516]
### Extension name

Game Relations

### Feature Description

Currently, if you click on the game relations tab, the covers of the listed games are always dimmed if not installed.

Please make an option that the display of the cover is not dimmed / darkened if a game is not installed.

### Screenshots

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/5352403/80cb87ea-f4f9-46f8-85d0-046a21c15feb)

**Comment by darklinkpower** [comment]
Duplicate of https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/459
