### ISSUE TITLE
[Details to Grid View Converter] Conversion enabled for theme but the right panel stays very narrow

### ISSUE THREAD

**Issue by drt0** [darklinkpower/PlayniteExtensionsCollection#517]
### Extension name

Details to Grid View Converter

### Bug Description

I installed Details to Grid View Converter with DH Dawn, Helium, Nova X and enabled them in the addon settings. However, after I restarted the right panel in Grid view remained really narrow.

### Logs

[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14728803/playnite.log)
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/14728805/extensions.log)

### Screenshots

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/3438438/64c84738-98c3-47e8-8b2a-8deb1dbe52ca)

**Comment by darklinkpower** [comment]
This is not controlled by the extension, you need to increase its width in Playnite settings here:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/3a57f741-c546-43b2-b76e-8fe9bdc5cc80)
