### ISSUE TITLE
[Purchase Date Importer] Fails importing from GOG complaining about not logged in being logged in in fact

### ISSUE THREAD

**Issue by Mancubuss** [darklinkpower/PlayniteExtensionsCollection#529]
### Extension name

Purchase Date Importer

### Bug Description

An attempt to import data from GOG results in an error:

<img width="352" alt="image" src="https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/29070996/fb79a001-a383-4cf3-b441-2f134d65bf4d">

Closing the error and pressing 'Login' opens a frame which shows user being logged in on GOG site, being able to successfully navigate profile section.

<img width="800" alt="image" src="https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/29070996/c2a62246-ecfa-42c7-a6db-540c8159efe7">

### To Reproduce
Preconditions: 
1. GOG account added and successfully authorized in
2. Extension added

Steps:
1. Open Playnite menu and choose Extensions - Purchase Date Importer - Open...
2. Choose 'GOG' from Library menu
3. Press 'Import ...'

### Logs
[Playnite.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/15141238/Playnite.zip)

**Comment by darklinkpower** [comment]
Fix available in new update.
