### ISSUE TITLE
[Xbox Metadata] Merge plugins

### ISSUE THREAD

**Issue by Jeshibu** [darklinkpower/PlayniteExtensionsCollection#530]
### Extension name

Xbox Metadata

### Feature Description

Hey, I see you've released an Xbox Metadata plugin - I've released one previously, and there's no hard feelings here, just that here's now two extensions named Xbox Metadata, which is confusing for users. I suggest we remove one, and it's fine if it's yours that remains.

I haven't had a chance to compare the two, in practice, but looking at the code, it looks like we could add the Xbox 360 system search/results from my repo. Something I hadn't been able to fix about mine was that the game search always lasted about 10 seconds, which you might have solved. Either way a merger is probably best, whether as a PR to my repo or yours.

**Comment by darklinkpower** [comment]
Hi, I'm really sorry, I didn't know there was a plugin for Xbox. I totally missed it 😣😣😣
I apologize, I'm unable right now but I'll be removing it asap, likely in the afternoon.

**Comment by darklinkpower** [comment]
PR to delete it opened, I apologize if this caused any discomfort https://github.com/JosefNemec/PlayniteAddonDatabase/pull/345

**Comment by Jeshibu** [comment]
No worries! Please don't delete it from this repo yet, you've got at least one search method I hadn't seen yet.

**Comment by darklinkpower** [comment]
No worries, I plan to keep it here for personal use only.
