### ISSUE TITLE
Geforcenow Enabler not importing at all

### ISSUE THREAD

**Issue by allenfrisch** [darklinkpower/PlayniteExtensionsCollection#537]
### Extension name

NvidiaGeForceNowEnabler

### Bug Description

Works perfectly on ROG Ally, but cannot get any GFN games to import on GPD WIN Mini. I have tried everything but can't figure out what's causing the problem.

### To Reproduce

Neither updating game library nor updating enabled status of games from the extensions menu find any game titles.

### Logs

[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/15370276/extensions.log)
[playnite.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/15370277/playnite.log)

**Comment by darklinkpower** [comment]
Fixed in new update.
