### ISSUE TITLE
ReviewViewer (Playnite 9) Menu items not displaying

### ISSUE THREAD

**Issue by SlipperyJim** [darklinkpower/PlayniteExtensionsCollection#54]
![image](https://user-images.githubusercontent.com/34274435/134050234-6f7201c9-ea2f-4f76-9ff4-64c86ac92a08.png)

Localization does not seem to be working properly. My OS is en-gb.

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/a790611bba88534d58fedb1e9f3aed3b3bb75983
