### ISSUE TITLE
[Splash Screen] Dual Screen Problem

### ISSUE THREAD

**Issue by JFERDZ** [darklinkpower/PlayniteExtensionsCollection#541]
### Extension name

SplashScreen

### Feature Description

Hi,
I use a dual screen setup and every time I run a game the splash screen shows up in screen #1 while the game is running on screen #2, how can I set up Splash Screen to always shows in Screen#2?

**Comment by darklinkpower** [comment]
The splash screen window will display in the current main screen in your PC, I assume that's number 1 for you? If that's the case then I or someone else would need to look and see how it can be displayed in the non primary screen.

**Comment by JFERDZ** [comment]
have it show on the second screen or give the user the option to choose where to show it, that would be great!

I really don't know if this requires opening another topic, but being able to control the time SplashScreen takes to make the transition between Playnite and the emulators would also be a wonderful addition.

**Comment by JFERDZ** [comment]
have it show on the second screen or give the user the option to choose where to show it, that would be great!

I really don't know if this requires opening another topic, but being able to control the time SplashScreen takes to make the transition between Playnite and the emulators would also be a wonderful addition.

**Comment by R91g** [comment]
Hi,
I have a monitor as my first screen and a television as my second screen. I play the games in the second screen.
I run Playnite in Fullscreen mode on the second screen but splash screen shows the splash on the first screen

**Comment by KuroZantetsuken** [comment]
I also have the splash screen show on the wrong monitor. Would be nice to be able to pick manually.
