### ISSUE TITLE
[Steam Screenshots] Fullscreen Theme ListView support

### ISSUE THREAD

**Issue by saVantCZ** [darklinkpower/PlayniteExtensionsCollection#544]
### Extension name

Steam Screenshots

### Feature Description

Is it possible to expose plugin for fullscreen theme without using contentcontrol?
What i am asking is to use ListView ItemsSource="{PluginSettings Plugin=SteamScreenshots, Path=Screenshots}" with screenshot collection list
and ItemContainerStyle something like Image Source="{Binding Image}"

Just like how Screenshot Visualzer plugin works. Thanks

**Comment by darklinkpower** [comment]
Support added by binding to the control `Context.ScreenshotsBitmapImages` property, let me know if works fine for you: https://github.com/darklinkpower/PlayniteExtensionsCollection/wiki/Steam-Screenshots#custom-styling-support

**Comment by saVantCZ** [comment]
I am sorry, i could not get it work

System.Windows.Data Error: 40 : BindingExpression path error: 'ScreenshotsBitmapImages' property not found on 'object' ''SteamScreenshotsControl' (Name='')'. BindingExpression:Path=Content.ScreenshotsBitmapImages; DataItem='ContentControl' (Name='SteamScreenshots_SteamScreenshotsViewControl'); target element is 'ListView' (Name='ScreenshotsList'); target property is 'ItemsSource' (type 'IEnumerable')

my code is

`<ListView x:Name="ScreenshotsList"  ScrollViewer.HorizontalScrollBarVisibility="Disabled" Tag="{DynamicResource MediaScreenshots}"
                                                                              VirtualizingPanel.IsVirtualizing="True" VirtualizingPanel.VirtualizationMode="Recycling"  BorderBrush="Transparent" BorderThickness="0" Background="Transparent" 
                                                                              FocusVisualStyle="{x:Null}" Focusable="False" AlternationCount="10" KeyboardNavigation.DirectionalNavigation="Once" ItemsSource="{Binding ElementName=SteamScreenshots_SteamScreenshotsViewControl, Path=Content.ScreenshotsBitmapImages}">
                                            <ListView.Style>
                                                <Style TargetType="ListView">
                                                    <Setter Property="Visibility" Value="Collapsed"/>
                                                    <Setter Property="Template">
                                                        <Setter.Value>
                                                            <ControlTemplate TargetType="{x:Type ListBox}">
                                                                <ScrollViewer CanContentScroll="False" HorizontalScrollBarVisibility="Hidden">
                                                                    <VirtualizingStackPanel x:Name="StackPanel" IsItemsHost="True" Orientation="Horizontal" HorizontalAlignment="Left"/>
                                                                </ScrollViewer>
                                                            </ControlTemplate>
                                                        </Setter.Value>
                                                    </Setter>
                                                    <Style.Triggers>
                                                        <DataTrigger Binding="{PluginSettings Plugin=ScreenshotsVisualizer, Path=HasData}" Value="False">
                                                            <Setter Property="Visibility" Value="Collapsed"/>
                                                        </DataTrigger>
                                                        <MultiDataTrigger>
                                                            <MultiDataTrigger.Conditions>
                                                                <Condition Binding="{Binding RelativeSource={RelativeSource Self}, Path=Tag}" Value="True"/>
                                                                <Condition Binding="{Binding ElementName=PART_ElemGameDetails, Path=Visibility}" Value="Visible"/>
                                                            </MultiDataTrigger.Conditions>
                                                            <MultiDataTrigger.Setters>
                                                                <Setter Property="Visibility" Value="Visible"/>
                                                            </MultiDataTrigger.Setters>
                                                        </MultiDataTrigger>
                                                    </Style.Triggers>
                                                </Style>
                                            </ListView.Style>

                                            <ListView.ItemContainerStyle>
                                                <Style TargetType="ListViewItem">
                                                    <Setter Property="Visibility" Value="Collapsed"/>
                                                    <Setter Property="FocusVisualStyle" Value="{x:Null}"/>
                                                    <Setter Property="Focusable" Value="True"/>
                                                    <Setter Property="Template">
                                                        <Setter.Value>
                                                            <ControlTemplate TargetType="ListViewItem">
                                                                <Grid x:Name="ScreenshotItem" Width="370" Height="210" Margin="16">
                                                                    <Border BorderBrush="Transparent" CornerRadius="15">
                                                                        <Grid>
                                                                            <Border Name="mask" CornerRadius="15" Margin="1" Background="Black"/>
                                                                            <Grid>
                                                                                <Grid.OpacityMask>
                                                                                    <VisualBrush Visual="{Binding ElementName=mask}"/>
                                                                                </Grid.OpacityMask>
                                                                                <Image x:Name="Image" RenderOptions.BitmapScalingMode="LowQuality"/>
                                                                            </Grid>
                                                                        </Grid>
                                                                    </Border>
                                                                    <Border x:Name="MainBorder" Opacity="1" BorderThickness="3" CornerRadius="15" Margin="-6" Style="{DynamicResource PS5Border}" Visibility="Hidden" Tag="False">
                                                                        <Border.CacheMode>
                                                                            <BitmapCache EnableClearType="False" 
                                                 RenderAtScale="1" 
                                                 SnapsToDevicePixels="False"/>
                                                                        </Border.CacheMode>
                                                                    </Border>
                                                                    <Border x:Name="FlashBorder" CornerRadius="15" Opacity="1" Margin="0" Style="{DynamicResource PS5Cover}"  Visibility="Hidden" Tag="False">
                                                                        <Border.CacheMode>
                                                                            <BitmapCache EnableClearType="False" 
                                                 RenderAtScale="1" 
                                                 SnapsToDevicePixels="False"/>
                                                                        </Border.CacheMode>
                                                                    </Border>
                                                                </Grid>
                                                                <ControlTemplate.Triggers>
                                                                    <Trigger Property="ListBox.AlternationIndex" Value="0">
                                                                        <Setter Property="Visibility" Value="Visible"/>
                                                                        <Setter Property="Source" TargetName="Image" Value="{Binding}"/>
                                                                    </Trigger>
                                                                    <Trigger Property="ListBox.AlternationIndex" Value="1">
                                                                        <Setter Property="Visibility" Value="Visible"/>
                                                                        <Setter Property="Source" TargetName="Image" Value="{Binding}"/>
                                                                    </Trigger>
                                                                    <Trigger Property="ListBox.AlternationIndex" Value="2">
                                                                        <Setter Property="Visibility" Value="Visible"/>
                                                                        <Setter Property="Source" TargetName="Image" Value="{Binding}"/>
                                                                    </Trigger>
                                                                    <Trigger Property="IsFocused" Value="True">
                                                                        <Setter Property="Visibility" Value="Visible" TargetName="MainBorder" />
                                                                        <Setter Property="Tag" Value="True" TargetName="MainBorder" />
                                                                        <Setter Property="Visibility" Value="Visible" TargetName="FlashBorder" />
                                                                        <Setter Property="Tag" Value="True" TargetName="FlashBorder" />
                                                                    </Trigger>
                                                                    <MultiDataTrigger>
                                                                        <MultiDataTrigger.Conditions>
                                                                            <Condition Binding="{Binding ElementName=PlayTrailer, Path=IsChecked}" Value="True"/>
                                                                            <Condition Binding="{Binding ElementName=PART_ElemGameDetails, Path=Visibility}" Value="Visible"/>
                                                                        </MultiDataTrigger.Conditions>
                                                                        <MultiDataTrigger.EnterActions>
                                                                            <BeginStoryboard>
                                                                                <Storyboard>
                                                                                    <DoubleAnimation Storyboard.TargetProperty="Opacity" Storyboard.TargetName="ScreenshotItem" From="1" To="0" Duration="0:0:0.2" FillBehavior="HoldEnd"/>
                                                                                </Storyboard>
                                                                            </BeginStoryboard>
                                                                        </MultiDataTrigger.EnterActions>
                                                                        <MultiDataTrigger.ExitActions>
                                                                            <BeginStoryboard>
                                                                                <Storyboard>
                                                                                    <DoubleAnimation Storyboard.TargetProperty="Opacity" Storyboard.TargetName="ScreenshotItem" From="0" To="1" Duration="0:0:0.2" FillBehavior="HoldEnd"/>
                                                                                </Storyboard>
                                                                            </BeginStoryboard>
                                                                        </MultiDataTrigger.ExitActions>
                                                                    </MultiDataTrigger>
                                                                </ControlTemplate.Triggers>
                                                            </ControlTemplate>
                                                        </Setter.Value>
                                                    </Setter>
                                                </Style>
                                            </ListView.ItemContainerStyle>
                                        </ListView>`

**Comment by darklinkpower** [comment]
Do you have the full source code available? At least from that snippet it looks correct. I also just tried this and it works fine:

```xml
<ListView x:Name="ScreenshotsList"  ScrollViewer.HorizontalScrollBarVisibility="Disabled" Tag="{DynamicResource MediaScreenshots}"
            VirtualizingPanel.IsVirtualizing="True"
            VirtualizingPanel.VirtualizationMode="Recycling"
            BorderBrush="Transparent" BorderThickness="0" Background="Transparent"
            FocusVisualStyle="{x:Null}" Focusable="False" AlternationCount="10" KeyboardNavigation.DirectionalNavigation="Once" ItemsSource="{Binding ElementName=SteamScreenshots_SteamScreenshotsViewControl, Path=Content.ScreenshotsBitmapImages}">
    <ListView.View>
        <GridView>
            <GridViewColumn Header="Image">
                <GridViewColumn.CellTemplate>
                    <DataTemplate>
                        <Image Source="{Binding}" RenderOptions.BitmapScalingMode="Fant" Height="100" Margin="5"/>
                    </DataTemplate>
                </GridViewColumn.CellTemplate>
            </GridViewColumn>
        </GridView>
    </ListView.View>
</ListView>
```

Are you sure you have updated to the latest version with this implemented?


---

As a tip, you can format and display the code here by adding 3 backtick ( ` ) characters, followed by the language, then ending the code block again with 3 backticks and it will display like above:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/878942fc-50d6-4c23-9722-12a1d5d0f561)

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/cd36b330-6b75-4100-8034-4af813d378f4)

**Comment by saVantCZ** [comment]
Yes it is working now, but i have small problem with Alternation Count, sometimes it shows indeed 3 items and sometimes it loads all of them and ignore visibility based on alternation

```xml
 <ContentControl x:Name="SteamScreenshots_SteamScreenshotsViewControl" Visibility="Collapsed" />

                                        <ListView x:Name="ScreenshotsList"  ScrollViewer.HorizontalScrollBarVisibility="Disabled" Tag="{DynamicResource MediaScreenshots}"
                                                                              VirtualizingPanel.IsVirtualizing="True" VirtualizingPanel.VirtualizationMode="Recycling"  BorderBrush="Transparent" BorderThickness="0" Background="Transparent" 
                                                                              FocusVisualStyle="{x:Null}" Focusable="False" AlternationCount="10" KeyboardNavigation.DirectionalNavigation="Once" ItemsSource="{Binding ElementName=SteamScreenshots_SteamScreenshotsViewControl, Path=Content.ScreenshotsBitmapImages}">
                                            <ListView.Style>
                                                <Style TargetType="ListView">
                                                    <Setter Property="Visibility" Value="Collapsed"/>
                                                    <Setter Property="Template">
                                                        <Setter.Value>
                                                            <ControlTemplate TargetType="{x:Type ListBox}">
                                                                <ScrollViewer CanContentScroll="False" HorizontalScrollBarVisibility="Hidden">
                                                                    <VirtualizingStackPanel x:Name="StackPanel" IsItemsHost="True" Orientation="Horizontal" HorizontalAlignment="Left"/>
                                                                </ScrollViewer>
                                                            </ControlTemplate>
                                                        </Setter.Value>
                                                    </Setter>
                                                    <Style.Triggers>
                                                        <MultiDataTrigger>
                                                            <MultiDataTrigger.Conditions>
                                                                <Condition Binding="{Binding RelativeSource={RelativeSource Self}, Path=Tag}" Value="True"/>
                                                                <Condition Binding="{Binding ElementName=PART_ElemGameDetails, Path=Visibility}" Value="Visible"/>
                                                            </MultiDataTrigger.Conditions>
                                                            <MultiDataTrigger.Setters>
                                                                <Setter Property="Visibility" Value="Visible"/>
                                                            </MultiDataTrigger.Setters>
                                                        </MultiDataTrigger>
                                                    </Style.Triggers>
                                                </Style>
                                            </ListView.Style>

                                            <ListView.ItemContainerStyle>
                                                <Style TargetType="ListViewItem">
                                                    <Setter Property="Visibility" Value="Collapsed"/>
                                                    <Setter Property="FocusVisualStyle" Value="{x:Null}"/>
                                                    <Setter Property="Focusable" Value="True"/>
                                                    <Setter Property="Template">
                                                        <Setter.Value>
                                                            <ControlTemplate TargetType="ListViewItem">
                                                                <Grid x:Name="ScreenshotItem" Width="370" Height="210" Margin="16">
                                                                    <Border BorderBrush="Transparent" CornerRadius="15">
                                                                        <Grid>
                                                                            <Border Name="mask" CornerRadius="15" Margin="1" Background="Black"/>
                                                                            <Grid>
                                                                                <Grid.OpacityMask>
                                                                                    <VisualBrush Visual="{Binding ElementName=mask}"/>
                                                                                </Grid.OpacityMask>
                                                                                <Image x:Name="Image" RenderOptions.BitmapScalingMode="LowQuality"/>
                                                                            </Grid>
                                                                        </Grid>
                                                                    </Border>
                                                                    <Border x:Name="MainBorder" Opacity="1" BorderThickness="3" CornerRadius="15" Margin="-6" Style="{DynamicResource PS5Border}" Visibility="Hidden" Tag="False">
                                                                        <Border.CacheMode>
                                                                            <BitmapCache EnableClearType="False" 
                                                 RenderAtScale="1" 
                                                 SnapsToDevicePixels="False"/>
                                                                        </Border.CacheMode>
                                                                    </Border>
                                                                    <Border x:Name="FlashBorder" CornerRadius="15" Opacity="1" Margin="0" Style="{DynamicResource PS5Cover}"  Visibility="Hidden" Tag="False">
                                                                        <Border.CacheMode>
                                                                            <BitmapCache EnableClearType="False" 
                                                 RenderAtScale="1" 
                                                 SnapsToDevicePixels="False"/>
                                                                        </Border.CacheMode>
                                                                    </Border>
                                                                </Grid>
                                                                <ControlTemplate.Triggers>
                                                                    <Trigger Property="ListBox.AlternationIndex" Value="0">
                                                                        <Setter Property="Visibility" Value="Visible"/>
                                                                        <Setter Property="Source" TargetName="Image" Value="{Binding}"/>
                                                                    </Trigger>
                                                                    <Trigger Property="ListBox.AlternationIndex" Value="1">
                                                                        <Setter Property="Visibility" Value="Visible"/>
                                                                        <Setter Property="Source" TargetName="Image" Value="{Binding}"/>
                                                                    </Trigger>
                                                                    <Trigger Property="ListBox.AlternationIndex" Value="2">
                                                                        <Setter Property="Visibility" Value="Visible"/>
                                                                        <Setter Property="Source" TargetName="Image" Value="{Binding}"/>
                                                                    </Trigger>
                                                                    <Trigger Property="IsFocused" Value="True">
                                                                        <Setter Property="Visibility" Value="Visible" TargetName="MainBorder" />
                                                                        <Setter Property="Tag" Value="True" TargetName="MainBorder" />
                                                                        <Setter Property="Visibility" Value="Visible" TargetName="FlashBorder" />
                                                                        <Setter Property="Tag" Value="True" TargetName="FlashBorder" />
                                                                    </Trigger>
                                                                    <MultiDataTrigger>
                                                                        <MultiDataTrigger.Conditions>
                                                                            <Condition Binding="{Binding ElementName=PlayTrailer, Path=IsChecked}" Value="True"/>
                                                                            <Condition Binding="{Binding ElementName=PART_ElemGameDetails, Path=Visibility}" Value="Visible"/>
                                                                        </MultiDataTrigger.Conditions>
                                                                        <MultiDataTrigger.EnterActions>
                                                                            <BeginStoryboard>
                                                                                <Storyboard>
                                                                                    <DoubleAnimation Storyboard.TargetProperty="Opacity" Storyboard.TargetName="ScreenshotItem" From="1" To="0" Duration="0:0:0.2" FillBehavior="HoldEnd"/>
                                                                                </Storyboard>
                                                                            </BeginStoryboard>
                                                                        </MultiDataTrigger.EnterActions>
                                                                        <MultiDataTrigger.ExitActions>
                                                                            <BeginStoryboard>
                                                                                <Storyboard>
                                                                                    <DoubleAnimation Storyboard.TargetProperty="Opacity" Storyboard.TargetName="ScreenshotItem" From="0" To="1" Duration="0:0:0.2" FillBehavior="HoldEnd"/>
                                                                                </Storyboard>
                                                                            </BeginStoryboard>
                                                                        </MultiDataTrigger.ExitActions>
                                                                    </MultiDataTrigger>
                                                                </ControlTemplate.Triggers>
                                                            </ControlTemplate>
                                                        </Setter.Value>
                                                    </Setter>
                                                </Style>
                                            </ListView.ItemContainerStyle>
                                        </ListView>```

**Comment by saVantCZ** [comment]
Oh my bad, i forgot to set Alternation Count higher instead of 10. 
Thank you for your help and amazing job on playnite plugins!
