### ISSUE TITLE
[Steam Screenshots] Game details autoscrolling

### ISSUE THREAD

**Issue by Bobodemon** [darklinkpower/PlayniteExtensionsCollection#547]
### Extension name

Steam Screenshots

### Bug Description

After installing the Steam Screenshots extension, my game details automatically scroll down every time I select a game. Is there a way to prevent this? I am using Helium theme. Thanks.

### To Reproduce

Selecting a game makes game details scroll down with Steam Screenshots installed using Helium theme.

### Logs

[playnite.log](https://github.com/user-attachments/files/15517131/playnite.log)
[extensions.log](https://github.com/user-attachments/files/15517132/extensions.log)

**Comment by darklinkpower** [comment]
Fix will be available in next update.
