### ISSUE TITLE
[Steam Screenshots] The addon doesn't find screenshots for "Age Of Empires II Definitive Edition"

### ISSUE THREAD

**Issue by HerrKnarz** [darklinkpower/PlayniteExtensionsCollection#550]
### Extension name

Steam Screenshots

### Bug Description

The extension finds screenshots for allmost all games in my library, if they have a steam link assigned, but for some reason none are found for "Age Of Empires II Definitive Edition". The game has a steam link and is from the steam library addon. I know that games not available in my country aren't found, but that's not the case with this game.

The link I have to the game is this one: https://store.steampowered.com/app/813780

It's no big deal, if some games are missing, but maybe it's an indication for something probably affecting others as well.

### To Reproduce

Have "Age Of Empires II Definitive Edition" in your library, add a link to its steam page and see if the steam screenshots addon finds any shots.

### Logs

[extensions.log](https://github.com/user-attachments/files/15525069/extensions.log)
[playnite.log](https://github.com/user-attachments/files/15525070/playnite.log)

**Comment by darklinkpower** [comment]
Can't reproduce, working fine for me:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/4baf0f01-4c90-452d-9aec-88b095b6d4f4)

Can you check if your links doesn't have spaces at the start or end of the url in Playnite?

And if this file exists here, upload it here:

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/841774e1-ae8a-4bce-bcdc-c5b849f37321)

![image](https://github.com/darklinkpower/PlayniteExtensionsCollection/assets/1389286/a0db44a2-ac2c-487f-b720-de730eb59151)


`813780_appdetails.json`

**Comment by HerrKnarz** [comment]
Sorry for the late reply. The link is exactly the same as yours and has no spaces anywhere. I found the file and attached it. It simply says success:false, though.
[813780_appdetails.json](https://github.com/user-attachments/files/15747339/813780_appdetails.json)

I now deleted the file and checked the game again in Playnite. This time the screenshots are found. Do you use the files to cache data? Maybe steam just was acting up the moment it tried to get the screenshots and the addon didn't try again because of the success status in the file. A function to force a new API call to get the screenshots would be a good idea for cases like this, I guess. Or automatically fetch the data again from steam, if the file is a few days old, so newly added screenshots will also be displayed.

**Comment by darklinkpower** [comment]
Measures to fix this implemented in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/3ee49a755bea00ff09f545be8d6b61972ff3de24 and https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/bd6d9625c3851113a8912516284930603d0c0c1c
