### ISSUE TITLE
[Review Viewer] DialogResultsDataRefreshFinishedMessage not outputing

### ISSUE THREAD

**Issue by Jhanlon95** [darklinkpower/PlayniteExtensionsCollection#56]
**Extension**
Review Viewer

**Describe the bug**
When updating the review data on a title the dialog window's text outputs the variable name instead of the correct message

**To Reproduce**
Right click on a game -> Review Viewer -> Update data -> select "No" to download data for games that already have it

**Expected behavior**
Output a clear message 

**Screenshots**
![image](https://user-images.githubusercontent.com/11045596/134337641-06cd30fe-09bf-4048-9d15-c7e225916e7d.png)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/9eb3316bf3f49da9e2ea91431c83d6b7c932022f
