### ISSUE TITLE
Extra Metadata Loader

### ISSUE THREAD

**Issue by Mike-Aniki** [darklinkpower/PlayniteExtensionsCollection#562]
### Extension name

Downloading videos from youtube no longer works

### Feature Description

Youtube has changed something in its api which has blocked all software that recupere video from youtube (4K Video Downloader , smartube ,freetube , ect...) the video displays an error 403 , most of the software have updated and fixed this error . 

I've just done a test with extra metadata Loader and it's that downloading videos from youtube no longer works.

**Comment by zeroantix** [comment]
I believe downloading the latest version of **yt-dlp** (yt-dlp 2024.07.09 as of the time of commenting) fixes this issue, at least it did for me.

Example:
![image](https://github.com/user-attachments/assets/22970e72-a2ad-4484-b966-f77cdee0c7c9)

**Comment by Mike-Aniki** [comment]
Indeed with the latest update of yt-dlp it works, I had not seen that yt-dlp had been updated last week (yt-dlp 2024.07.09). Thank u
