### ISSUE TITLE
[Steam Wishlist Discount Notifier] Games missing

### ISSUE THREAD

**Issue by Supernaz** [darklinkpower/PlayniteExtensionsCollection#565]
### Extension name

Steam Wishlist Discount Notifier

### Bug Description

Hi,

I noticed that several games were missing from the list displayed by the add-on.
I currently have 337 games in my whishlist.
But the add-on only displays 300 games.

Edit : I may have an answer. 
The games with a visible discount (-10%, -20% etc) are displayed.
The games with not visible discount ("SPECIAL PROMOTION" i think) are not displayed.

### Logs

f858cce1-66d3-46e5-9ddf-512b327630e9

### Screenshots

<img width="160" alt="Capture d’écran 2024-07-28 112353" src="https://github.com/user-attachments/assets/fb2e37f1-47b1-49aa-ba0c-388046fefcd2">

<img width="747" alt="Capture d’écran 2024-07-28 112507" src="https://github.com/user-attachments/assets/af1fe736-9ee8-4d58-beb1-b3832a66f713">

<img width="395" alt="Capture d’écran 2024-07-28 112527" src="https://github.com/user-attachments/assets/64a04b4a-2764-4eaa-abf7-db7857b405c2">

<img src="https://i.ibb.co/y8YvKXZ/Capture-d-cran-2024-07-28-121001.jpg">

**Comment by darklinkpower** [comment]
I think that display formatting is only available in European countries, or at least it's not available here in Mexico. Can you go to the wishlist page in a browser and save the page using `Ctrl+S` and upload the `html` file to examine it?

**Comment by Supernaz** [comment]
> I think that display formatting is only available in European countries, or at least it's not available here in Mexico. Can you go to the wishlist page in a browser and save the page using `Ctrl+S` and upload the `html` file to examine it?

I no longer get this strange display on my steam whishlist page (i'm french).
Everything's back to normal now, and your plug-in is displaying my entire wishlist.
Thank you !
