### ISSUE TITLE
[Steam Store Screenshots Viewer] Add an option to disable automatic screenshot refresh every 12 days and make it possible to refresh manually.

### ISSUE THREAD

**Issue by poetickatana** [darklinkpower/PlayniteExtensionsCollection#572]
### Extension name

Steam Store Screenshots Viewer

### Feature Description

From the 1.6 update:
> Changed: Screenshots will be refreshed each 12 days after the initial download to help in cases where screenshots have been changed or updated

It doesn't really matter to me if the screenshots in Playnite are slightly out of sync with those on Steam and I don't like the idea of Playnite silently downloading large amounts of image data from Steam every 12 days.

Would it be possible to make this feature optional? Instead, maybe add an option to refresh the Steam screenshots for selected games manually.

**Comment by darklinkpower** [comment]
uhh why was this created and then closed?

> and I don't like the idea of Playnite silently downloading large amounts of image data from Steam every 12 days.

Images are already downloaded in the background when data is first obtained, nothing is changing in regard to that. Only thing that is downloaded is new found screenshots, if there are any.
