### ISSUE TITLE
[Fullscreen Mode] Sorting based on Recently Added

### ISSUE THREAD

**Issue by ahmedusmanshahid** [darklinkpower/PlayniteExtensionsCollection#580]
### Extension name

Full screen mode sorting

### Feature Description

Fullscreen mode should allow sorting based on recently or newly added. it will give playnite a playstation like feel.
also the regular version should support this as well (cant find any actual option in desktop version)

**Comment by ahmedusmanshahid** [comment]
it can be done be done via filter panel. press RS on controller to open it in fullscreen mode

**Comment by darklinkpower** [comment]
I think you got confused and posted this in the wrong place. This repository is for extensions I develop. The Playnite repository is over at https://github.com/JosefNemec/Playnite
