### ISSUE TITLE
[Details to grid view converter] Text in settings describing 

### ISSUE THREAD

**Issue by Jeshibu** [darklinkpower/PlayniteExtensionsCollection#583]
### Extension name

Details to grid view converter

### Feature Description

An extremely common followup question for users of Details to grid view converter is: how do I make the grid view details panel bigger?
It would probably help a lot of users if a short pointer to where to find that was added to the settings.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/47394fedbb3783c5fa3dc424afc1ca47e7689cd4
