### ISSUE TITLE
Steam Screenshots extension low resolution screenshots 

### ISSUE THREAD

**Issue by STOPchris1** [darklinkpower/PlayniteExtensionsCollection#584]
### Extension name

Steam Screenshots

### Bug Description

Is there any way to get high resolution screenshots? I am using the PS5reborn full screen theme and the screenshots look low resolution when displayed in full screen. Is there a way to increase the resolution using this extension or another way?

**Comment by saVantCZ** [comment]
Plugin would need to expose Binding for fullscreen steam images.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/211ba47da5c9de863163f92bc0c3788a3abf82fd, now themes need to implement support for it.
