### ISSUE TITLE
[Steam Screenshots] Expose Full resolution images binding for Fullscreen Theme

### ISSUE THREAD

**Issue by saVantCZ** [darklinkpower/PlayniteExtensionsCollection#586]
### Extension name

Steam Screenshots

### Feature Description

Possibility to view full resolution images in ListView for fullscreen themes, plugin only expose thumbnails.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/211ba47da5c9de863163f92bc0c3788a3abf82fd

Here's a test build: 

[SteamScreenshots_8e77fe31-5e62-41e2-8fa2-64844cfd5b6b_1_8.zip](https://github.com/user-attachments/files/17729166/SteamScreenshots_8e77fe31-5e62-41e2-8fa2-64844cfd5b6b_1_8.zip)


Rename zip extension to pext to install. Property exposed as `ScreenshotsFullBitmapImages`.

---

Using the occasion, would you be interested in trying testing a new plugin integration? It's to add a web view to Playnite. It worked fine on my end but not sure if it's good to go or something is missing.

[WebExplorer_181ddd05-2168-4162-a116-b9c2a20c652c_1_0.zip](https://github.com/user-attachments/files/17729184/WebExplorer_181ddd05-2168-4162-a116-b9c2a20c652c_1_0.zip)


![Playnite DesktopApp_egh0nZAKto](https://github.com/user-attachments/assets/0b481483-d3de-46dd-bb40-fe0983444406)
![Playnite FullscreenApp_Jh40DVB3z3](https://github.com/user-attachments/assets/c87efece-5323-467d-9e5d-b9094b1e28ca)


Here's a tutorial if you are interested: https://github.com/darklinkpower/PlayniteExtensionsCollection/wiki/Web-Explorer#integration-of-custom-controls-in-custom-themes

**Comment by saVantCZ** [comment]
Wow this is amazing, will definitely try on my fullscreen theme.

Thanks for fast response, will test steam screenshots as soon as i get to my PC

**Comment by saVantCZ** [comment]
Seems like ItemsSource="{Binding ElementName=SteamScreenshots_SteamScreenshotsViewControl, Path=Content.ScreenshotsFullBitmapImages}"> doesnt work, Content.ScreenshotsBitmapImages works as usual, showing thumbnails.

**Comment by darklinkpower** [comment]
I got this email but the actual message is not here anymore. Is it still an issue?

![image](https://github.com/user-attachments/assets/49df817f-8b08-410b-a3f5-2a813bc99573)

**Comment by saVantCZ** [comment]
My mistake, i was testing it on my portable instance without updated extension instead of my main build.

All works good, just noticed that thumbnail and fullres are not in sync. I am using listview with alternations to show 1st, 2nd and 3rd screenshot thumbnails and when focused on these, another listview became visible with same alternations 1 to 3, but shows different images. Even after clearing screenshots cache and its quite random, some games are in sync with both thumbnails and full, some are scrambled. 

But i fixed this by using itemsource from one listview in second one and render fullres images smaller in thumb view.

**Comment by darklinkpower** [comment]
The randomness issue should be fixed with https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/ac61740cb9c8c1ee77360518edfca324dee8fdd4. However, in my opinion, if you're going to display the high-resolution images anyway, it makes more sense to skip the low-resolution ones entirely. Since all the high-resolution images are being loaded, loading both types simultaneously will only slow things down.

**Comment by saVantCZ** [comment]
Should be fine once cache is created. But I will rewrite code anyway if randomness is fixed, thanks

**Comment by darklinkpower** [comment]
Closing as completed.
