### ISSUE TITLE
[Special K Helper] Special K service won't start since plugin version 1.34

### ISSUE THREAD

**Issue by yan-bibiyan** [darklinkpower/PlayniteExtensionsCollection#588]
### Extension name

Special K Helper

### Bug Description

In versions 1.34+ of the plugin the Special K services won't start automatically when I start a game. I double checked the settings and did a lot of updating / rolling back - version 1.33 works with no issues whatsoever, but none of the subsequent up to and including 1.36 do.

### Logs

[extensions.log](https://github.com/user-attachments/files/17783627/extensions.log)
[playnite.log](https://github.com/user-attachments/files/17783628/playnite.log)

**Comment by darklinkpower** [comment]
What happens if you right click the sidebar icon and click here?

![image](https://github.com/user-attachments/assets/ac0b66dd-597a-4a86-99bf-34e6e4a497e5)

If services start successfully it should look like this:

![image](https://github.com/user-attachments/assets/624f4b20-13f6-41e5-a364-d6c10f416a6a)

**Comment by yan-bibiyan** [comment]
Restarted PC, started Playnite:
![Screenshot 2024-11-16 075752](https://github.com/user-attachments/assets/5ff63d64-d40c-47f6-909c-fe87debdd6eb)
<img width="311" alt="2024-11-16 07_58_12-Special K" src="https://github.com/user-attachments/assets/6fc7d3ef-154e-48f0-b56a-3fd5d9d59019">


Started a game, the game is running:
![Screenshot 2024-11-16 075850](https://github.com/user-attachments/assets/36dbb05c-37b9-4afb-a6da-e8734588af2c)
<img width="311" alt="2024-11-16 07_59_04-Special K" src="https://github.com/user-attachments/assets/d6bf5670-d967-4ab4-a8d6-04f848e08d99">


After I quit the game:
![Screenshot 2024-11-16 075927](https://github.com/user-attachments/assets/c8c2c6f5-9736-4aec-9d71-772b427ed5d1)
<img width="311" alt="2024-11-16 07_59_38-Special K" src="https://github.com/user-attachments/assets/b06f6f3e-fd61-4311-93eb-77adc14e81f2">

Thanks for looking into this, hope this helps - let me know if I can provide you with any other info.

**Comment by darklinkpower** [comment]
I've released v1.37 that should have fixed the issue. If the issue is still there after updating please upload the extensions.log file.

**Comment by yan-bibiyan** [comment]
I can confirm the issue is fixed in v1.37 and everything works as expected. Thank you for looking into this, and overall for the effort to create and maintain this great collection of extensions.
