### ISSUE TITLE
[Special K Helper] Special K Helper Failing to load

### ISSUE THREAD

**Issue by Backnard** [darklinkpower/PlayniteExtensionsCollection#589]
### Extension name

Special K Helper

### Bug Description

Special K Helper is failing to load after updating to 1.37

### To Reproduce

Fails to load when Playnite starts

### Logs

[playnite.log](https://github.com/user-attachments/files/17788429/playnite.log)
[extensions.log](https://github.com/user-attachments/files/17788430/extensions.log)

**Comment by darklinkpower** [comment]
Can you upload your config.json file from here?

![image](https://github.com/user-attachments/assets/66420528-6c3b-46ce-8d6c-d04ba30c1d59)

**Comment by Dim0N22** [comment]
I have the same problem with the latest Special K Helper version. My config file: [config.json](https://github.com/user-attachments/files/17788829/config.json).

**Comment by darklinkpower** [comment]
I've released a new version v1.38 that fixes the issue.

**Comment by Backnard** [comment]
Thank you @darklinkpower! I can confirm1.38 fixes the issue for me as well.
