### ISSUE TITLE
[Steam Store Screenshots Viewer] Crashes at Metro 2033 game detail page.

### ISSUE THREAD

**Issue by MILES-FAN** [darklinkpower/PlayniteExtensionsCollection#591]
### Extension name

Steam Store Screenshots Viewer

### Bug Description

Crashes at Metro 2033 game detail page. 

### To Reproduce

(Tried Helium and Stardust, Helium instant crashes, Stardust crashes when select Screenshots tab.)
![Stardust_crash](https://github.com/user-attachments/assets/4ac917c9-073c-40c3-ae5e-30db0d9d611e)

### Logs

[extensions.log](https://github.com/user-attachments/files/17907524/extensions.log)
[playnite.log](https://github.com/user-attachments/files/17907526/playnite.log)

### Screenshots

![Stardust_crash](https://github.com/user-attachments/assets/4ac917c9-073c-40c3-ae5e-30db0d9d611e)

**Comment by darklinkpower** [comment]
Hi, based on the logs, it looks like there's an issue related to image rendering. The key part of the error is:

> この処理を完了するために必要なイメージング コンポーネントが見つかりませんでした。 ---> System.Runtime.InteropServices.COMException: コンポーネントが見つかりません。 (HRESULT からの例外:0x88982F50)

Which translated is:

> Could not find the imaging component needed to complete this operation. ---> COMException: component not found. (Exception from HRESULT: 0x88982F50)

This usually occurs when the system cannot find a component needed for functionality or when it's corrupted. This could indicate that something in your system might be broken.

I'm not too sure how to go about trying to fix this other than general steps to fix your system but I suggest to try the following:

1. Run a system scan: Open Command Prompt as Administrator, then type `sfc /scannow` and press Enter. This will check for and fix any missing or corrupted system files.
2. Try repairing system components: If the first scan doesn’t help, try running this in Command Prompts: `DISM /Online /Cleanup-Image /ScanHealth` and `DISM /Online /Cleanup-Image /RestoreHealth`
3. Try repairing .Net framework installation: https://dotnet.microsoft.com/en-us/download/dotnet-framework

Also what Windows version are you using? And is it any of the custom Windows builds that change the Operating System by any chance?

**Comment by MILES-FAN** [comment]
Thank you for your reply. I have a very typical new installation of Windows 11. In addition, I've noticed that the crashing issue only occurs on the game detail page for Metro 2033, all other game detail pages are fine. I'll try to see if I can reproduce the problem on my laptop next.

System information:
Windows 11 23H2
Install date ‎2024/‎9/‎2
OS build	22631.4541

.Net Version:
CBS           : 1
Install       : 1
InstallPath   : C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
Release       : 533320
Servicing     : 0
TargetVersion : 4.0.0
Version       : 4.8.09032
PSPath        : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
PSParentPath  : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4
PSChildName   : Full
PSDrive       : HKLM
PSProvider    : Microsoft.PowerShell.Core\Registry

**Comment by MILES-FAN** [comment]
![Snipaste_2024-11-27](https://github.com/user-attachments/assets/c47432ff-187e-43be-bf9c-f4958b48cc57)
Problem solved by deleting a corrupted image from ScreenshotsCache folder. Here is a corrupted image (0 byte) I found in ScreenshotsCache folder.
[corrupted image.zip](https://github.com/user-attachments/files/17930649/corrupted.image.zip)
Replace any cache with this corrupted image can reproduce problem.

**Comment by darklinkpower** [comment]
Thanks for the info. It looks like a file didn't complete its download, I'll implement measures to prevent this.

**Comment by darklinkpower** [comment]
I've made some changes to prevent this crash:

- Incomplete downloads will not be placed in the previous final path until the download finishes (https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/dd9c03c42269bb9874875ceb27eaed05ac441687)
- I also took the opportunity to rewrite the extension and made it more resilient to errors in the process (https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/5598396cba11aadbf74a498495daf281b0bd2ab3). If the downloaded image is still invalid for some reason, the extension will now handle the error gracefully
