### ISSUE TITLE
[PlayState] PlayState incorrectly considers GOG Galaxy 2.0 as the launched game and doesn't detect the actual game that is running

### ISSUE THREAD

**Issue by Rudolf-Snail** [darklinkpower/PlayniteExtensionsCollection#596]
### Extension name

PlayState

### Bug Description

When I launch my GOG copy of Shadow Tactics: Blades of the Shogun the PlayState extension doesn't pause the game when I switch the active window (alt-tab) or use the shortcut for pausing the state.  However the extension correctly notifies me and claims that the PlayState is changed in these instances. 
After some experimentation and testing I found that the extension works fine on my installed Steam games. After further testing I realized that PlayState actually pauses the GOG Galaxy client when I'm playing Shadow Tactics instead of the game. Adding all the GOG processes I could find running in Task Manager to the scan exclusion list in the PlayState extension  —
_GalaxyClient Helper Application (32 bit)
GOG Galaxy (32 bit)
GOG Galaxy Notifications Renderer (32 bit)
GalaxyCommunicationService (32 bit)_
—  didn't fix this issue.
I could configure the GOG integration, so that it doesn't launch games using GOG Galaxy client, and that would probably fix this issue, but then I wouldn't be able to track the game time for my GOG games or get achievements.

### Logs

[extensions.log](https://github.com/user-attachments/files/18142658/extensions.log)
[playnite.log](https://github.com/user-attachments/files/18142659/playnite.log)

**Comment by darklinkpower** [comment]
It looks like the problem is because the executable you are launching is GOG Galaxy executable:

```
16-12 00:21:13.016|DEBUG|ProcessStarter:Starting process: C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe, /launchViaAutostart /gameId=1601442230 /command=runGame /path="D:\Gaming\GOG\Shadow Tactics - Blades of the Shogun\", , False
```

This makes the extension to scan in the executable directory `C:\Program Files (x86)\GOG Galaxy`.

I'm really confused what's your setup here because this shouldn't happen in normal circumstances. My guess is that you manually configured the game Play action, under  Edit -> Play Actions like that but I'm not sure. There's no mention at all of the GOG Library plugin starting the game so that's my guess, because if it was used it should be between these two lines:

```
16-12 00:21:13.134|DEBUG|SteamLibrary#SteamLibrary:Found 4 installed Steam games.
16-12 00:21:15.496|DEBUG|SteamLibrary#SteamLibrary:Found 589 library Steam games.
```

Please tell me how the game was imported and share screenshots of the game Installation and Play Action tabs.

**Comment by Rudolf-Snail** [comment]
> It looks like the problem is because the executable you are launching is GOG Galaxy executable:
> 
> ```
> 16-12 00:21:13.016|DEBUG|ProcessStarter:Starting process: C:\Program Files (x86)\GOG Galaxy\GalaxyClient.exe, /launchViaAutostart /gameId=1601442230 /command=runGame /path="D:\Gaming\GOG\Shadow Tactics - Blades of the Shogun\", , False
> ```
> 
> This makes the extension to scan in the executable directory `C:\Program Files (x86)\GOG Galaxy`.

I see... I think it's launching it properly by launching the client with the path of the game as an argument, but I see how it creates a problem for the PlayState extension, which expects a different behavior.

> I'm really confused what's your setup here because this shouldn't happen in normal circumstances. My guess is that you manually configured the game Play action, under Edit -> Play Actions like that but I'm not sure. There's no mention at all of the GOG Library plugin starting the game so that's my guess, because if it was used there should be a log line from the GOG plugin between these two lines:
> 
> ```
> 16-12 00:21:12.677|DEBUG|OriginLibrary#OriginLibrary:Found 0 installed EA games.
> 16-12 00:21:13.134|DEBUG|SteamLibrary#SteamLibrary:Found 4 installed Steam games.
> ```
> 
> Please tell me how the game was imported and share screenshots of the game Installation and Play Action tabs.

That's odd, because I'm not aware of changing them, nor do they seem changed.
![Screenshot 2024-12-16 163222](https://github.com/user-attachments/assets/65f9e8ba-c6c5-4a6c-832b-cc9eb52c93bb)
![Screenshot 2024-12-16 163335](https://github.com/user-attachments/assets/47d8908d-13aa-44ca-a777-5b6f9a01bdd5)
![Screenshot 2024-12-16 163559](https://github.com/user-attachments/assets/055abfad-da5f-444e-a13b-043485a0260d)

This is the installation location: `D:\Gaming\GOG\Shadow Tactics - Blades of the Shogun`
![Screenshot 2024-12-16 163535](https://github.com/user-attachments/assets/b73046aa-53d0-4613-ada0-bd10905229ea)

And these are the Playnite settings for the GOG integration:
![Screenshot 2024-12-16 163404](https://github.com/user-attachments/assets/486ba4cc-360e-42c7-b2f3-5135eb5ce27a)

As far as importing the game I'm not sure, but it was likely through the GOG integration, when I was importing GOG games.

**Comment by darklinkpower** [comment]
Thanks. I've identified the issue and fixed it in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/98befb26d37e64b45a9c9d880708498f40ddee43. Update is available.

**Comment by Rudolf-Snail** [comment]
Thanks a lot for the fix!
