### ISSUE TITLE
 Extra Metadata Tools Video crashes

### ISSUE THREAD

**Issue by Deerhall** [darklinkpower/PlayniteExtensionsCollection#64]
**Extension**
Extra Metadata Tools Video

**Describe the bug**
Plugin crashes after null array error.

**To Reproduce**
Rename anything to "Bastion" and attempt to download Steam Trailer HD.
(I could reproduce by adding discord.exe and rename it to "Bastion").
Playnite 9.1

**Expected behavior**
Download the trailer from Steam.

**Screenshots**
https://i.ibb.co/19gpQ76/image.png (Before attempting steam HD download)
https://i.ibb.co/L6cfHwg/image.png (Error message)
https://i.ibb.co/ggcYV63/image.png (After attempting download and getting error)

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/b9c82d3221fb7491e8ec8e920ed4fe53529f64a4
