### ISSUE TITLE
[Importer for Anilist] Failed to import

### ISSUE THREAD

**Issue by Ayokx** [darklinkpower/PlayniteExtensionsCollection#69]
**Extension**
Importer for Anilist

**Describe the bug**
When I update the library it doesn't work and give me an error in the notification area.

**To Reproduce**
Go to Update Library>Importer for Anilist or Update all

**Expected behavior**
My anilist informations being imported to playnite.

**Screenshots**
Error : 
![acpture](https://user-images.githubusercontent.com/92641740/137594451-a1c09325-4ee4-4510-b246-bb65e7d0b0ae.png)

**Additional Informations**
I have the access code typed in the settings. When I erase it, it gives me a different error so I don't think my code is the problem.

**Comment by darklinkpower** [comment]
Fixed in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/e86bf917cabb174259271dbf476ad9340e68b3ce
