### ISSUE TITLE
[Splash Screen] Image on secondary monitor only

### ISSUE THREAD

**Issue by Andei** [darklinkpower/PlayniteExtensionsCollection#72]
**Extension**
Splash Screen

**Describe the bug**
Since 9.4 the splash screen image shows up on my secondary monitor. 

**Expected behavior**
Pic shows up on main 

**Extensions log**
`17-10 20:08:49.849|INFO |SplashScreen#SplashScreen:Game: Deus Ex: Mankind Divided
17-10 20:08:49.849|INFO |SplashScreen#SplashScreen:Found game background image
17-10 20:08:49.853|INFO |SplashScreen#SplashScreen:Specific game logo found in C:\Users\andre\SynologyDrive\Playnite814\ExtraMetadata\games\1aa1c5b0-1b77-4651-b718-91fc9a62d80b\Logo.png `

**Comment by darklinkpower** [comment]
Can you try with this version and see if it's fixed?
[SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_3.zip](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7361037/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_3.zip)

**Comment by Andei** [comment]
It works.
Thank you so much!

**Comment by darklinkpower** [comment]
Forgot to close.
