### ISSUE TITLE
[Splash Screen] Makes some games keep flickering between keyboard and controller

### ISSUE THREAD

**Issue by mateusmedeiros** [darklinkpower/PlayniteExtensionsCollection#75]
**Extension**
Splash Screen

**Describe the bug**
It seems by https://playnite.link/forum/thread-681-post-6056.html#pid6056 that this is caused by the way Playnite uses Xinput and, somehow, Splash Screen makes Playnite keep control of the controller even with the game open.

I didn't dig deep enough to confirm this, but I could confirm that basically whenever I pressed dpad buttons or left analog stick the game in question would basically change the prompts to keyboard (changing back on any other button press and so on). It also caused a weird double input problem on at least one game (Deus Ex HR).

**To Reproduce**
Two games that caused this behavior for me where Control from Game Pass and Deus Ex: Human Revolution from Steam. The steps are basically:
  1. Install Playnite 9
  2. Install Splash Screen extension
  3. Make sure the extension is configured to show splash screens on whichever mode you're on
  4. Open Control or Deus Ex (and probably some others, but these two are the ones that triggered it for me)

Note that ticking and unticking the "Close before game opens" checkbox did not make any difference.

**Expected behavior**
Stable input on the game

**Extensions.log**
[extensions.log](https://github.com/darklinkpower/PlayniteExtensionsCollection/files/7369900/extensions.log)

**Comment by darklinkpower** [comment]
Forgot to close. This was fixed in a Playnite update.
