### ISSUE TITLE
[Search Collection] add yandex images

### ISSUE THREAD

**Issue by shakeyourbunny** [darklinkpower/PlayniteExtensionsCollection#83]
**Extension**
Search Collection

**Describe the solution you'd like**
Add search engine for Yandex Images; 

URL pattern: https://yandex.com/images/search?text=searchterm

Reason: Yandex Images has more accurate results for looking for game covers

**Comment by darklinkpower** [comment]
I thought about it and I don't like media searches as default available options in the extensions. I rewrote the extension from scratch and added support to add custom search items from settings, which you can use to add this to your installation.
