### ISSUE TITLE
[Installation Status Updater] Non-play actions incorrectly mark a game as installed

### ISSUE THREAD

**Issue by chocolatechipcats** [darklinkpower/PlayniteExtensionsCollection#87]
**Extension**
Installation Status Updater - specific to Playnite 9.xx

**Describe the bug**
When a game is not installed, _any_ actions pointing to a valid executable will result in the game being detected as "installed." This results in games unexpectedly getting marked as installed because there's a valid path to modding tools or something.

**To Reproduce**

1. Add a game.
2. Add a new "file" action pointing to a valid executable. Make sure it isn't marked as a play action.
3. Remove any other play actions (alternately, make them point to a non-valid location). Remove the installation path for good measure.
4. Mark as not uninstalled. Save metadata.
5. Run installation status updater.

**Expected behavior**
The game to remain marked as uninstalled. The only valid actions are non-play, and there's no installation path.

Thank you!

**Comment by darklinkpower** [comment]
Can you please share a screnshot of your extension setttings?

**Comment by chocolatechipcats** [comment]
Is this the extension settings? Apologies - I'm a bit confused on what you mean by that.

![2021-10-31 18_15_46-Add-ons…](https://user-images.githubusercontent.com/47759676/139601643-66a94d24-e353-415d-886f-33ea1d8bdf10.png)

Here is one of my affected games with no play action - I didn't realize when I put the original post, but it also seems that non-executables (in this case, it's a link to the strategy guide in my [eBook manager](https://manual.calibre-ebook.com/url_scheme.html)) can trigger the glitch as well:

![2021-10-31 18_23_30-Edit Game Details](https://user-images.githubusercontent.com/47759676/139601721-284817f4-c621-4392-8c19-fb7927893c9b.png)

![2021-10-31 18_23_36-Edit Game Details](https://user-images.githubusercontent.com/47759676/139601725-9c049e44-0418-4e16-9f46-0bb86be0fc1f.png)

Here is another one with a play action that points to a nonexistent location (installation path is also blank here).

![2021-10-31 18_29_18-Edit Game Details](https://user-images.githubusercontent.com/47759676/139601852-23914e99-8d5e-48ab-b98b-617e5c34dbae.png)

**Comment by darklinkpower** [comment]
The extension settings are in this subsection

![image](https://user-images.githubusercontent.com/1389286/139791869-f18ba165-1806-4b9f-9c12-248c306b58a2.png)

**Comment by chocolatechipcats** [comment]
Ah, I see the issue now - I didn't know those settings were there:

![2021-11-02 02_35_34-Add-ons…](https://user-images.githubusercontent.com/47759676/139945553-c9c5ea25-6f36-4aaa-a59a-5aba2e30175b.png)

I swapped them around. It's working as expected now. Thanks for bearing with me.
