### ISSUE TITLE
[Steam Game Import] Import from Depressurizer ignores the Playnite game import exclusion list

### ISSUE THREAD

**Issue by shakeyourbunny** [darklinkpower/PlayniteExtensionsCollection#91]
**Extension**
Steam Game Import

**Describe the bug**
If you are importing games from Depressurizer, this extension ignores any games from the import exclusion list from PlayNite. 

Would you be so kind to fix this that the game import exclusion list is taken into consideration during import?

**To Reproduce**
Select Extensions Menu -> Steam Game Importer -> Import from Depressureizer -> ( select data file ) -> press OK.

**Expected behavior**
The extension should consider and not ignore the Playnite Game Import Exclusion list.

**Comment by darklinkpower** [comment]
Done
