### ISSUE TITLE
[Extra Metadata Tools] The "download logo from Google" dialog has the width and the height of images backward

### ISSUE THREAD

**Issue by udese** [darklinkpower/PlayniteExtensionsCollection#93]
**Extension**
Extra Metadata Tools

**Describe the bug**
The annotated size below each result when using the "download logo from Google" functionality is displayed as _height x width_ instead of _width x height_.
This doesn't happen in the built-in Playnite `Google Images` functionality.

**To Reproduce**
right-click on a game and go to `Extra Metadata Tools > Logos > Download logos for selected games from Google`.

**Screenshots**
![EHZqigzgI6](https://user-images.githubusercontent.com/60602698/139764798-5ad7d590-2b17-4d24-a005-d77c20f26a6b.png)

**Comment by darklinkpower** [comment]
Fixed in functionality reimplementation in `Extra Metadata Loader` extension.
