### ISSUE TITLE
[ExtraMetadataLoader] Delete Logo doesn't work

### ISSUE THREAD

**Issue by Andei** [darklinkpower/PlayniteExtensionsCollection#95]
**Extension**
ExtraMetadataLoader

**Describe the bug**
Delete Logo doesn't work. Popup says done, but logo is still in folder and Playnite details view. 
If I want to overwrite it with new downloaded logo from google there's no popup to ask to overwrite existing one.
Instead you got the error as in screenshot after trying to download

**To Reproduce**
see above 

**Expected behavior**

**Screenshots**
![Playnite DesktopApp_mXCEVDhOVY](https://user-images.githubusercontent.com/7351090/140060991-557d1583-630d-44b9-93ba-959baf27df7f.png)

**Extensions log**
`03-11 13:33:38.635|ERROR|ExtraMetadataLoader#ExtraMetadataHelper:Error while deleting game logo C:\Users\andre\SynologyDrive\Playnite814\ExtraMetadata\games\1f719ba6-fe77-4592-b95d-d42d25648a52\Logo.png
System.IO.IOException: Der Prozess kann nicht auf die Datei "C:\Users\andre\SynologyDrive\Playnite814\ExtraMetadata\games\1f719ba6-fe77-4592-b95d-d42d25648a52\Logo.png" zugreifen, da sie von einem anderen Prozess verwendet wird.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalDelete(String path, Boolean checkHost)
   bei System.IO.File.Delete(String path)
   bei ExtraMetadataLoader.Helpers.ExtraMetadataHelper.DeleteGameLogo(Game game) in C:\Users\Brandon\source\repos\PlayniteScriptExtensions\source\Generic\ExtraMetadataLoader\Helpers\ExtraMetadataHelper.cs:Zeile 89.
03-11 13:33:58.003|DEBUG|ExtraMetadataLoader#HttpDownloader:DownloadStringWithHeadersAsync method with url https://www.steamgriddb.com/api/v2/search/autocomplete/Dungeon%20Siege%3A%20Legends%20of%20Aranna
03-11 13:33:58.457|DEBUG|ExtraMetadataLoader#HttpDownloader:Ran to completion
03-11 13:34:02.338|DEBUG|ExtraMetadataLoader#HttpDownloader:DownloadStringWithHeadersAsync method with url https://www.steamgriddb.com/api/v2/search/autocomplete/Dungeon%20Siege%3A%20Legends%20of%20Aranna
03-11 13:34:02.540|DEBUG|ExtraMetadataLoader#HttpDownloader:Ran to completion
03-11 13:34:10.181|DEBUG|ExtraMetadataLoader#HttpDownloader:DownloadStringWithHeadersAsync method with url https://www.steamgriddb.com/api/v2/search/autocomplete/Dungeon%20Siege%20Legends%20of%20Aranna
03-11 13:34:10.420|DEBUG|ExtraMetadataLoader#HttpDownloader:Ran to completion
03-11 13:34:37.165|INFO |Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e#PS:Error downloading file "https://static.wikia.nocookie.net/dungeonsiege/images/a/a8/Legends_of_Aranna_Logo.png/revision/latest?cb=20200716085915". Error: Ausnahme beim Aufrufen von "DownloadFile" mit 2 Argument(en):  "Ausnahmefehler während einer WebClient-Anforderung."
`

**Comment by darklinkpower** [comment]
This is an issue caused by the custom theme you are using not properly loading the logos and locking them. You need to contact its developer to fix it.
