### ISSUE TITLE
[extra metadata loader] Make downloading video's for only steam / PC Games optional

### ISSUE THREAD

**Issue by joyrider3774** [darklinkpower/PlayniteExtensionsCollection#97]
**Extension**
Extra Metadata Loader

**Describe the solution you'd like**
Make downloading video's for only steam / PC Games optional, i used the functionality also for xbox and playstation (console) games. As for a lot of games on those platforms the games also exists on steam and the video / microtrailer can be used

**Screenshots**
![image](https://user-images.githubusercontent.com/10714776/140418562-a9204d6f-d382-493e-acf5-e4357eab6409.png)

**Comment by darklinkpower** [comment]
Done in latest version.
