### ISSUE TITLE
[PlayState] Don't count paused time as play time

### ISSUE THREAD

**Issue by BanCrash** [darklinkpower/PlayniteExtensionsCollection#99]
**Extension**
PlayState

**Describe the solution you'd like**
- I think it shouldn't account the paused time as play time, since you are pausing the process.

- Also would like to have the option to just pause the play time without pausing the process to use it with online games that could have issues when pausing the process, but I assume this should be made from another extension rather than this one.

**Comment by darklinkpower** [comment]
Done in https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/3fcfd15a8c7542944860bb5b826f1a7f03c32938 and https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/340049723aaeba20db1fb55be0e3f99ce27bf692

**Comment by BanCrash** [comment]
> Done in [3fcfd15](https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/3fcfd15a8c7542944860bb5b826f1a7f03c32938) and [3400497](https://github.com/darklinkpower/PlayniteExtensionsCollection/commit/340049723aaeba20db1fb55be0e3f99ce27bf692)

Wow, that was fast, thank you so much!
